/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NedapOnsApi);
  }
}(this, function(expect, NedapOnsApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('AdminBackgroundImage', function() {
      beforeEach(function() {
        instance = new NedapOnsApi.AdminBackgroundImage();
      });

      it('should create an instance of AdminBackgroundImage', function() {
        // TODO: update the code to test AdminBackgroundImage
        expect(instance).to.be.a(NedapOnsApi.AdminBackgroundImage);
      });

      it('should have the property isGradient (base name: "isGradient")', function() {
        // TODO: update the code to test the property isGradient
        expect(instance).to.have.property('isGradient');
        // expect(instance.isGradient).to.be(expectedValueLiteral);
      });

      it('should have the property backgroundPath (base name: "backgroundPath")', function() {
        // TODO: update the code to test the property backgroundPath
        expect(instance).to.have.property('backgroundPath');
        // expect(instance.backgroundPath).to.be(expectedValueLiteral);
      });

      it('should have the property color (base name: "color")', function() {
        // TODO: update the code to test the property color
        expect(instance).to.have.property('color');
        // expect(instance.color).to.be(expectedValueLiteral);
      });

    });
  });

}));
