/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NedapOnsApi);
  }
}(this, function(expect, NedapOnsApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('BankAccount', function() {
      beforeEach(function() {
        instance = new NedapOnsApi.BankAccount();
      });

      it('should create an instance of BankAccount', function() {
        // TODO: update the code to test BankAccount
        expect(instance).to.be.a(NedapOnsApi.BankAccount);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property _number (base name: "number")', function() {
        // TODO: update the code to test the property _number
        expect(instance).to.have.property('_number');
        // expect(instance._number).to.be(expectedValueLiteral);
      });

      it('should have the property nameOfOwner (base name: "nameOfOwner")', function() {
        // TODO: update the code to test the property nameOfOwner
        expect(instance).to.have.property('nameOfOwner');
        // expect(instance.nameOfOwner).to.be(expectedValueLiteral);
      });

      it('should have the property cityOfOwner (base name: "cityOfOwner")', function() {
        // TODO: update the code to test the property cityOfOwner
        expect(instance).to.have.property('cityOfOwner');
        // expect(instance.cityOfOwner).to.be(expectedValueLiteral);
      });

      it('should have the property iban (base name: "iban")', function() {
        // TODO: update the code to test the property iban
        expect(instance).to.have.property('iban');
        // expect(instance.iban).to.be(expectedValueLiteral);
      });

      it('should have the property bic (base name: "bic")', function() {
        // TODO: update the code to test the property bic
        expect(instance).to.have.property('bic');
        // expect(instance.bic).to.be(expectedValueLiteral);
      });

      it('should have the property creditBankAccount (base name: "creditBankAccount")', function() {
        // TODO: update the code to test the property creditBankAccount
        expect(instance).to.have.property('creditBankAccount');
        // expect(instance.creditBankAccount).to.be(expectedValueLiteral);
      });

      it('should have the property authorizationDate (base name: "authorizationDate")', function() {
        // TODO: update the code to test the property authorizationDate
        expect(instance).to.have.property('authorizationDate');
        // expect(instance.authorizationDate).to.be(expectedValueLiteral);
      });

      it('should have the property createdAt (base name: "createdAt")', function() {
        // TODO: update the code to test the property createdAt
        expect(instance).to.have.property('createdAt');
        // expect(instance.createdAt).to.be(expectedValueLiteral);
      });

      it('should have the property updatedAt (base name: "updatedAt")', function() {
        // TODO: update the code to test the property updatedAt
        expect(instance).to.have.property('updatedAt');
        // expect(instance.updatedAt).to.be(expectedValueLiteral);
      });

    });
  });

}));
