/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NedapOnsApi);
  }
}(this, function(expect, NedapOnsApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Bsn', function() {
      beforeEach(function() {
        instance = new NedapOnsApi.Bsn();
      });

      it('should create an instance of Bsn', function() {
        // TODO: update the code to test Bsn
        expect(instance).to.be.a(NedapOnsApi.Bsn);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property clientId (base name: "clientId")', function() {
        // TODO: update the code to test the property clientId
        expect(instance).to.have.property('clientId');
        // expect(instance.clientId).to.be(expectedValueLiteral);
      });

      it('should have the property _number (base name: "number")', function() {
        // TODO: update the code to test the property _number
        expect(instance).to.have.property('_number');
        // expect(instance._number).to.be(expectedValueLiteral);
      });

      it('should have the property sourceVerified (base name: "sourceVerified")', function() {
        // TODO: update the code to test the property sourceVerified
        expect(instance).to.have.property('sourceVerified');
        // expect(instance.sourceVerified).to.be(expectedValueLiteral);
      });

      it('should have the property idVerified (base name: "idVerified")', function() {
        // TODO: update the code to test the property idVerified
        expect(instance).to.have.property('idVerified');
        // expect(instance.idVerified).to.be(expectedValueLiteral);
      });

      it('should have the property idNumber (base name: "idNumber")', function() {
        // TODO: update the code to test the property idNumber
        expect(instance).to.have.property('idNumber');
        // expect(instance.idNumber).to.be(expectedValueLiteral);
      });

      it('should have the property idType (base name: "idType")', function() {
        // TODO: update the code to test the property idType
        expect(instance).to.have.property('idType');
        // expect(instance.idType).to.be(expectedValueLiteral);
      });

      it('should have the property source (base name: "source")', function() {
        // TODO: update the code to test the property source
        expect(instance).to.have.property('source');
        // expect(instance.source).to.be(expectedValueLiteral);
      });

      it('should have the property idVerifiedType (base name: "idVerifiedType")', function() {
        // TODO: update the code to test the property idVerifiedType
        expect(instance).to.have.property('idVerifiedType');
        // expect(instance.idVerifiedType).to.be(expectedValueLiteral);
      });

      it('should have the property idVerifiedDate (base name: "idVerifiedDate")', function() {
        // TODO: update the code to test the property idVerifiedDate
        expect(instance).to.have.property('idVerifiedDate');
        // expect(instance.idVerifiedDate).to.be(expectedValueLiteral);
      });

      it('should have the property bsnUnknown (base name: "bsnUnknown")', function() {
        // TODO: update the code to test the property bsnUnknown
        expect(instance).to.have.property('bsnUnknown');
        // expect(instance.bsnUnknown).to.be(expectedValueLiteral);
      });

      it('should have the property reasonBsnUnknown (base name: "reasonBsnUnknown")', function() {
        // TODO: update the code to test the property reasonBsnUnknown
        expect(instance).to.have.property('reasonBsnUnknown');
        // expect(instance.reasonBsnUnknown).to.be(expectedValueLiteral);
      });

      it('should have the property idValidUntil (base name: "idValidUntil")', function() {
        // TODO: update the code to test the property idValidUntil
        expect(instance).to.have.property('idValidUntil');
        // expect(instance.idValidUntil).to.be(expectedValueLiteral);
      });

      it('should have the property bsnVerifiedDate (base name: "bsnVerifiedDate")', function() {
        // TODO: update the code to test the property bsnVerifiedDate
        expect(instance).to.have.property('bsnVerifiedDate');
        // expect(instance.bsnVerifiedDate).to.be(expectedValueLiteral);
      });

      it('should have the property widVerified (base name: "widVerified")', function() {
        // TODO: update the code to test the property widVerified
        expect(instance).to.have.property('widVerified');
        // expect(instance.widVerified).to.be(expectedValueLiteral);
      });

      it('should have the property verifiedByEmployeeId (base name: "verifiedByEmployeeId")', function() {
        // TODO: update the code to test the property verifiedByEmployeeId
        expect(instance).to.have.property('verifiedByEmployeeId');
        // expect(instance.verifiedByEmployeeId).to.be(expectedValueLiteral);
      });

      it('should have the property bsnDocumentType (base name: "bsnDocumentType")', function() {
        // TODO: update the code to test the property bsnDocumentType
        expect(instance).to.have.property('bsnDocumentType');
        // expect(instance.bsnDocumentType).to.be(expectedValueLiteral);
      });

      it('should have the property bsnSource (base name: "bsnSource")', function() {
        // TODO: update the code to test the property bsnSource
        expect(instance).to.have.property('bsnSource');
        // expect(instance.bsnSource).to.be(expectedValueLiteral);
      });

      it('should have the property bsnIdVerifiedType (base name: "bsnIdVerifiedType")', function() {
        // TODO: update the code to test the property bsnIdVerifiedType
        expect(instance).to.have.property('bsnIdVerifiedType');
        // expect(instance.bsnIdVerifiedType).to.be(expectedValueLiteral);
      });

    });
  });

}));
