/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NedapOnsApi);
  }
}(this, function(expect, NedapOnsApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Coding', function() {
      beforeEach(function() {
        instance = new NedapOnsApi.Coding();
      });

      it('should create an instance of Coding', function() {
        // TODO: update the code to test Coding
        expect(instance).to.be.a(NedapOnsApi.Coding);
      });

      it('should have the property system (base name: "system")', function() {
        // TODO: update the code to test the property system
        expect(instance).to.have.property('system');
        // expect(instance.system).to.be(expectedValueLiteral);
      });

      it('should have the property code (base name: "code")', function() {
        // TODO: update the code to test the property code
        expect(instance).to.have.property('code');
        // expect(instance.code).to.be(expectedValueLiteral);
      });

      it('should have the property display (base name: "display")', function() {
        // TODO: update the code to test the property display
        expect(instance).to.have.property('display');
        // expect(instance.display).to.be(expectedValueLiteral);
      });

    });
  });

}));
