/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NedapOnsApi);
  }
}(this, function(expect, NedapOnsApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('DbcGgzZorgtype', function() {
      beforeEach(function() {
        instance = new NedapOnsApi.DbcGgzZorgtype();
      });

      it('should create an instance of DbcGgzZorgtype', function() {
        // TODO: update the code to test DbcGgzZorgtype
        expect(instance).to.be.a(NedapOnsApi.DbcGgzZorgtype);
      });

      it('should have the property groepcode (base name: "groepcode")', function() {
        // TODO: update the code to test the property groepcode
        expect(instance).to.have.property('groepcode');
        // expect(instance.groepcode).to.be(expectedValueLiteral);
      });

      it('should have the property element (base name: "element")', function() {
        // TODO: update the code to test the property element
        expect(instance).to.have.property('element');
        // expect(instance.element).to.be(expectedValueLiteral);
      });

      it('should have the property hierarchieniveau (base name: "hierarchieniveau")', function() {
        // TODO: update the code to test the property hierarchieniveau
        expect(instance).to.have.property('hierarchieniveau');
        // expect(instance.hierarchieniveau).to.be(expectedValueLiteral);
      });

      it('should have the property selecteerbaar (base name: "selecteerbaar")', function() {
        // TODO: update the code to test the property selecteerbaar
        expect(instance).to.have.property('selecteerbaar');
        // expect(instance.selecteerbaar).to.be(expectedValueLiteral);
      });

      it('should have the property sorteervolgorde (base name: "sorteervolgorde")', function() {
        // TODO: update the code to test the property sorteervolgorde
        expect(instance).to.have.property('sorteervolgorde');
        // expect(instance.sorteervolgorde).to.be(expectedValueLiteral);
      });

      it('should have the property prestatiecodedeel (base name: "prestatiecodedeel")', function() {
        // TODO: update the code to test the property prestatiecodedeel
        expect(instance).to.have.property('prestatiecodedeel');
        // expect(instance.prestatiecodedeel).to.be(expectedValueLiteral);
      });

      it('should have the property brancheIndicatie (base name: "brancheIndicatie")', function() {
        // TODO: update the code to test the property brancheIndicatie
        expect(instance).to.have.property('brancheIndicatie');
        // expect(instance.brancheIndicatie).to.be(expectedValueLiteral);
      });

    });
  });

}));
