/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NedapOnsApi);
  }
}(this, function(expect, NedapOnsApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('DossierMedicalInvoluntaryCareLegalStatus', function() {
      beforeEach(function() {
        instance = new NedapOnsApi.DossierMedicalInvoluntaryCareLegalStatus();
      });

      it('should create an instance of DossierMedicalInvoluntaryCareLegalStatus', function() {
        // TODO: update the code to test DossierMedicalInvoluntaryCareLegalStatus
        expect(instance).to.be.a(NedapOnsApi.DossierMedicalInvoluntaryCareLegalStatus);
      });

      it('should have the property status (base name: "status")', function() {
        // TODO: update the code to test the property status
        expect(instance).to.have.property('status');
        // expect(instance.status).to.be(expectedValueLiteral);
      });

      it('should have the property code (base name: "code")', function() {
        // TODO: update the code to test the property code
        expect(instance).to.have.property('code');
        // expect(instance.code).to.be(expectedValueLiteral);
      });

      it('should have the property beginDate (base name: "beginDate")', function() {
        // TODO: update the code to test the property beginDate
        expect(instance).to.have.property('beginDate');
        // expect(instance.beginDate).to.be(expectedValueLiteral);
      });

      it('should have the property endDate (base name: "endDate")', function() {
        // TODO: update the code to test the property endDate
        expect(instance).to.have.property('endDate');
        // expect(instance.endDate).to.be(expectedValueLiteral);
      });

      it('should have the property expirationDate (base name: "expirationDate")', function() {
        // TODO: update the code to test the property expirationDate
        expect(instance).to.have.property('expirationDate');
        // expect(instance.expirationDate).to.be(expectedValueLiteral);
      });

      it('should have the property comments (base name: "comments")', function() {
        // TODO: update the code to test the property comments
        expect(instance).to.have.property('comments');
        // expect(instance.comments).to.be(expectedValueLiteral);
      });

      it('should have the property endingReason (base name: "endingReason")', function() {
        // TODO: update the code to test the property endingReason
        expect(instance).to.have.property('endingReason');
        // expect(instance.endingReason).to.be(expectedValueLiteral);
      });

      it('should have the property documentId (base name: "documentId")', function() {
        // TODO: update the code to test the property documentId
        expect(instance).to.have.property('documentId');
        // expect(instance.documentId).to.be(expectedValueLiteral);
      });

      it('should have the property documentName (base name: "documentName")', function() {
        // TODO: update the code to test the property documentName
        expect(instance).to.have.property('documentName');
        // expect(instance.documentName).to.be(expectedValueLiteral);
      });

      it('should have the property archived (base name: "archived")', function() {
        // TODO: update the code to test the property archived
        expect(instance).to.have.property('archived');
        // expect(instance.archived).to.be(expectedValueLiteral);
      });

      it('should have the property request (base name: "request")', function() {
        // TODO: update the code to test the property request
        expect(instance).to.have.property('request');
        // expect(instance.request).to.be(expectedValueLiteral);
      });

      it('should have the property legalStatusDocuments (base name: "legalStatusDocuments")', function() {
        // TODO: update the code to test the property legalStatusDocuments
        expect(instance).to.have.property('legalStatusDocuments');
        // expect(instance.legalStatusDocuments).to.be(expectedValueLiteral);
      });

      it('should have the property legalStatusSuspensions (base name: "legalStatusSuspensions")', function() {
        // TODO: update the code to test the property legalStatusSuspensions
        expect(instance).to.have.property('legalStatusSuspensions');
        // expect(instance.legalStatusSuspensions).to.be(expectedValueLiteral);
      });

      it('should have the property legalGrounds (base name: "legalGrounds")', function() {
        // TODO: update the code to test the property legalGrounds
        expect(instance).to.have.property('legalGrounds');
        // expect(instance.legalGrounds).to.be(expectedValueLiteral);
      });

    });
  });

}));
