/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NedapOnsApi);
  }
}(this, function(expect, NedapOnsApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('DossierCarePlanSignatureRequirementDiscussionType', function() {
      beforeEach(function() {
        instance = NedapOnsApi.DossierCarePlanSignatureRequirementDiscussionType;
      });

      it('should create an instance of DossierCarePlanSignatureRequirementDiscussionType', function() {
        // TODO: update the code to test DossierCarePlanSignatureRequirementDiscussionType
        expect(instance).to.be.a('object');
      });

      it('should have the property discussed', function() {
        expect(instance).to.have.property('discussed');
        expect(instance.discussed).to.be("discussed");
      });

      it('should have the property discussedLater', function() {
        expect(instance).to.have.property('discussedLater');
        expect(instance.discussedLater).to.be("discussed_later");
      });

      it('should have the property noDiscussion', function() {
        expect(instance).to.have.property('noDiscussion');
        expect(instance.noDiscussion).to.be("no_discussion");
      });

      it('should have the property noAgreement', function() {
        expect(instance).to.have.property('noAgreement');
        expect(instance.noAgreement).to.be("no_agreement");
      });

    });
  });

}));
