/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NedapOnsApi);
  }
}(this, function(expect, NedapOnsApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('DossierActionEntry', function() {
      beforeEach(function() {
        instance = new NedapOnsApi.DossierActionEntry();
      });

      it('should create an instance of DossierActionEntry', function() {
        // TODO: update the code to test DossierActionEntry
        expect(instance).to.be.a(NedapOnsApi.DossierActionEntry);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property carePlanEntryId (base name: "carePlanEntryId")', function() {
        // TODO: update the code to test the property carePlanEntryId
        expect(instance).to.have.property('carePlanEntryId');
        // expect(instance.carePlanEntryId).to.be(expectedValueLiteral);
      });

      it('should have the property action (base name: "action")', function() {
        // TODO: update the code to test the property action
        expect(instance).to.have.property('action');
        // expect(instance.action).to.be(expectedValueLiteral);
      });

      it('should have the property actionId (base name: "actionId")', function() {
        // TODO: update the code to test the property actionId
        expect(instance).to.have.property('actionId');
        // expect(instance.actionId).to.be(expectedValueLiteral);
      });

      it('should have the property carePlanPersistentActionId (base name: "carePlanPersistentActionId")', function() {
        // TODO: update the code to test the property carePlanPersistentActionId
        expect(instance).to.have.property('carePlanPersistentActionId');
        // expect(instance.carePlanPersistentActionId).to.be(expectedValueLiteral);
      });

      it('should have the property comment (base name: "comment")', function() {
        // TODO: update the code to test the property comment
        expect(instance).to.have.property('comment');
        // expect(instance.comment).to.be(expectedValueLiteral);
      });

      it('should have the property title (base name: "title")', function() {
        // TODO: update the code to test the property title
        expect(instance).to.have.property('title');
        // expect(instance.title).to.be(expectedValueLiteral);
      });

    });
  });

}));
