/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NedapOnsApi);
  }
}(this, function(expect, NedapOnsApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('DossierRestrictiveMeasureCarePlanEntryJudgement', function() {
      beforeEach(function() {
        instance = new NedapOnsApi.DossierRestrictiveMeasureCarePlanEntryJudgement();
      });

      it('should create an instance of DossierRestrictiveMeasureCarePlanEntryJudgement', function() {
        // TODO: update the code to test DossierRestrictiveMeasureCarePlanEntryJudgement
        expect(instance).to.be.a(NedapOnsApi.DossierRestrictiveMeasureCarePlanEntryJudgement);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property restrictiveMeasureCarePlanEntryId (base name: "restrictiveMeasureCarePlanEntryId")', function() {
        // TODO: update the code to test the property restrictiveMeasureCarePlanEntryId
        expect(instance).to.have.property('restrictiveMeasureCarePlanEntryId');
        // expect(instance.restrictiveMeasureCarePlanEntryId).to.be(expectedValueLiteral);
      });

      it('should have the property status (base name: "status")', function() {
        // TODO: update the code to test the property status
        expect(instance).to.have.property('status');
        // expect(instance.status).to.be(expectedValueLiteral);
      });

      it('should have the property text (base name: "text")', function() {
        // TODO: update the code to test the property text
        expect(instance).to.have.property('text');
        // expect(instance.text).to.be(expectedValueLiteral);
      });

      it('should have the property clientExternalId (base name: "clientExternalId")', function() {
        // TODO: update the code to test the property clientExternalId
        expect(instance).to.have.property('clientExternalId');
        // expect(instance.clientExternalId).to.be(expectedValueLiteral);
      });

      it('should have the property reviewerUserId (base name: "reviewerUserId")', function() {
        // TODO: update the code to test the property reviewerUserId
        expect(instance).to.have.property('reviewerUserId');
        // expect(instance.reviewerUserId).to.be(expectedValueLiteral);
      });

      it('should have the property reviewedAt (base name: "reviewedAt")', function() {
        // TODO: update the code to test the property reviewedAt
        expect(instance).to.have.property('reviewedAt');
        // expect(instance.reviewedAt).to.be(expectedValueLiteral);
      });

      it('should have the property createdById (base name: "createdById")', function() {
        // TODO: update the code to test the property createdById
        expect(instance).to.have.property('createdById');
        // expect(instance.createdById).to.be(expectedValueLiteral);
      });

      it('should have the property updatedById (base name: "updatedById")', function() {
        // TODO: update the code to test the property updatedById
        expect(instance).to.have.property('updatedById');
        // expect(instance.updatedById).to.be(expectedValueLiteral);
      });

      it('should have the property createdAt (base name: "createdAt")', function() {
        // TODO: update the code to test the property createdAt
        expect(instance).to.have.property('createdAt');
        // expect(instance.createdAt).to.be(expectedValueLiteral);
      });

      it('should have the property updatedAt (base name: "updatedAt")', function() {
        // TODO: update the code to test the property updatedAt
        expect(instance).to.have.property('updatedAt');
        // expect(instance.updatedAt).to.be(expectedValueLiteral);
      });

    });
  });

}));
