/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NedapOnsApi);
  }
}(this, function(expect, NedapOnsApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ExpenseExpenseType', function() {
      beforeEach(function() {
        instance = new NedapOnsApi.ExpenseExpenseType();
      });

      it('should create an instance of ExpenseExpenseType', function() {
        // TODO: update the code to test ExpenseExpenseType
        expect(instance).to.be.a(NedapOnsApi.ExpenseExpenseType);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property name (base name: "name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

      it('should have the property unit (base name: "unit")', function() {
        // TODO: update the code to test the property unit
        expect(instance).to.have.property('unit');
        // expect(instance.unit).to.be(expectedValueLiteral);
      });

      it('should have the property inputType (base name: "inputType")', function() {
        // TODO: update the code to test the property inputType
        expect(instance).to.have.property('inputType');
        // expect(instance.inputType).to.be(expectedValueLiteral);
      });

      it('should have the property format (base name: "format")', function() {
        // TODO: update the code to test the property format
        expect(instance).to.have.property('format');
        // expect(instance.format).to.be(expectedValueLiteral);
      });

      it('should have the property icon (base name: "icon")', function() {
        // TODO: update the code to test the property icon
        expect(instance).to.have.property('icon');
        // expect(instance.icon).to.be(expectedValueLiteral);
      });

      it('should have the property exportCode (base name: "exportCode")', function() {
        // TODO: update the code to test the property exportCode
        expect(instance).to.have.property('exportCode');
        // expect(instance.exportCode).to.be(expectedValueLiteral);
      });

      it('should have the property exportCodeGreaterThanTen (base name: "exportCodeGreaterThanTen")', function() {
        // TODO: update the code to test the property exportCodeGreaterThanTen
        expect(instance).to.have.property('exportCodeGreaterThanTen');
        // expect(instance.exportCodeGreaterThanTen).to.be(expectedValueLiteral);
      });

      it('should have the property compensationInCents (base name: "compensationInCents")', function() {
        // TODO: update the code to test the property compensationInCents
        expect(instance).to.have.property('compensationInCents');
        // expect(instance.compensationInCents).to.be(expectedValueLiteral);
      });

      it('should have the property compensationInCentsGreaterThanTen (base name: "compensationInCentsGreaterThanTen")', function() {
        // TODO: update the code to test the property compensationInCentsGreaterThanTen
        expect(instance).to.have.property('compensationInCentsGreaterThanTen');
        // expect(instance.compensationInCentsGreaterThanTen).to.be(expectedValueLiteral);
      });

      it('should have the property removed (base name: "removed")', function() {
        // TODO: update the code to test the property removed
        expect(instance).to.have.property('removed');
        // expect(instance.removed).to.be(expectedValueLiteral);
      });

      it('should have the property travelCalculationEnabled (base name: "travelCalculationEnabled")', function() {
        // TODO: update the code to test the property travelCalculationEnabled
        expect(instance).to.have.property('travelCalculationEnabled');
        // expect(instance.travelCalculationEnabled).to.be(expectedValueLiteral);
      });

      it('should have the property beginDate (base name: "beginDate")', function() {
        // TODO: update the code to test the property beginDate
        expect(instance).to.have.property('beginDate');
        // expect(instance.beginDate).to.be(expectedValueLiteral);
      });

      it('should have the property endDate (base name: "endDate")', function() {
        // TODO: update the code to test the property endDate
        expect(instance).to.have.property('endDate');
        // expect(instance.endDate).to.be(expectedValueLiteral);
      });

      it('should have the property alternativeToTravelCalc (base name: "alternativeToTravelCalc")', function() {
        // TODO: update the code to test the property alternativeToTravelCalc
        expect(instance).to.have.property('alternativeToTravelCalc');
        // expect(instance.alternativeToTravelCalc).to.be(expectedValueLiteral);
      });

    });
  });

}));
