/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NedapOnsApi);
  }
}(this, function(expect, NedapOnsApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('FinanceInvoiceRowFinanceLog', function() {
      beforeEach(function() {
        instance = new NedapOnsApi.FinanceInvoiceRowFinanceLog();
      });

      it('should create an instance of FinanceInvoiceRowFinanceLog', function() {
        // TODO: update the code to test FinanceInvoiceRowFinanceLog
        expect(instance).to.be.a(NedapOnsApi.FinanceInvoiceRowFinanceLog);
      });

      it('should have the property invoiceRowId (base name: "invoiceRowId")', function() {
        // TODO: update the code to test the property invoiceRowId
        expect(instance).to.have.property('invoiceRowId');
        // expect(instance.invoiceRowId).to.be(expectedValueLiteral);
      });

      it('should have the property financeLogId (base name: "financeLogId")', function() {
        // TODO: update the code to test the property financeLogId
        expect(instance).to.have.property('financeLogId');
        // expect(instance.financeLogId).to.be(expectedValueLiteral);
      });

    });
  });

}));
