/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NedapOnsApi);
  }
}(this, function(expect, NedapOnsApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('FinanceListGroupActivityModelList', function() {
      beforeEach(function() {
        instance = new NedapOnsApi.FinanceListGroupActivityModelList();
      });

      it('should create an instance of FinanceListGroupActivityModelList', function() {
        // TODO: update the code to test FinanceListGroupActivityModelList
        expect(instance).to.be.a(NedapOnsApi.FinanceListGroupActivityModelList);
      });

      it('should have the property groupActivities (base name: "groupActivities")', function() {
        // TODO: update the code to test the property groupActivities
        expect(instance).to.have.property('groupActivities');
        // expect(instance.groupActivities).to.be(expectedValueLiteral);
      });

    });
  });

}));
