/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NedapOnsApi);
  }
}(this, function(expect, NedapOnsApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('GroupcareOccurrence', function() {
      beforeEach(function() {
        instance = new NedapOnsApi.GroupcareOccurrence();
      });

      it('should create an instance of GroupcareOccurrence', function() {
        // TODO: update the code to test GroupcareOccurrence
        expect(instance).to.be.a(NedapOnsApi.GroupcareOccurrence);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property _date (base name: "date")', function() {
        // TODO: update the code to test the property _date
        expect(instance).to.have.property('_date');
        // expect(instance._date).to.be(expectedValueLiteral);
      });

      it('should have the property startTime (base name: "startTime")', function() {
        // TODO: update the code to test the property startTime
        expect(instance).to.have.property('startTime');
        // expect(instance.startTime).to.be(expectedValueLiteral);
      });

      it('should have the property endTime (base name: "endTime")', function() {
        // TODO: update the code to test the property endTime
        expect(instance).to.have.property('endTime');
        // expect(instance.endTime).to.be(expectedValueLiteral);
      });

      it('should have the property groupId (base name: "groupId")', function() {
        // TODO: update the code to test the property groupId
        expect(instance).to.have.property('groupId');
        // expect(instance.groupId).to.be(expectedValueLiteral);
      });

      it('should have the property groupName (base name: "groupName")', function() {
        // TODO: update the code to test the property groupName
        expect(instance).to.have.property('groupName');
        // expect(instance.groupName).to.be(expectedValueLiteral);
      });

      it('should have the property locationName (base name: "locationName")', function() {
        // TODO: update the code to test the property locationName
        expect(instance).to.have.property('locationName');
        // expect(instance.locationName).to.be(expectedValueLiteral);
      });

      it('should have the property locationId (base name: "locationId")', function() {
        // TODO: update the code to test the property locationId
        expect(instance).to.have.property('locationId');
        // expect(instance.locationId).to.be(expectedValueLiteral);
      });

      it('should have the property registration (base name: "registration")', function() {
        // TODO: update the code to test the property registration
        expect(instance).to.have.property('registration');
        // expect(instance.registration).to.be(expectedValueLiteral);
      });

      it('should have the property employeeIds (base name: "employeeIds")', function() {
        // TODO: update the code to test the property employeeIds
        expect(instance).to.have.property('employeeIds');
        // expect(instance.employeeIds).to.be(expectedValueLiteral);
      });

      it('should have the property recurrenceType (base name: "recurrenceType")', function() {
        // TODO: update the code to test the property recurrenceType
        expect(instance).to.have.property('recurrenceType');
        // expect(instance.recurrenceType).to.be(expectedValueLiteral);
      });

      it('should have the property recurrenceInterval (base name: "recurrenceInterval")', function() {
        // TODO: update the code to test the property recurrenceInterval
        expect(instance).to.have.property('recurrenceInterval');
        // expect(instance.recurrenceInterval).to.be(expectedValueLiteral);
      });

    });
  });

}));
