/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NedapOnsApi);
  }
}(this, function(expect, NedapOnsApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('HermesCareProviderSettings', function() {
      beforeEach(function() {
        instance = new NedapOnsApi.HermesCareProviderSettings();
      });

      it('should create an instance of HermesCareProviderSettings', function() {
        // TODO: update the code to test HermesCareProviderSettings
        expect(instance).to.be.a(NedapOnsApi.HermesCareProviderSettings);
      });

      it('should have the property enabled (base name: "enabled")', function() {
        // TODO: update the code to test the property enabled
        expect(instance).to.have.property('enabled');
        // expect(instance.enabled).to.be(expectedValueLiteral);
      });

      it('should have the property defaultTemplateSet (base name: "defaultTemplateSet")', function() {
        // TODO: update the code to test the property defaultTemplateSet
        expect(instance).to.have.property('defaultTemplateSet');
        // expect(instance.defaultTemplateSet).to.be(expectedValueLiteral);
      });

      it('should have the property defaultContactMethod (base name: "defaultContactMethod")', function() {
        // TODO: update the code to test the property defaultContactMethod
        expect(instance).to.have.property('defaultContactMethod');
        // expect(instance.defaultContactMethod).to.be(expectedValueLiteral);
      });

    });
  });

}));
