/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NedapOnsApi);
  }
}(this, function(expect, NedapOnsApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('MedicationDoubleCheckChange', function() {
      beforeEach(function() {
        instance = new NedapOnsApi.MedicationDoubleCheckChange();
      });

      it('should create an instance of MedicationDoubleCheckChange', function() {
        // TODO: update the code to test MedicationDoubleCheckChange
        expect(instance).to.be.a(NedapOnsApi.MedicationDoubleCheckChange);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property doubleCheckUuid (base name: "doubleCheckUuid")', function() {
        // TODO: update the code to test the property doubleCheckUuid
        expect(instance).to.have.property('doubleCheckUuid');
        // expect(instance.doubleCheckUuid).to.be(expectedValueLiteral);
      });

      it('should have the property senderEmployeeId (base name: "senderEmployeeId")', function() {
        // TODO: update the code to test the property senderEmployeeId
        expect(instance).to.have.property('senderEmployeeId');
        // expect(instance.senderEmployeeId).to.be(expectedValueLiteral);
      });

      it('should have the property checkerEmployeeId (base name: "checkerEmployeeId")', function() {
        // TODO: update the code to test the property checkerEmployeeId
        expect(instance).to.have.property('checkerEmployeeId');
        // expect(instance.checkerEmployeeId).to.be(expectedValueLiteral);
      });

      it('should have the property decision (base name: "decision")', function() {
        // TODO: update the code to test the property decision
        expect(instance).to.have.property('decision');
        // expect(instance.decision).to.be(expectedValueLiteral);
      });

      it('should have the property decisionReason (base name: "decisionReason")', function() {
        // TODO: update the code to test the property decisionReason
        expect(instance).to.have.property('decisionReason');
        // expect(instance.decisionReason).to.be(expectedValueLiteral);
      });

      it('should have the property decisionAt (base name: "decisionAt")', function() {
        // TODO: update the code to test the property decisionAt
        expect(instance).to.have.property('decisionAt');
        // expect(instance.decisionAt).to.be(expectedValueLiteral);
      });

    });
  });

}));
