/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NedapOnsApi);
  }
}(this, function(expect, NedapOnsApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('MovesNavigationAvailabilityState', function() {
      beforeEach(function() {
        instance = NedapOnsApi.MovesNavigationAvailabilityState;
      });

      it('should create an instance of MovesNavigationAvailabilityState', function() {
        // TODO: update the code to test MovesNavigationAvailabilityState
        expect(instance).to.be.a('object');
      });

      it('should have the property AVAILABLE', function() {
        expect(instance).to.have.property('AVAILABLE');
        expect(instance.AVAILABLE).to.be("AVAILABLE");
      });

      it('should have the property DISABLED', function() {
        expect(instance).to.have.property('DISABLED');
        expect(instance.DISABLED).to.be("DISABLED");
      });

      it('should have the property UNAVAILABLE', function() {
        expect(instance).to.have.property('UNAVAILABLE');
        expect(instance.UNAVAILABLE).to.be("UNAVAILABLE");
      });

    });
  });

}));
