/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NedapOnsApi);
  }
}(this, function(expect, NedapOnsApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('MovesPlanCardOccurrencePlanRequest', function() {
      beforeEach(function() {
        instance = new NedapOnsApi.MovesPlanCardOccurrencePlanRequest();
      });

      it('should create an instance of MovesPlanCardOccurrencePlanRequest', function() {
        // TODO: update the code to test MovesPlanCardOccurrencePlanRequest
        expect(instance).to.be.a(NedapOnsApi.MovesPlanCardOccurrencePlanRequest);
      });

      it('should have the property _date (base name: "date")', function() {
        // TODO: update the code to test the property _date
        expect(instance).to.have.property('_date');
        // expect(instance._date).to.be(expectedValueLiteral);
      });

      it('should have the property occurrenceId (base name: "occurrenceId")', function() {
        // TODO: update the code to test the property occurrenceId
        expect(instance).to.have.property('occurrenceId');
        // expect(instance.occurrenceId).to.be(expectedValueLiteral);
      });

      it('should have the property planCardChecksum (base name: "planCardChecksum")', function() {
        // TODO: update the code to test the property planCardChecksum
        expect(instance).to.have.property('planCardChecksum');
        // expect(instance.planCardChecksum).to.be(expectedValueLiteral);
      });

      it('should have the property planCardTimelineId (base name: "planCardTimelineId")', function() {
        // TODO: update the code to test the property planCardTimelineId
        expect(instance).to.have.property('planCardTimelineId');
        // expect(instance.planCardTimelineId).to.be(expectedValueLiteral);
      });

      it('should have the property fixedStartTime (base name: "fixedStartTime")', function() {
        // TODO: update the code to test the property fixedStartTime
        expect(instance).to.have.property('fixedStartTime');
        // expect(instance.fixedStartTime).to.be(expectedValueLiteral);
      });

      it('should have the property incidental (base name: "incidental")', function() {
        // TODO: update the code to test the property incidental
        expect(instance).to.have.property('incidental');
        // expect(instance.incidental).to.be(expectedValueLiteral);
      });

      it('should have the property assignment (base name: "assignment")', function() {
        // TODO: update the code to test the property assignment
        expect(instance).to.have.property('assignment');
        // expect(instance.assignment).to.be(expectedValueLiteral);
      });

      it('should have the property beforePlanCard (base name: "beforePlanCard")', function() {
        // TODO: update the code to test the property beforePlanCard
        expect(instance).to.have.property('beforePlanCard');
        // expect(instance.beforePlanCard).to.be(expectedValueLiteral);
      });

      it('should have the property afterPlanCard (base name: "afterPlanCard")', function() {
        // TODO: update the code to test the property afterPlanCard
        expect(instance).to.have.property('afterPlanCard');
        // expect(instance.afterPlanCard).to.be(expectedValueLiteral);
      });

    });
  });

}));
