/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NedapOnsApi);
  }
}(this, function(expect, NedapOnsApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Practitioner', function() {
      beforeEach(function() {
        instance = new NedapOnsApi.Practitioner();
      });

      it('should create an instance of Practitioner', function() {
        // TODO: update the code to test Practitioner
        expect(instance).to.be.a(NedapOnsApi.Practitioner);
      });

      it('should have the property agbCodes (base name: "agbCodes")', function() {
        // TODO: update the code to test the property agbCodes
        expect(instance).to.have.property('agbCodes');
        // expect(instance.agbCodes).to.be(expectedValueLiteral);
      });

      it('should have the property bigCodes (base name: "bigCodes")', function() {
        // TODO: update the code to test the property bigCodes
        expect(instance).to.have.property('bigCodes');
        // expect(instance.bigCodes).to.be(expectedValueLiteral);
      });

      it('should have the property skjCodes (base name: "skjCodes")', function() {
        // TODO: update the code to test the property skjCodes
        expect(instance).to.have.property('skjCodes');
        // expect(instance.skjCodes).to.be(expectedValueLiteral);
      });

      it('should have the property professions (base name: "professions")', function() {
        // TODO: update the code to test the property professions
        expect(instance).to.have.property('professions');
        // expect(instance.professions).to.be(expectedValueLiteral);
      });

    });
  });

}));
