/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NedapOnsApi);
  }
}(this, function(expect, NedapOnsApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('PresenceLogProduct', function() {
      beforeEach(function() {
        instance = new NedapOnsApi.PresenceLogProduct();
      });

      it('should create an instance of PresenceLogProduct', function() {
        // TODO: update the code to test PresenceLogProduct
        expect(instance).to.be.a(NedapOnsApi.PresenceLogProduct);
      });

      it('should have the property activityObjectId (base name: "activityObjectId")', function() {
        // TODO: update the code to test the property activityObjectId
        expect(instance).to.have.property('activityObjectId');
        // expect(instance.activityObjectId).to.be(expectedValueLiteral);
      });

      it('should have the property duration (base name: "duration")', function() {
        // TODO: update the code to test the property duration
        expect(instance).to.have.property('duration');
        // expect(instance.duration).to.be(expectedValueLiteral);
      });

      it('should have the property quantity (base name: "quantity")', function() {
        // TODO: update the code to test the property quantity
        expect(instance).to.have.property('quantity');
        // expect(instance.quantity).to.be(expectedValueLiteral);
      });

      it('should have the property activityDirectOrIndirect (base name: "activityDirectOrIndirect")', function() {
        // TODO: update the code to test the property activityDirectOrIndirect
        expect(instance).to.have.property('activityDirectOrIndirect');
        // expect(instance.activityDirectOrIndirect).to.be(expectedValueLiteral);
      });

      it('should have the property description (base name: "description")', function() {
        // TODO: update the code to test the property description
        expect(instance).to.have.property('description');
        // expect(instance.description).to.be(expectedValueLiteral);
      });

    });
  });

}));
