/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NedapOnsApi);
  }
}(this, function(expect, NedapOnsApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('PresenceLogPermission', function() {
      beforeEach(function() {
        instance = new NedapOnsApi.PresenceLogPermission();
      });

      it('should create an instance of PresenceLogPermission', function() {
        // TODO: update the code to test PresenceLogPermission
        expect(instance).to.be.a(NedapOnsApi.PresenceLogPermission);
      });

      it('should have the property addBefore (base name: "add_before")', function() {
        // TODO: update the code to test the property addBefore
        expect(instance).to.have.property('addBefore');
        // expect(instance.addBefore).to.be(expectedValueLiteral);
      });

      it('should have the property addAfter (base name: "add_after")', function() {
        // TODO: update the code to test the property addAfter
        expect(instance).to.have.property('addAfter');
        // expect(instance.addAfter).to.be(expectedValueLiteral);
      });

      it('should have the property modify (base name: "modify")', function() {
        // TODO: update the code to test the property modify
        expect(instance).to.have.property('modify');
        // expect(instance.modify).to.be(expectedValueLiteral);
      });

      it('should have the property remove (base name: "remove")', function() {
        // TODO: update the code to test the property remove
        expect(instance).to.have.property('remove');
        // expect(instance.remove).to.be(expectedValueLiteral);
      });

    });
  });

}));
