/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NedapOnsApi);
  }
}(this, function(expect, NedapOnsApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('PresenceLogORT', function() {
      beforeEach(function() {
        instance = new NedapOnsApi.PresenceLogORT();
      });

      it('should create an instance of PresenceLogORT', function() {
        // TODO: update the code to test PresenceLogORT
        expect(instance).to.be.a(NedapOnsApi.PresenceLogORT);
      });

      it('should have the property start (base name: "start")', function() {
        // TODO: update the code to test the property start
        expect(instance).to.have.property('start');
        // expect(instance.start).to.be(expectedValueLiteral);
      });

      it('should have the property end (base name: "end")', function() {
        // TODO: update the code to test the property end
        expect(instance).to.have.property('end');
        // expect(instance.end).to.be(expectedValueLiteral);
      });

      it('should have the property percentage (base name: "percentage")', function() {
        // TODO: update the code to test the property percentage
        expect(instance).to.have.property('percentage');
        // expect(instance.percentage).to.be(expectedValueLiteral);
      });

      it('should have the property percentageDecimal (base name: "percentageDecimal")', function() {
        // TODO: update the code to test the property percentageDecimal
        expect(instance).to.have.property('percentageDecimal');
        // expect(instance.percentageDecimal).to.be(expectedValueLiteral);
      });

      it('should have the property description (base name: "description")', function() {
        // TODO: update the code to test the property description
        expect(instance).to.have.property('description');
        // expect(instance.description).to.be(expectedValueLiteral);
      });

    });
  });

}));
