/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NedapOnsApi);
  }
}(this, function(expect, NedapOnsApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ZpmCareOrderZpmPlaatsingsbesluitnummer', function() {
      beforeEach(function() {
        instance = new NedapOnsApi.ZpmCareOrderZpmPlaatsingsbesluitnummer();
      });

      it('should create an instance of ZpmCareOrderZpmPlaatsingsbesluitnummer', function() {
        // TODO: update the code to test ZpmCareOrderZpmPlaatsingsbesluitnummer
        expect(instance).to.be.a(NedapOnsApi.ZpmCareOrderZpmPlaatsingsbesluitnummer);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property beginDate (base name: "beginDate")', function() {
        // TODO: update the code to test the property beginDate
        expect(instance).to.have.property('beginDate');
        // expect(instance.beginDate).to.be(expectedValueLiteral);
      });

      it('should have the property endDate (base name: "endDate")', function() {
        // TODO: update the code to test the property endDate
        expect(instance).to.have.property('endDate');
        // expect(instance.endDate).to.be(expectedValueLiteral);
      });

      it('should have the property careOrderObjectId (base name: "careOrderObjectId")', function() {
        // TODO: update the code to test the property careOrderObjectId
        expect(instance).to.have.property('careOrderObjectId');
        // expect(instance.careOrderObjectId).to.be(expectedValueLiteral);
      });

      it('should have the property plaatsingsbesluitnummer (base name: "plaatsingsbesluitnummer")', function() {
        // TODO: update the code to test the property plaatsingsbesluitnummer
        expect(instance).to.have.property('plaatsingsbesluitnummer');
        // expect(instance.plaatsingsbesluitnummer).to.be(expectedValueLiteral);
      });

      it('should have the property fpt (base name: "fpt")', function() {
        // TODO: update the code to test the property fpt
        expect(instance).to.have.property('fpt');
        // expect(instance.fpt).to.be(expectedValueLiteral);
      });

    });
  });

}));
