/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from "../ApiClient";
import AgendaClientAbsenceOccurrence from '../model/AgendaClientAbsenceOccurrence';
import AgendaListClientAbsenceOccurrenceList from '../model/AgendaListClientAbsenceOccurrenceList';

/**
* AgendaClientAbsenceOccurrence service.
* @module api/AgendaClientAbsenceOccurrenceApi
* @version 0.0.0
*/
export default class AgendaClientAbsenceOccurrenceApi {

    /**
    * Constructs a new AgendaClientAbsenceOccurrenceApi. 
    * @alias module:api/AgendaClientAbsenceOccurrenceApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the agendaClientAbsenceOccurrenceAPIByClientInPeriod operation.
     * @callback moduleapi/AgendaClientAbsenceOccurrenceApi~agendaClientAbsenceOccurrenceAPIByClientInPeriodCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AgendaListClientAbsenceOccurrenceList{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Used for selecting ClientAbsenceOccurrences from a client and moment in time.
     * Used for selecting ClientAbsenceOccurrences from a client and moment in time.
     * @param {Number} clientId The ID of the client to get the ClientAbsenceOccurrences from
     * @param {Object} opts Optional parameters
     * @param {Date} opts.from The start date of the ClientAbsenceOccurrences to retrieve
     * @param {Date} opts.to The end date of the ClientAbsenceOccurrences to retrieve
     * @param {module:api/AgendaClientAbsenceOccurrenceApi~agendaClientAbsenceOccurrenceAPIByClientInPeriodCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    agendaClientAbsenceOccurrenceAPIByClientInPeriod(clientId, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'clientId' is set
      if (clientId === undefined || clientId === null) {
        throw new Error("Missing the required parameter 'clientId' when calling agendaClientAbsenceOccurrenceAPIByClientInPeriod");
      }

      let pathParams = {
        
      };
      let queryParams = {
        'client_id': clientId,'from': opts['from'],'to': opts['to']
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = AgendaListClientAbsenceOccurrenceList;

      return this.apiClient.callApi(
        '/v0/agenda/client_absence_occurrences/by_client_in_period', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the agendaClientAbsenceOccurrenceAPIById operation.
     * @callback moduleapi/AgendaClientAbsenceOccurrenceApi~agendaClientAbsenceOccurrenceAPIByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AgendaClientAbsenceOccurrence{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Used for selecting a ClientAbsenceOccurrence
     * Used for selecting a ClientAbsenceOccurrence
     * @param {String} id used for selecting ClientAbsenceOccurrence
     * @param {module:api/AgendaClientAbsenceOccurrenceApi~agendaClientAbsenceOccurrenceAPIByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    agendaClientAbsenceOccurrenceAPIById(id, callback) {
      
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling agendaClientAbsenceOccurrenceAPIById");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = AgendaClientAbsenceOccurrence;

      return this.apiClient.callApi(
        '/v0/agenda/client_absence_occurrences/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}