/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from "../ApiClient";
import AgendaUnavailability from '../model/AgendaUnavailability';

/**
* AgendaUnavailability service.
* @module api/AgendaUnavailabilityApi
* @version 0.0.0
*/
export default class AgendaUnavailabilityApi {

    /**
    * Constructs a new AgendaUnavailabilityApi. 
    * @alias module:api/AgendaUnavailabilityApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the agendaUnavailabilityAPICreate operation.
     * @callback moduleapi/AgendaUnavailabilityApi~agendaUnavailabilityAPICreateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AgendaUnavailability{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Creates an Agenda Unavailability for the specified employee
     * Used to create new unavailabilities
     * @param {module:model/AgendaUnavailability} body Unavailibality to be created
     * @param {module:api/AgendaUnavailabilityApi~agendaUnavailabilityAPICreateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    agendaUnavailabilityAPICreate(body, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling agendaUnavailabilityAPICreate");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = AgendaUnavailability;

      return this.apiClient.callApi(
        '/v0/agenda/unavailabilities', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}