/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from "../ApiClient";
import DossierDemand from '../model/DossierDemand';
import DossierListDemandList from '../model/DossierListDemandList';

/**
* DossierDemand service.
* @module api/DossierDemandApi
* @version 0.0.0
*/
export default class DossierDemandApi {

    /**
    * Constructs a new DossierDemandApi. 
    * @alias module:api/DossierDemandApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the dossierDemandAPIByDomainId operation.
     * @callback moduleapi/DossierDemandApi~dossierDemandAPIByDomainIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DossierListDemandList{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Return the Demands of a Domain corresponding to the given id.
     * @param {Number} domainId 
     * @param {module:api/DossierDemandApi~dossierDemandAPIByDomainIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    dossierDemandAPIByDomainId(domainId, callback) {
      
      let postBody = null;
      // verify the required parameter 'domainId' is set
      if (domainId === undefined || domainId === null) {
        throw new Error("Missing the required parameter 'domainId' when calling dossierDemandAPIByDomainId");
      }

      let pathParams = {
        'domain_id': domainId
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = DossierListDemandList;

      return this.apiClient.callApi(
        '/v0/administration/dossier/domains/{domain_id}/demands', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the dossierDemandAPIById operation.
     * @callback moduleapi/DossierDemandApi~dossierDemandAPIByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DossierDemand{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get a resource by its ID
     * @param {Number} id used for selecting Demand
     * @param {Object} opts Optional parameters
     * @param {String} opts.xCupidoUserName 
     * @param {String} opts.xCupidoActiveIdentity 
     * @param {module:api/DossierDemandApi~dossierDemandAPIByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    dossierDemandAPIById(id, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling dossierDemandAPIById");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
        
      };
      let headerParams = {
        'X-Cupido-User-Name': opts['xCupidoUserName'],'X-Cupido-Active-Identity': opts['xCupidoActiveIdentity']
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = DossierDemand;

      return this.apiClient.callApi(
        '/v0/administration/dossier/demands/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the dossierDemandAPICreate operation.
     * @callback moduleapi/DossierDemandApi~dossierDemandAPICreateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DossierDemand{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create Demand
     * @param {module:model/DossierDemand} body Demand to create
     * @param {module:api/DossierDemandApi~dossierDemandAPICreateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    dossierDemandAPICreate(body, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling dossierDemandAPICreate");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = DossierDemand;

      return this.apiClient.callApi(
        '/v0/administration/dossier/demands', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the dossierDemandAPIDelete operation.
     * @callback moduleapi/DossierDemandApi~dossierDemandAPIDeleteCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Deletes the Demand with given id
     * @param {Number} id used for selecting Demand
     * @param {Object} opts Optional parameters
     * @param {String} opts.xCupidoUserName 
     * @param {String} opts.xCupidoActiveIdentity 
     * @param {module:api/DossierDemandApi~dossierDemandAPIDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     */
    dossierDemandAPIDelete(id, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling dossierDemandAPIDelete");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
        
      };
      let headerParams = {
        'X-Cupido-User-Name': opts['xCupidoUserName'],'X-Cupido-Active-Identity': opts['xCupidoActiveIdentity']
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/v0/administration/dossier/demands/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the dossierDemandAPIMultiple operation.
     * @callback moduleapi/DossierDemandApi~dossierDemandAPIMultipleCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DossierListDemandList{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Method used for requesting multiple Demand objects using their ids.
     * @param {Object} opts Optional parameters
     * @param {Array.<Number>} opts.id array style id&#x27;s: id&#x3D;1&amp;id&#x3D;2&amp;etc
     * @param {String} opts.xCupidoUserName 
     * @param {String} opts.xCupidoActiveIdentity 
     * @param {module:api/DossierDemandApi~dossierDemandAPIMultipleCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    dossierDemandAPIMultiple(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        'id': this.apiClient.buildCollectionParam(opts['id'], 'multi')
      };
      let headerParams = {
        'X-Cupido-User-Name': opts['xCupidoUserName'],'X-Cupido-Active-Identity': opts['xCupidoActiveIdentity']
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = DossierListDemandList;

      return this.apiClient.callApi(
        '/v0/administration/dossier/demands/multiple', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the dossierDemandAPIUpdate operation.
     * @callback moduleapi/DossierDemandApi~dossierDemandAPIUpdateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DossierDemand{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Updates the given Demand
     * @param {module:model/DossierDemand} body Demand to update
     * @param {Number} id used for selecting Demand
     * @param {Object} opts Optional parameters
     * @param {String} opts.xCupidoUserName 
     * @param {String} opts.xCupidoActiveIdentity 
     * @param {module:api/DossierDemandApi~dossierDemandAPIUpdateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    dossierDemandAPIUpdate(body, id, opts, callback) {
      opts = opts || {};
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling dossierDemandAPIUpdate");
      }
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling dossierDemandAPIUpdate");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
        
      };
      let headerParams = {
        'X-Cupido-User-Name': opts['xCupidoUserName'],'X-Cupido-Active-Identity': opts['xCupidoActiveIdentity']
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = DossierDemand;

      return this.apiClient.callApi(
        '/v0/administration/dossier/demands/{id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}