/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from "../ApiClient";
import DossierListSystemNoteList from '../model/DossierListSystemNoteList';
import DossierSystemNote from '../model/DossierSystemNote';

/**
* DossierSystemNote service.
* @module api/DossierSystemNoteApi
* @version 0.0.0
*/
export default class DossierSystemNoteApi {

    /**
    * Constructs a new DossierSystemNoteApi. 
    * @alias module:api/DossierSystemNoteApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the dossierSystemNoteAPIAll operation.
     * @callback moduleapi/DossierSystemNoteApi~dossierSystemNoteAPIAllCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DossierListSystemNoteList{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns every SystemNote available from the SystemNoteAPI
     * @param {Object} opts Optional parameters
     * @param {Date} opts.updatedSince 
     * @param {String} opts.xCupidoUserName 
     * @param {String} opts.xCupidoActiveIdentity 
     * @param {module:api/DossierSystemNoteApi~dossierSystemNoteAPIAllCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    dossierSystemNoteAPIAll(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        'updatedSince': opts['updatedSince']
      };
      let headerParams = {
        'X-Cupido-User-Name': opts['xCupidoUserName'],'X-Cupido-Active-Identity': opts['xCupidoActiveIdentity']
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = DossierListSystemNoteList;

      return this.apiClient.callApi(
        '/v0/administration/dossier/system_notes', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the dossierSystemNoteAPIById operation.
     * @callback moduleapi/DossierSystemNoteApi~dossierSystemNoteAPIByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DossierSystemNote{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} id used for selecting SystemNote
     * @param {Object} opts Optional parameters
     * @param {Array.<String>} opts.include 
     * @param {String} opts.xCupidoUserName 
     * @param {String} opts.xCupidoActiveIdentity 
     * @param {module:api/DossierSystemNoteApi~dossierSystemNoteAPIByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    dossierSystemNoteAPIById(id, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling dossierSystemNoteAPIById");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
        'include': this.apiClient.buildCollectionParam(opts['include'], 'multi')
      };
      let headerParams = {
        'X-Cupido-User-Name': opts['xCupidoUserName'],'X-Cupido-Active-Identity': opts['xCupidoActiveIdentity']
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = DossierSystemNote;

      return this.apiClient.callApi(
        '/v0/administration/dossier/system_notes/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the dossierSystemNoteAPICreate operation.
     * @callback moduleapi/DossierSystemNoteApi~dossierSystemNoteAPICreateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DossierSystemNote{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create SystemNote
     * @param {module:model/DossierSystemNote} body SystemNote to create
     * @param {Object} opts Optional parameters
     * @param {String} opts.xCupidoUserName 
     * @param {String} opts.xCupidoActiveIdentity 
     * @param {module:api/DossierSystemNoteApi~dossierSystemNoteAPICreateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    dossierSystemNoteAPICreate(body, opts, callback) {
      opts = opts || {};
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling dossierSystemNoteAPICreate");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        'X-Cupido-User-Name': opts['xCupidoUserName'],'X-Cupido-Active-Identity': opts['xCupidoActiveIdentity']
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = DossierSystemNote;

      return this.apiClient.callApi(
        '/v0/administration/dossier/system_notes', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the dossierSystemNoteAPIDelete operation.
     * @callback moduleapi/DossierSystemNoteApi~dossierSystemNoteAPIDeleteCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DossierSystemNote{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Deletes the SystemNote with given id
     * @param {Number} id used for selecting SystemNote
     * @param {Object} opts Optional parameters
     * @param {String} opts.xCupidoUserName 
     * @param {String} opts.xCupidoActiveIdentity 
     * @param {module:api/DossierSystemNoteApi~dossierSystemNoteAPIDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    dossierSystemNoteAPIDelete(id, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling dossierSystemNoteAPIDelete");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
        
      };
      let headerParams = {
        'X-Cupido-User-Name': opts['xCupidoUserName'],'X-Cupido-Active-Identity': opts['xCupidoActiveIdentity']
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = DossierSystemNote;

      return this.apiClient.callApi(
        '/v0/administration/dossier/system_notes/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the dossierSystemNoteAPIUpdate operation.
     * @callback moduleapi/DossierSystemNoteApi~dossierSystemNoteAPIUpdateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DossierSystemNote{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Updates the given SystemNote
     * @param {module:model/DossierSystemNote} body SystemNote to update
     * @param {Number} id used for selecting SystemNote
     * @param {Object} opts Optional parameters
     * @param {String} opts.xCupidoUserName 
     * @param {String} opts.xCupidoActiveIdentity 
     * @param {module:api/DossierSystemNoteApi~dossierSystemNoteAPIUpdateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    dossierSystemNoteAPIUpdate(body, id, opts, callback) {
      opts = opts || {};
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling dossierSystemNoteAPIUpdate");
      }
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling dossierSystemNoteAPIUpdate");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
        
      };
      let headerParams = {
        'X-Cupido-User-Name': opts['xCupidoUserName'],'X-Cupido-Active-Identity': opts['xCupidoActiveIdentity']
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = DossierSystemNote;

      return this.apiClient.callApi(
        '/v0/administration/dossier/system_notes/{id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}