/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from "../ApiClient";
import EmployeePrivacySettings from '../model/EmployeePrivacySettings';

/**
* EmployeePrivacySettings service.
* @module api/EmployeePrivacySettingsApi
* @version 0.0.0
*/
export default class EmployeePrivacySettingsApi {

    /**
    * Constructs a new EmployeePrivacySettingsApi. 
    * @alias module:api/EmployeePrivacySettingsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the employeePrivacySettingsAPIUpdateByEmployeeId operation.
     * @callback moduleapi/EmployeePrivacySettingsApi~employeePrivacySettingsAPIUpdateByEmployeeIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/EmployeePrivacySettings{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update the employee privacy settings corresponding to the given id.
     * @param {module:model/EmployeePrivacySettings} body 
     * @param {Number} employeeId 
     * @param {module:api/EmployeePrivacySettingsApi~employeePrivacySettingsAPIUpdateByEmployeeIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    employeePrivacySettingsAPIUpdateByEmployeeId(body, employeeId, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling employeePrivacySettingsAPIUpdateByEmployeeId");
      }
      // verify the required parameter 'employeeId' is set
      if (employeeId === undefined || employeeId === null) {
        throw new Error("Missing the required parameter 'employeeId' when calling employeePrivacySettingsAPIUpdateByEmployeeId");
      }

      let pathParams = {
        'employee_id': employeeId
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = EmployeePrivacySettings;

      return this.apiClient.callApi(
        '/v0/administration/employees/{employee_id}/privacy_settings', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}