/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from "../ApiClient";
import ExpenseExpenseAddressModel from '../model/ExpenseExpenseAddressModel';
import ExpenseListExpenseAddressModelList from '../model/ExpenseListExpenseAddressModelList';

/**
* ExpenseExpenseAddressModel service.
* @module api/ExpenseExpenseAddressModelApi
* @version 0.0.0
*/
export default class ExpenseExpenseAddressModelApi {

    /**
    * Constructs a new ExpenseExpenseAddressModelApi. 
    * @alias module:api/ExpenseExpenseAddressModelApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the expenseExpenseAddressModelAPICreateOrUpdateExpenseAddress operation.
     * @callback moduleapi/ExpenseExpenseAddressModelApi~expenseExpenseAddressModelAPICreateOrUpdateExpenseAddressCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ExpenseExpenseAddressModel{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update an expense address
     * @param {module:model/ExpenseExpenseAddressModel} body ExpenseAddress to update
     * @param {Number} employeeId 
     * @param {Object} opts Optional parameters
     * @param {String} opts.xCupidoUserName 
     * @param {String} opts.xCupidoActiveIdentity 
     * @param {module:api/ExpenseExpenseAddressModelApi~expenseExpenseAddressModelAPICreateOrUpdateExpenseAddressCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    expenseExpenseAddressModelAPICreateOrUpdateExpenseAddress(body, employeeId, opts, callback) {
      opts = opts || {};
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling expenseExpenseAddressModelAPICreateOrUpdateExpenseAddress");
      }
      // verify the required parameter 'employeeId' is set
      if (employeeId === undefined || employeeId === null) {
        throw new Error("Missing the required parameter 'employeeId' when calling expenseExpenseAddressModelAPICreateOrUpdateExpenseAddress");
      }

      let pathParams = {
        'employee_id': employeeId
      };
      let queryParams = {
        
      };
      let headerParams = {
        'X-Cupido-User-Name': opts['xCupidoUserName'],'X-Cupido-Active-Identity': opts['xCupidoActiveIdentity']
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = ExpenseExpenseAddressModel;

      return this.apiClient.callApi(
        '/v0/administration/authorized/employees/{employee_id}/expense_address', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the expenseExpenseAddressModelAPIGetExpenseAddresses operation.
     * @callback moduleapi/ExpenseExpenseAddressModelApi~expenseExpenseAddressModelAPIGetExpenseAddressesCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ExpenseListExpenseAddressModelList{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns the expense addresses of given employee
     * @param {Number} employeeId 
     * @param {Object} opts Optional parameters
     * @param {String} opts.xCupidoUserName 
     * @param {String} opts.xCupidoActiveIdentity 
     * @param {module:api/ExpenseExpenseAddressModelApi~expenseExpenseAddressModelAPIGetExpenseAddressesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    expenseExpenseAddressModelAPIGetExpenseAddresses(employeeId, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'employeeId' is set
      if (employeeId === undefined || employeeId === null) {
        throw new Error("Missing the required parameter 'employeeId' when calling expenseExpenseAddressModelAPIGetExpenseAddresses");
      }

      let pathParams = {
        'employee_id': employeeId
      };
      let queryParams = {
        
      };
      let headerParams = {
        'X-Cupido-User-Name': opts['xCupidoUserName'],'X-Cupido-Active-Identity': opts['xCupidoActiveIdentity']
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ExpenseListExpenseAddressModelList;

      return this.apiClient.callApi(
        '/v0/administration/authorized/employees/{employee_id}/expense_address', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the expenseExpenseAddressModelAPIRemoveExpenseAddress operation.
     * @callback moduleapi/ExpenseExpenseAddressModelApi~expenseExpenseAddressModelAPIRemoveExpenseAddressCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Removes expense address
     * @param {Number} employeeId 
     * @param {Number} expenseAddressId 
     * @param {Object} opts Optional parameters
     * @param {String} opts.xCupidoUserName 
     * @param {String} opts.xCupidoActiveIdentity 
     * @param {module:api/ExpenseExpenseAddressModelApi~expenseExpenseAddressModelAPIRemoveExpenseAddressCallback} callback The callback function, accepting three arguments: error, data, response
     */
    expenseExpenseAddressModelAPIRemoveExpenseAddress(employeeId, expenseAddressId, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'employeeId' is set
      if (employeeId === undefined || employeeId === null) {
        throw new Error("Missing the required parameter 'employeeId' when calling expenseExpenseAddressModelAPIRemoveExpenseAddress");
      }
      // verify the required parameter 'expenseAddressId' is set
      if (expenseAddressId === undefined || expenseAddressId === null) {
        throw new Error("Missing the required parameter 'expenseAddressId' when calling expenseExpenseAddressModelAPIRemoveExpenseAddress");
      }

      let pathParams = {
        'employee_id': employeeId,'expenseAddress_id': expenseAddressId
      };
      let queryParams = {
        
      };
      let headerParams = {
        'X-Cupido-User-Name': opts['xCupidoUserName'],'X-Cupido-Active-Identity': opts['xCupidoActiveIdentity']
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/v0/administration/authorized/employees/{employee_id}/expense_address/{expenseAddress_id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}