/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from "../ApiClient";
import ListFreeFieldAssignmentList from '../model/ListFreeFieldAssignmentList';

/**
* FreeFieldAssignment service.
* @module api/FreeFieldAssignmentApi
* @version 0.0.0
*/
export default class FreeFieldAssignmentApi {

    /**
    * Constructs a new FreeFieldAssignmentApi. 
    * @alias module:api/FreeFieldAssignmentApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the freeFieldAssignmentAPIStreamAll operation.
     * @callback moduleapi/FreeFieldAssignmentApi~freeFieldAssignmentAPIStreamAllCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ListFreeFieldAssignmentList{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve all entries for free_field_assignments
     * @param {module:api/FreeFieldAssignmentApi~freeFieldAssignmentAPIStreamAllCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    freeFieldAssignmentAPIStreamAll(callback) {
      
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json', 'application/x-ndjson'];
      let returnType = ListFreeFieldAssignmentList;

      return this.apiClient.callApi(
        '/v0/xstream/free_field_assignments/data', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the freeFieldAssignmentAPIStreamUpdates operation.
     * @callback moduleapi/FreeFieldAssignmentApi~freeFieldAssignmentAPIStreamUpdatesCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ListFreeFieldAssignmentList{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve all updates for free_field_assignments since date
     * @param {Date} since 
     * @param {module:api/FreeFieldAssignmentApi~freeFieldAssignmentAPIStreamUpdatesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    freeFieldAssignmentAPIStreamUpdates(since, callback) {
      
      let postBody = null;
      // verify the required parameter 'since' is set
      if (since === undefined || since === null) {
        throw new Error("Missing the required parameter 'since' when calling freeFieldAssignmentAPIStreamUpdates");
      }

      let pathParams = {
        
      };
      let queryParams = {
        'since': since
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json', 'application/x-ndjson'];
      let returnType = ListFreeFieldAssignmentList;

      return this.apiClient.callApi(
        '/v0/xstream/free_field_assignments/updates', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}