/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from "../ApiClient";
import ListLocationAssignmentWaitingListList from '../model/ListLocationAssignmentWaitingListList';
import LocationAssignmentWaitingList from '../model/LocationAssignmentWaitingList';

/**
* LocationAssignmentWaitingList service.
* @module api/LocationAssignmentWaitingListApi
* @version 0.0.0
*/
export default class LocationAssignmentWaitingListApi {

    /**
    * Constructs a new LocationAssignmentWaitingListApi. 
    * @alias module:api/LocationAssignmentWaitingListApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the locationAssignmentWaitingListAPIByClientId operation.
     * @callback moduleapi/LocationAssignmentWaitingListApi~locationAssignmentWaitingListAPIByClientIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ListLocationAssignmentWaitingListList{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Return the waiting list location assignments of a Client corresponding to the given id.
     * @param {Number} clientId id
     * @param {Object} opts Optional parameters
     * @param {Date} opts.validFrom 
     * @param {Date} opts.validTo 
     * @param {module:api/LocationAssignmentWaitingListApi~locationAssignmentWaitingListAPIByClientIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    locationAssignmentWaitingListAPIByClientId(clientId, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'clientId' is set
      if (clientId === undefined || clientId === null) {
        throw new Error("Missing the required parameter 'clientId' when calling locationAssignmentWaitingListAPIByClientId");
      }

      let pathParams = {
        'client_id': clientId
      };
      let queryParams = {
        'valid_from': opts['validFrom'],'valid_to': opts['validTo']
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ListLocationAssignmentWaitingListList;

      return this.apiClient.callApi(
        '/v0/administration/clients/{client_id}/waiting_list_locations', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the locationAssignmentWaitingListAPIById operation.
     * @callback moduleapi/LocationAssignmentWaitingListApi~locationAssignmentWaitingListAPIByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/LocationAssignmentWaitingList{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} id used for selecting LocationAssignmentWaitingList
     * @param {module:api/LocationAssignmentWaitingListApi~locationAssignmentWaitingListAPIByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    locationAssignmentWaitingListAPIById(id, callback) {
      
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling locationAssignmentWaitingListAPIById");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = LocationAssignmentWaitingList;

      return this.apiClient.callApi(
        '/v0/administration/location_assignment_waiting_lists/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the locationAssignmentWaitingListAPICreate operation.
     * @callback moduleapi/LocationAssignmentWaitingListApi~locationAssignmentWaitingListAPICreateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/LocationAssignmentWaitingList{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create LocationAssignmentWaitingList
     * @param {module:model/LocationAssignmentWaitingList} body LocationAssignmentWaitingList to create
     * @param {module:api/LocationAssignmentWaitingListApi~locationAssignmentWaitingListAPICreateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    locationAssignmentWaitingListAPICreate(body, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling locationAssignmentWaitingListAPICreate");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = LocationAssignmentWaitingList;

      return this.apiClient.callApi(
        '/v0/administration/location_assignment_waiting_lists', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the locationAssignmentWaitingListAPIUpdate operation.
     * @callback moduleapi/LocationAssignmentWaitingListApi~locationAssignmentWaitingListAPIUpdateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/LocationAssignmentWaitingList{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Updates the given LocationAssignmentWaitingList
     * @param {module:model/LocationAssignmentWaitingList} body LocationAssignmentWaitingList to update
     * @param {Number} id used for selecting LocationAssignmentWaitingList
     * @param {module:api/LocationAssignmentWaitingListApi~locationAssignmentWaitingListAPIUpdateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    locationAssignmentWaitingListAPIUpdate(body, id, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling locationAssignmentWaitingListAPIUpdate");
      }
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling locationAssignmentWaitingListAPIUpdate");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = LocationAssignmentWaitingList;

      return this.apiClient.callApi(
        '/v0/administration/location_assignment_waiting_lists/{id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}