/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from "../ApiClient";
import MovesListShiftList from '../model/MovesListShiftList';
import MovesShift from '../model/MovesShift';

/**
* MovesShift service.
* @module api/MovesShiftApi
* @version 0.0.0
*/
export default class MovesShiftApi {

    /**
    * Constructs a new MovesShiftApi. 
    * @alias module:api/MovesShiftApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the movesShiftAPIById operation.
     * @callback moduleapi/MovesShiftApi~movesShiftAPIByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/MovesShift{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get a shift by its ID
     * @param {String} id used for selecting Shift
     * @param {module:api/MovesShiftApi~movesShiftAPIByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    movesShiftAPIById(id, callback) {
      
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling movesShiftAPIById");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = MovesShift;

      return this.apiClient.callApi(
        '/v0/plannen_roosteren/shifts/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the movesShiftAPIStreamAll operation.
     * @callback moduleapi/MovesShiftApi~movesShiftAPIStreamAllCallback
     * @param {String} error Error message, if any.
     * @param {module:model/MovesListShiftList{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Return all Shift models in a streaming manner
     * @param {module:api/MovesShiftApi~movesShiftAPIStreamAllCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    movesShiftAPIStreamAll(callback) {
      
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json', 'application/x-ndjson'];
      let returnType = MovesListShiftList;

      return this.apiClient.callApi(
        '/v0/xstream/shifts/data', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the movesShiftAPIStreamDeletes operation.
     * @callback moduleapi/MovesShiftApi~movesShiftAPIStreamDeletesCallback
     * @param {String} error Error message, if any.
     * @param {module:model/MovesListShiftList{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Return all Shift models which where deleted since the date given in the request.
     * If no date is given it will return all deleted Shift models
     * @param {Date} since 
     * @param {module:api/MovesShiftApi~movesShiftAPIStreamDeletesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    movesShiftAPIStreamDeletes(since, callback) {
      
      let postBody = null;
      // verify the required parameter 'since' is set
      if (since === undefined || since === null) {
        throw new Error("Missing the required parameter 'since' when calling movesShiftAPIStreamDeletes");
      }

      let pathParams = {
        
      };
      let queryParams = {
        'since': since
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json', 'application/x-ndjson'];
      let returnType = MovesListShiftList;

      return this.apiClient.callApi(
        '/v0/xstream/shifts/deletes', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the movesShiftAPIStreamUpdates operation.
     * @callback moduleapi/MovesShiftApi~movesShiftAPIStreamUpdatesCallback
     * @param {String} error Error message, if any.
     * @param {module:model/MovesListShiftList{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Return all Shift models which where updated since the date given in the request.
     * @param {Date} since 
     * @param {module:api/MovesShiftApi~movesShiftAPIStreamUpdatesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    movesShiftAPIStreamUpdates(since, callback) {
      
      let postBody = null;
      // verify the required parameter 'since' is set
      if (since === undefined || since === null) {
        throw new Error("Missing the required parameter 'since' when calling movesShiftAPIStreamUpdates");
      }

      let pathParams = {
        
      };
      let queryParams = {
        'since': since
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json', 'application/x-ndjson'];
      let returnType = MovesListShiftList;

      return this.apiClient.callApi(
        '/v0/xstream/shifts/updates', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}