/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from "../ApiClient";
import OpenehrCompositionIdList from '../model/OpenehrCompositionIdList';
import OpenehrListCarePlanVvtCareProfileLinkList from '../model/OpenehrListCarePlanVvtCareProfileLinkList';

/**
* OpenehrCarePlanVvtCareProfileLink service.
* @module api/OpenehrCarePlanVvtCareProfileLinkApi
* @version 0.0.0
*/
export default class OpenehrCarePlanVvtCareProfileLinkApi {

    /**
    * Constructs a new OpenehrCarePlanVvtCareProfileLinkApi. 
    * @alias module:api/OpenehrCarePlanVvtCareProfileLinkApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the openehrCarePlanVvtCareProfileLinkAPILinkIds operation.
     * @callback moduleapi/OpenehrCarePlanVvtCareProfileLinkApi~openehrCarePlanVvtCareProfileLinkAPILinkIdsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/OpenehrListCarePlanVvtCareProfileLinkList{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns care plan IDs for given VVT care profile composition IDs
     * @param {module:model/OpenehrCompositionIdList} body 
     * @param {module:api/OpenehrCarePlanVvtCareProfileLinkApi~openehrCarePlanVvtCareProfileLinkAPILinkIdsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    openehrCarePlanVvtCareProfileLinkAPILinkIds(body, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling openehrCarePlanVvtCareProfileLinkAPILinkIds");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = OpenehrListCarePlanVvtCareProfileLinkList;

      return this.apiClient.callApi(
        '/v0/openehr_dossier/back_channel/unauthorized/vvt_care_profiles/care_plan_links', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}