/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from "../ApiClient";
import PayrollCollectiveAgreementAssignment from '../model/PayrollCollectiveAgreementAssignment';
import PayrollListCollectiveAgreementAssignmentList from '../model/PayrollListCollectiveAgreementAssignmentList';

/**
* PayrollCollectiveAgreementAssignment service.
* @module api/PayrollCollectiveAgreementAssignmentApi
* @version 0.0.0
*/
export default class PayrollCollectiveAgreementAssignmentApi {

    /**
    * Constructs a new PayrollCollectiveAgreementAssignmentApi. 
    * @alias module:api/PayrollCollectiveAgreementAssignmentApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the payrollCollectiveAgreementAssignmentAPIByEmployeeId operation.
     * @callback moduleapi/PayrollCollectiveAgreementAssignmentApi~payrollCollectiveAgreementAssignmentAPIByEmployeeIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PayrollListCollectiveAgreementAssignmentList{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Return the collective agreement assignments of an Employee corresponding to the given id.
     * @param {Number} employeeId id
     * @param {module:api/PayrollCollectiveAgreementAssignmentApi~payrollCollectiveAgreementAssignmentAPIByEmployeeIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    payrollCollectiveAgreementAssignmentAPIByEmployeeId(employeeId, callback) {
      
      let postBody = null;
      // verify the required parameter 'employeeId' is set
      if (employeeId === undefined || employeeId === null) {
        throw new Error("Missing the required parameter 'employeeId' when calling payrollCollectiveAgreementAssignmentAPIByEmployeeId");
      }

      let pathParams = {
        'employee_id': employeeId
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = PayrollListCollectiveAgreementAssignmentList;

      return this.apiClient.callApi(
        '/v0/administration/collective_agreement_assignments/by_employee_id/{employee_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the payrollCollectiveAgreementAssignmentAPIById operation.
     * @callback moduleapi/PayrollCollectiveAgreementAssignmentApi~payrollCollectiveAgreementAssignmentAPIByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PayrollCollectiveAgreementAssignment{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns the collective agreement assignment corresponding to the given id
     * @param {Number} id used for selecting Collective Agreement Assignment
     * @param {module:api/PayrollCollectiveAgreementAssignmentApi~payrollCollectiveAgreementAssignmentAPIByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    payrollCollectiveAgreementAssignmentAPIById(id, callback) {
      
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling payrollCollectiveAgreementAssignmentAPIById");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = PayrollCollectiveAgreementAssignment;

      return this.apiClient.callApi(
        '/v0/administration/collective_agreement_assignments/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the payrollCollectiveAgreementAssignmentAPICreate operation.
     * @callback moduleapi/PayrollCollectiveAgreementAssignmentApi~payrollCollectiveAgreementAssignmentAPICreateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PayrollCollectiveAgreementAssignment{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create the provided collective agreement assignment and assign it to the employee corresponding to the provided id
     * @param {module:model/PayrollCollectiveAgreementAssignment} body 
     * @param {module:api/PayrollCollectiveAgreementAssignmentApi~payrollCollectiveAgreementAssignmentAPICreateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    payrollCollectiveAgreementAssignmentAPICreate(body, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling payrollCollectiveAgreementAssignmentAPICreate");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = PayrollCollectiveAgreementAssignment;

      return this.apiClient.callApi(
        '/v0/administration/collective_agreement_assignments', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the payrollCollectiveAgreementAssignmentAPIRemoveByEmployeeId operation.
     * @callback moduleapi/PayrollCollectiveAgreementAssignmentApi~payrollCollectiveAgreementAssignmentAPIRemoveByEmployeeIdCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Remove all collective agreement assignments for the employee corresponding to the given id
     * @param {Number} employeeId 
     * @param {module:api/PayrollCollectiveAgreementAssignmentApi~payrollCollectiveAgreementAssignmentAPIRemoveByEmployeeIdCallback} callback The callback function, accepting three arguments: error, data, response
     */
    payrollCollectiveAgreementAssignmentAPIRemoveByEmployeeId(employeeId, callback) {
      
      let postBody = null;
      // verify the required parameter 'employeeId' is set
      if (employeeId === undefined || employeeId === null) {
        throw new Error("Missing the required parameter 'employeeId' when calling payrollCollectiveAgreementAssignmentAPIRemoveByEmployeeId");
      }

      let pathParams = {
        'employee_id': employeeId
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/v0/administration/collective_agreement_assignments/by_employee_id/{employee_id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the payrollCollectiveAgreementAssignmentAPIRemoveById operation.
     * @callback moduleapi/PayrollCollectiveAgreementAssignmentApi~payrollCollectiveAgreementAssignmentAPIRemoveByIdCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Remove the collective agreement assignment corresponding to the given id
     * @param {Number} id 
     * @param {module:api/PayrollCollectiveAgreementAssignmentApi~payrollCollectiveAgreementAssignmentAPIRemoveByIdCallback} callback The callback function, accepting three arguments: error, data, response
     */
    payrollCollectiveAgreementAssignmentAPIRemoveById(id, callback) {
      
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling payrollCollectiveAgreementAssignmentAPIRemoveById");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/v0/administration/collective_agreement_assignments/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the payrollCollectiveAgreementAssignmentAPIUpdateById operation.
     * @callback moduleapi/PayrollCollectiveAgreementAssignmentApi~payrollCollectiveAgreementAssignmentAPIUpdateByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PayrollCollectiveAgreementAssignment{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update the provided collective agreement assignment
     * @param {module:model/PayrollCollectiveAgreementAssignment} body 
     * @param {Number} id 
     * @param {module:api/PayrollCollectiveAgreementAssignmentApi~payrollCollectiveAgreementAssignmentAPIUpdateByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    payrollCollectiveAgreementAssignmentAPIUpdateById(body, id, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling payrollCollectiveAgreementAssignmentAPIUpdateById");
      }
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling payrollCollectiveAgreementAssignmentAPIUpdateById");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = PayrollCollectiveAgreementAssignment;

      return this.apiClient.callApi(
        '/v0/administration/collective_agreement_assignments/{id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}