/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from "../ApiClient";
import PortalEmployeePortalProfile from '../model/PortalEmployeePortalProfile';

/**
* PortalEmployeePortalProfile service.
* @module api/PortalEmployeePortalProfileApi
* @version 0.0.0
*/
export default class PortalEmployeePortalProfileApi {

    /**
    * Constructs a new PortalEmployeePortalProfileApi. 
    * @alias module:api/PortalEmployeePortalProfileApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the portalEmployeePortalProfileAPIByEmployeeId operation.
     * @callback moduleapi/PortalEmployeePortalProfileApi~portalEmployeePortalProfileAPIByEmployeeIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PortalEmployeePortalProfile{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Return the employee portal profile of a employee corresponding to the given employee id.
     * @param {Number} employeeId id
     * @param {module:api/PortalEmployeePortalProfileApi~portalEmployeePortalProfileAPIByEmployeeIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    portalEmployeePortalProfileAPIByEmployeeId(employeeId, callback) {
      
      let postBody = null;
      // verify the required parameter 'employeeId' is set
      if (employeeId === undefined || employeeId === null) {
        throw new Error("Missing the required parameter 'employeeId' when calling portalEmployeePortalProfileAPIByEmployeeId");
      }

      let pathParams = {
        'employee_id': employeeId
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = PortalEmployeePortalProfile;

      return this.apiClient.callApi(
        '/v0/medewerkerportaal/employees/{employee_id}/employee_portal_profile', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}