/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from "../ApiClient";
import ListPractitionerBigCodeList from '../model/ListPractitionerBigCodeList';
import PractitionerBigCode from '../model/PractitionerBigCode';

/**
* PractitionerBigCode service.
* @module api/PractitionerBigCodeApi
* @version 0.0.0
*/
export default class PractitionerBigCodeApi {

    /**
    * Constructs a new PractitionerBigCodeApi. 
    * @alias module:api/PractitionerBigCodeApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the practitionerBigCodeAPIByEmployeeId operation.
     * @callback moduleapi/PractitionerBigCodeApi~practitionerBigCodeAPIByEmployeeIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ListPractitionerBigCodeList{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Return the BIG codes assigned to the employee corresponding to the provided id
     * @param {Number} employeeId 
     * @param {module:api/PractitionerBigCodeApi~practitionerBigCodeAPIByEmployeeIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    practitionerBigCodeAPIByEmployeeId(employeeId, callback) {
      
      let postBody = null;
      // verify the required parameter 'employeeId' is set
      if (employeeId === undefined || employeeId === null) {
        throw new Error("Missing the required parameter 'employeeId' when calling practitionerBigCodeAPIByEmployeeId");
      }

      let pathParams = {
        'employee_id': employeeId
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ListPractitionerBigCodeList;

      return this.apiClient.callApi(
        '/v0/administration/employees/{employee_id}/big_codes', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the practitionerBigCodeAPIByEmployeeIdAndBigId operation.
     * @callback moduleapi/PractitionerBigCodeApi~practitionerBigCodeAPIByEmployeeIdAndBigIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PractitionerBigCode{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Return the BIG code with the provided id assigned to the employee corresponding to the provided id
     * @param {Number} employeeId 
     * @param {Number} bigCodeId 
     * @param {module:api/PractitionerBigCodeApi~practitionerBigCodeAPIByEmployeeIdAndBigIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    practitionerBigCodeAPIByEmployeeIdAndBigId(employeeId, bigCodeId, callback) {
      
      let postBody = null;
      // verify the required parameter 'employeeId' is set
      if (employeeId === undefined || employeeId === null) {
        throw new Error("Missing the required parameter 'employeeId' when calling practitionerBigCodeAPIByEmployeeIdAndBigId");
      }
      // verify the required parameter 'bigCodeId' is set
      if (bigCodeId === undefined || bigCodeId === null) {
        throw new Error("Missing the required parameter 'bigCodeId' when calling practitionerBigCodeAPIByEmployeeIdAndBigId");
      }

      let pathParams = {
        'employee_id': employeeId,'big_code_id': bigCodeId
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = PractitionerBigCode;

      return this.apiClient.callApi(
        '/v0/administration/employees/{employee_id}/big_codes/{big_code_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the practitionerBigCodeAPICreateForEmployeeId operation.
     * @callback moduleapi/PractitionerBigCodeApi~practitionerBigCodeAPICreateForEmployeeIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PractitionerBigCode{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Creates the provided BIG code and assigns it to the employee corresponding to the provided id
     * @param {module:model/PractitionerBigCode} body 
     * @param {Number} employeeId 
     * @param {module:api/PractitionerBigCodeApi~practitionerBigCodeAPICreateForEmployeeIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    practitionerBigCodeAPICreateForEmployeeId(body, employeeId, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling practitionerBigCodeAPICreateForEmployeeId");
      }
      // verify the required parameter 'employeeId' is set
      if (employeeId === undefined || employeeId === null) {
        throw new Error("Missing the required parameter 'employeeId' when calling practitionerBigCodeAPICreateForEmployeeId");
      }

      let pathParams = {
        'employee_id': employeeId
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = PractitionerBigCode;

      return this.apiClient.callApi(
        '/v0/administration/employees/{employee_id}/big_codes', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the practitionerBigCodeAPIDeleteForEmployeeId operation.
     * @callback moduleapi/PractitionerBigCodeApi~practitionerBigCodeAPIDeleteForEmployeeIdCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Deletes the BIG code with the provided id assigned to the employee corresponding to the provided id
     * @param {Number} employeeId 
     * @param {Number} bigCodeId 
     * @param {module:api/PractitionerBigCodeApi~practitionerBigCodeAPIDeleteForEmployeeIdCallback} callback The callback function, accepting three arguments: error, data, response
     */
    practitionerBigCodeAPIDeleteForEmployeeId(employeeId, bigCodeId, callback) {
      
      let postBody = null;
      // verify the required parameter 'employeeId' is set
      if (employeeId === undefined || employeeId === null) {
        throw new Error("Missing the required parameter 'employeeId' when calling practitionerBigCodeAPIDeleteForEmployeeId");
      }
      // verify the required parameter 'bigCodeId' is set
      if (bigCodeId === undefined || bigCodeId === null) {
        throw new Error("Missing the required parameter 'bigCodeId' when calling practitionerBigCodeAPIDeleteForEmployeeId");
      }

      let pathParams = {
        'employee_id': employeeId,'big_code_id': bigCodeId
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/v0/administration/employees/{employee_id}/big_codes/{big_code_id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the practitionerBigCodeAPIUpdateForEmployeeId operation.
     * @callback moduleapi/PractitionerBigCodeApi~practitionerBigCodeAPIUpdateForEmployeeIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PractitionerBigCode{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Updates the provided BIG code assigned to the employee corresponding to the provided id
     * @param {module:model/PractitionerBigCode} body 
     * @param {Number} employeeId 
     * @param {Number} bigCodeId 
     * @param {module:api/PractitionerBigCodeApi~practitionerBigCodeAPIUpdateForEmployeeIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    practitionerBigCodeAPIUpdateForEmployeeId(body, employeeId, bigCodeId, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling practitionerBigCodeAPIUpdateForEmployeeId");
      }
      // verify the required parameter 'employeeId' is set
      if (employeeId === undefined || employeeId === null) {
        throw new Error("Missing the required parameter 'employeeId' when calling practitionerBigCodeAPIUpdateForEmployeeId");
      }
      // verify the required parameter 'bigCodeId' is set
      if (bigCodeId === undefined || bigCodeId === null) {
        throw new Error("Missing the required parameter 'bigCodeId' when calling practitionerBigCodeAPIUpdateForEmployeeId");
      }

      let pathParams = {
        'employee_id': employeeId,'big_code_id': bigCodeId
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = PractitionerBigCode;

      return this.apiClient.callApi(
        '/v0/administration/employees/{employee_id}/big_codes/{big_code_id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}