/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from "../ApiClient";
import SurveyAnswerDefinitionGroup from '../model/SurveyAnswerDefinitionGroup';
import SurveyListAnswerDefinitionGroupList from '../model/SurveyListAnswerDefinitionGroupList';

/**
* SurveyAnswerDefinitionGroup service.
* @module api/SurveyAnswerDefinitionGroupApi
* @version 0.0.0
*/
export default class SurveyAnswerDefinitionGroupApi {

    /**
    * Constructs a new SurveyAnswerDefinitionGroupApi. 
    * @alias module:api/SurveyAnswerDefinitionGroupApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the surveyAnswerDefinitionGroupAPIAll operation.
     * @callback moduleapi/SurveyAnswerDefinitionGroupApi~surveyAnswerDefinitionGroupAPIAllCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SurveyListAnswerDefinitionGroupList{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns every AnswerDefinitionGroup available from the AnswerDefinitionGroupAPI
     * @param {Object} opts Optional parameters
     * @param {String} opts.xCupidoUserName 
     * @param {String} opts.xCupidoActiveIdentity 
     * @param {module:api/SurveyAnswerDefinitionGroupApi~surveyAnswerDefinitionGroupAPIAllCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    surveyAnswerDefinitionGroupAPIAll(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        'X-Cupido-User-Name': opts['xCupidoUserName'],'X-Cupido-Active-Identity': opts['xCupidoActiveIdentity']
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = SurveyListAnswerDefinitionGroupList;

      return this.apiClient.callApi(
        '/v0/administration/survey/answer_definition_groups', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the surveyAnswerDefinitionGroupAPIById operation.
     * @callback moduleapi/SurveyAnswerDefinitionGroupApi~surveyAnswerDefinitionGroupAPIByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SurveyAnswerDefinitionGroup{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} id used for selecting AnswerDefinitionGroup
     * @param {Object} opts Optional parameters
     * @param {Array.<String>} opts.include 
     * @param {String} opts.xCupidoUserName 
     * @param {String} opts.xCupidoActiveIdentity 
     * @param {module:api/SurveyAnswerDefinitionGroupApi~surveyAnswerDefinitionGroupAPIByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    surveyAnswerDefinitionGroupAPIById(id, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling surveyAnswerDefinitionGroupAPIById");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
        'include': this.apiClient.buildCollectionParam(opts['include'], 'multi')
      };
      let headerParams = {
        'X-Cupido-User-Name': opts['xCupidoUserName'],'X-Cupido-Active-Identity': opts['xCupidoActiveIdentity']
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = SurveyAnswerDefinitionGroup;

      return this.apiClient.callApi(
        '/v0/administration/survey/answer_definition_groups/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the surveyAnswerDefinitionGroupAPICreate operation.
     * @callback moduleapi/SurveyAnswerDefinitionGroupApi~surveyAnswerDefinitionGroupAPICreateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SurveyAnswerDefinitionGroup{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create AnswerDefinitionGroup
     * @param {module:model/SurveyAnswerDefinitionGroup} body AnswerDefinitionGroup to create
     * @param {Object} opts Optional parameters
     * @param {String} opts.xCupidoUserName 
     * @param {String} opts.xCupidoActiveIdentity 
     * @param {module:api/SurveyAnswerDefinitionGroupApi~surveyAnswerDefinitionGroupAPICreateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    surveyAnswerDefinitionGroupAPICreate(body, opts, callback) {
      opts = opts || {};
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling surveyAnswerDefinitionGroupAPICreate");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        'X-Cupido-User-Name': opts['xCupidoUserName'],'X-Cupido-Active-Identity': opts['xCupidoActiveIdentity']
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = SurveyAnswerDefinitionGroup;

      return this.apiClient.callApi(
        '/v0/administration/survey/answer_definition_groups', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the surveyAnswerDefinitionGroupAPIUpdate operation.
     * @callback moduleapi/SurveyAnswerDefinitionGroupApi~surveyAnswerDefinitionGroupAPIUpdateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SurveyAnswerDefinitionGroup{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Updates the given AnswerDefinitionGroup
     * @param {module:model/SurveyAnswerDefinitionGroup} body AnswerDefinitionGroup to update
     * @param {Number} id used for selecting AnswerDefinitionGroup
     * @param {Object} opts Optional parameters
     * @param {String} opts.xCupidoUserName 
     * @param {String} opts.xCupidoActiveIdentity 
     * @param {module:api/SurveyAnswerDefinitionGroupApi~surveyAnswerDefinitionGroupAPIUpdateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    surveyAnswerDefinitionGroupAPIUpdate(body, id, opts, callback) {
      opts = opts || {};
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling surveyAnswerDefinitionGroupAPIUpdate");
      }
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling surveyAnswerDefinitionGroupAPIUpdate");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
        
      };
      let headerParams = {
        'X-Cupido-User-Name': opts['xCupidoUserName'],'X-Cupido-Active-Identity': opts['xCupidoActiveIdentity']
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = SurveyAnswerDefinitionGroup;

      return this.apiClient.callApi(
        '/v0/administration/survey/answer_definition_groups/{id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}