/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from "../ApiClient";
import TasqueCareTaskOccurrence from '../model/TasqueCareTaskOccurrence';
import TasqueListCareTaskOccurrenceList from '../model/TasqueListCareTaskOccurrenceList';
import TasqueListClientIdBySubTypeList from '../model/TasqueListClientIdBySubTypeList';

/**
* TasqueCareTaskOccurrence service.
* @module api/TasqueCareTaskOccurrenceApi
* @version 0.0.0
*/
export default class TasqueCareTaskOccurrenceApi {

    /**
    * Constructs a new TasqueCareTaskOccurrenceApi. 
    * @alias module:api/TasqueCareTaskOccurrenceApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the tasqueCareTaskOccurrenceAPIByClientAndSubType operation.
     * @callback moduleapi/TasqueCareTaskOccurrenceApi~tasqueCareTaskOccurrenceAPIByClientAndSubTypeCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TasqueListCareTaskOccurrenceList{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns the care task occurrences for a client and the given sub-type and sub-type query.
     * @param {Number} clientId 
     * @param {String} subTypeQuery regex for sub_type
     * @param {Object} opts Optional parameters
     * @param {String} opts.subTypeId 
     * @param {module:api/TasqueCareTaskOccurrenceApi~tasqueCareTaskOccurrenceAPIByClientAndSubTypeCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    tasqueCareTaskOccurrenceAPIByClientAndSubType(clientId, subTypeQuery, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'clientId' is set
      if (clientId === undefined || clientId === null) {
        throw new Error("Missing the required parameter 'clientId' when calling tasqueCareTaskOccurrenceAPIByClientAndSubType");
      }
      // verify the required parameter 'subTypeQuery' is set
      if (subTypeQuery === undefined || subTypeQuery === null) {
        throw new Error("Missing the required parameter 'subTypeQuery' when calling tasqueCareTaskOccurrenceAPIByClientAndSubType");
      }

      let pathParams = {
        'client_id': clientId
      };
      let queryParams = {
        'sub_type_query': subTypeQuery,'sub_type_id': opts['subTypeId']
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = TasqueListCareTaskOccurrenceList;

      return this.apiClient.callApi(
        '/v0/taken/clients/{client_id}/care_task_occurrences/by_sub_type', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the tasqueCareTaskOccurrenceAPIByClientId operation.
     * @callback moduleapi/TasqueCareTaskOccurrenceApi~tasqueCareTaskOccurrenceAPIByClientIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TasqueListCareTaskOccurrenceList{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns the care task occurrences of a Client corresponding to the given id.
     * @param {Number} clientId id
     * @param {Date} from 
     * @param {Date} to 
     * @param {Boolean} includeFinished 
     * @param {module:api/TasqueCareTaskOccurrenceApi~tasqueCareTaskOccurrenceAPIByClientIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    tasqueCareTaskOccurrenceAPIByClientId(clientId, from, to, includeFinished, callback) {
      
      let postBody = null;
      // verify the required parameter 'clientId' is set
      if (clientId === undefined || clientId === null) {
        throw new Error("Missing the required parameter 'clientId' when calling tasqueCareTaskOccurrenceAPIByClientId");
      }
      // verify the required parameter 'from' is set
      if (from === undefined || from === null) {
        throw new Error("Missing the required parameter 'from' when calling tasqueCareTaskOccurrenceAPIByClientId");
      }
      // verify the required parameter 'to' is set
      if (to === undefined || to === null) {
        throw new Error("Missing the required parameter 'to' when calling tasqueCareTaskOccurrenceAPIByClientId");
      }
      // verify the required parameter 'includeFinished' is set
      if (includeFinished === undefined || includeFinished === null) {
        throw new Error("Missing the required parameter 'includeFinished' when calling tasqueCareTaskOccurrenceAPIByClientId");
      }

      let pathParams = {
        'client_id': clientId
      };
      let queryParams = {
        'from': from,'to': to,'include_finished': includeFinished
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = TasqueListCareTaskOccurrenceList;

      return this.apiClient.callApi(
        '/v0/taken/clients/{client_id}/care_task_occurrences', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the tasqueCareTaskOccurrenceAPIByEmployeeAndSubType operation.
     * @callback moduleapi/TasqueCareTaskOccurrenceApi~tasqueCareTaskOccurrenceAPIByEmployeeAndSubTypeCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TasqueListCareTaskOccurrenceList{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns the care task occurrences for a employee and the given sub-type and sub-type query.
     * @param {Number} employeeId 
     * @param {String} subTypeQuery regex for sub_type
     * @param {Object} opts Optional parameters
     * @param {String} opts.subTypeId 
     * @param {module:api/TasqueCareTaskOccurrenceApi~tasqueCareTaskOccurrenceAPIByEmployeeAndSubTypeCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    tasqueCareTaskOccurrenceAPIByEmployeeAndSubType(employeeId, subTypeQuery, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'employeeId' is set
      if (employeeId === undefined || employeeId === null) {
        throw new Error("Missing the required parameter 'employeeId' when calling tasqueCareTaskOccurrenceAPIByEmployeeAndSubType");
      }
      // verify the required parameter 'subTypeQuery' is set
      if (subTypeQuery === undefined || subTypeQuery === null) {
        throw new Error("Missing the required parameter 'subTypeQuery' when calling tasqueCareTaskOccurrenceAPIByEmployeeAndSubType");
      }

      let pathParams = {
        'employee_id': employeeId
      };
      let queryParams = {
        'sub_type_query': subTypeQuery,'sub_type_id': opts['subTypeId']
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = TasqueListCareTaskOccurrenceList;

      return this.apiClient.callApi(
        '/v0/taken/employees/{employee_id}/care_task_occurrences/by_sub_type', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the tasqueCareTaskOccurrenceAPIById operation.
     * @callback moduleapi/TasqueCareTaskOccurrenceApi~tasqueCareTaskOccurrenceAPIByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TasqueCareTaskOccurrence{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} id used for selecting CareTaskOccurrence
     * @param {module:api/TasqueCareTaskOccurrenceApi~tasqueCareTaskOccurrenceAPIByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    tasqueCareTaskOccurrenceAPIById(id, callback) {
      
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling tasqueCareTaskOccurrenceAPIById");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = TasqueCareTaskOccurrence;

      return this.apiClient.callApi(
        '/v0/taken/care_task_occurrences/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the tasqueCareTaskOccurrenceAPIByLocationAndSubType operation.
     * @callback moduleapi/TasqueCareTaskOccurrenceApi~tasqueCareTaskOccurrenceAPIByLocationAndSubTypeCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TasqueListCareTaskOccurrenceList{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns the care task occurrences for a location and the given sub-type and sub-type query.
     * @param {Number} locationId 
     * @param {String} subTypeQuery regex for sub_type
     * @param {Object} opts Optional parameters
     * @param {String} opts.subTypeId 
     * @param {module:api/TasqueCareTaskOccurrenceApi~tasqueCareTaskOccurrenceAPIByLocationAndSubTypeCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    tasqueCareTaskOccurrenceAPIByLocationAndSubType(locationId, subTypeQuery, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'locationId' is set
      if (locationId === undefined || locationId === null) {
        throw new Error("Missing the required parameter 'locationId' when calling tasqueCareTaskOccurrenceAPIByLocationAndSubType");
      }
      // verify the required parameter 'subTypeQuery' is set
      if (subTypeQuery === undefined || subTypeQuery === null) {
        throw new Error("Missing the required parameter 'subTypeQuery' when calling tasqueCareTaskOccurrenceAPIByLocationAndSubType");
      }

      let pathParams = {
        'location_id': locationId
      };
      let queryParams = {
        'sub_type_query': subTypeQuery,'sub_type_id': opts['subTypeId']
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = TasqueListCareTaskOccurrenceList;

      return this.apiClient.callApi(
        '/v0/taken/locations/{location_id}/care_task_occurrences/by_sub_type', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the tasqueCareTaskOccurrenceAPIByLocationId operation.
     * @callback moduleapi/TasqueCareTaskOccurrenceApi~tasqueCareTaskOccurrenceAPIByLocationIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TasqueListCareTaskOccurrenceList{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns the care task occurrences of a Location corresponding to the given id.
     * @param {Number} locationId id
     * @param {Date} from 
     * @param {Date} to 
     * @param {Boolean} includeFinished 
     * @param {module:api/TasqueCareTaskOccurrenceApi~tasqueCareTaskOccurrenceAPIByLocationIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    tasqueCareTaskOccurrenceAPIByLocationId(locationId, from, to, includeFinished, callback) {
      
      let postBody = null;
      // verify the required parameter 'locationId' is set
      if (locationId === undefined || locationId === null) {
        throw new Error("Missing the required parameter 'locationId' when calling tasqueCareTaskOccurrenceAPIByLocationId");
      }
      // verify the required parameter 'from' is set
      if (from === undefined || from === null) {
        throw new Error("Missing the required parameter 'from' when calling tasqueCareTaskOccurrenceAPIByLocationId");
      }
      // verify the required parameter 'to' is set
      if (to === undefined || to === null) {
        throw new Error("Missing the required parameter 'to' when calling tasqueCareTaskOccurrenceAPIByLocationId");
      }
      // verify the required parameter 'includeFinished' is set
      if (includeFinished === undefined || includeFinished === null) {
        throw new Error("Missing the required parameter 'includeFinished' when calling tasqueCareTaskOccurrenceAPIByLocationId");
      }

      let pathParams = {
        'location_id': locationId
      };
      let queryParams = {
        'from': from,'to': to,'include_finished': includeFinished
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = TasqueListCareTaskOccurrenceList;

      return this.apiClient.callApi(
        '/v0/taken/locations/{location_id}/care_task_occurrences', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the tasqueCareTaskOccurrenceAPIBySubType operation.
     * @callback moduleapi/TasqueCareTaskOccurrenceApi~tasqueCareTaskOccurrenceAPIBySubTypeCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TasqueListCareTaskOccurrenceList{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns the care task occurrences for the given sub-type and sub-type query.
     * @param {String} subTypeQuery regex for sub_type
     * @param {String} subTypeId sub_type_id of task
     * @param {module:api/TasqueCareTaskOccurrenceApi~tasqueCareTaskOccurrenceAPIBySubTypeCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    tasqueCareTaskOccurrenceAPIBySubType(subTypeQuery, subTypeId, callback) {
      
      let postBody = null;
      // verify the required parameter 'subTypeQuery' is set
      if (subTypeQuery === undefined || subTypeQuery === null) {
        throw new Error("Missing the required parameter 'subTypeQuery' when calling tasqueCareTaskOccurrenceAPIBySubType");
      }
      // verify the required parameter 'subTypeId' is set
      if (subTypeId === undefined || subTypeId === null) {
        throw new Error("Missing the required parameter 'subTypeId' when calling tasqueCareTaskOccurrenceAPIBySubType");
      }

      let pathParams = {
        'sub_type_id': subTypeId
      };
      let queryParams = {
        'sub_type_query': subTypeQuery
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = TasqueListCareTaskOccurrenceList;

      return this.apiClient.callApi(
        '/v0/taken/care_task_occurrences/by_sub_type_id/{sub_type_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the tasqueCareTaskOccurrenceAPIByTeamAndSubType operation.
     * @callback moduleapi/TasqueCareTaskOccurrenceApi~tasqueCareTaskOccurrenceAPIByTeamAndSubTypeCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TasqueListCareTaskOccurrenceList{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns the care task occurrences for a team and the given sub-type and sub-type query.
     * @param {Number} teamId 
     * @param {String} subTypeQuery regex for sub_type
     * @param {Object} opts Optional parameters
     * @param {String} opts.subTypeId 
     * @param {module:api/TasqueCareTaskOccurrenceApi~tasqueCareTaskOccurrenceAPIByTeamAndSubTypeCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    tasqueCareTaskOccurrenceAPIByTeamAndSubType(teamId, subTypeQuery, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'teamId' is set
      if (teamId === undefined || teamId === null) {
        throw new Error("Missing the required parameter 'teamId' when calling tasqueCareTaskOccurrenceAPIByTeamAndSubType");
      }
      // verify the required parameter 'subTypeQuery' is set
      if (subTypeQuery === undefined || subTypeQuery === null) {
        throw new Error("Missing the required parameter 'subTypeQuery' when calling tasqueCareTaskOccurrenceAPIByTeamAndSubType");
      }

      let pathParams = {
        'team_id': teamId
      };
      let queryParams = {
        'sub_type_query': subTypeQuery,'sub_type_id': opts['subTypeId']
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = TasqueListCareTaskOccurrenceList;

      return this.apiClient.callApi(
        '/v0/taken/teams/{team_id}/care_task_occurrences/by_sub_type', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the tasqueCareTaskOccurrenceAPIDestroyFollowing operation.
     * @callback moduleapi/TasqueCareTaskOccurrenceApi~tasqueCareTaskOccurrenceAPIDestroyFollowingCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Removes the given task occurrences item and all of the following occurrences of that item
     * @param {module:model/TasqueCareTaskOccurrence} body AgendaOccurrence to remove
     * @param {String} id Identifier of CareTaskOccurrence to delete.
     * @param {module:api/TasqueCareTaskOccurrenceApi~tasqueCareTaskOccurrenceAPIDestroyFollowingCallback} callback The callback function, accepting three arguments: error, data, response
     */
    tasqueCareTaskOccurrenceAPIDestroyFollowing(body, id, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling tasqueCareTaskOccurrenceAPIDestroyFollowing");
      }
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling tasqueCareTaskOccurrenceAPIDestroyFollowing");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/v0/taken/care_task_occurrences/{id}/destroy_following', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the tasqueCareTaskOccurrenceAPIDestroyIncidentally operation.
     * @callback moduleapi/TasqueCareTaskOccurrenceApi~tasqueCareTaskOccurrenceAPIDestroyIncidentallyCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Removes the given task occurrence item
     * @param {module:model/TasqueCareTaskOccurrence} body AgendaOccurrence to remove
     * @param {String} id Identifier of CareTaskOccurrence to delete.
     * @param {module:api/TasqueCareTaskOccurrenceApi~tasqueCareTaskOccurrenceAPIDestroyIncidentallyCallback} callback The callback function, accepting three arguments: error, data, response
     */
    tasqueCareTaskOccurrenceAPIDestroyIncidentally(body, id, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling tasqueCareTaskOccurrenceAPIDestroyIncidentally");
      }
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling tasqueCareTaskOccurrenceAPIDestroyIncidentally");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/v0/taken/care_task_occurrences/{id}/destroy_incidentally', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the tasqueCareTaskOccurrenceAPIDestroyNextFollowing operation.
     * @callback moduleapi/TasqueCareTaskOccurrenceApi~tasqueCareTaskOccurrenceAPIDestroyNextFollowingCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TasqueCareTaskOccurrence{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Find the next CareTaskOccurrence based on the id and a baseline search date and removes that found task occurrence item and all of the following occurrences of that item
     * @param {module:model/TasqueCareTaskOccurrence} body AgendaOccurrence to remove
     * @param {String} id Identifier of CareTaskOccurrence to delete.
     * @param {Date} _date The date from which the search for the next occurrence should be done
     * @param {module:api/TasqueCareTaskOccurrenceApi~tasqueCareTaskOccurrenceAPIDestroyNextFollowingCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    tasqueCareTaskOccurrenceAPIDestroyNextFollowing(body, id, _date, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling tasqueCareTaskOccurrenceAPIDestroyNextFollowing");
      }
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling tasqueCareTaskOccurrenceAPIDestroyNextFollowing");
      }
      // verify the required parameter '_date' is set
      if (_date === undefined || _date === null) {
        throw new Error("Missing the required parameter '_date' when calling tasqueCareTaskOccurrenceAPIDestroyNextFollowing");
      }

      let pathParams = {
        'id': id,'date': _date
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = TasqueCareTaskOccurrence;

      return this.apiClient.callApi(
        '/v0/taken/care_task_occurrences/{id}/next_date/{date}/destroy_following', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the tasqueCareTaskOccurrenceAPIDestroyNextIncidentally operation.
     * @callback moduleapi/TasqueCareTaskOccurrenceApi~tasqueCareTaskOccurrenceAPIDestroyNextIncidentallyCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TasqueCareTaskOccurrence{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Find the next CareTaskOccurrence based on the id and a baseline search date and removes that found task occurrence item
     * @param {module:model/TasqueCareTaskOccurrence} body AgendaOccurrence to remove
     * @param {String} id Identifier of CareTaskOccurrence to delete.
     * @param {Date} _date The date from which the search for the next occurrence should be done
     * @param {module:api/TasqueCareTaskOccurrenceApi~tasqueCareTaskOccurrenceAPIDestroyNextIncidentallyCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    tasqueCareTaskOccurrenceAPIDestroyNextIncidentally(body, id, _date, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling tasqueCareTaskOccurrenceAPIDestroyNextIncidentally");
      }
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling tasqueCareTaskOccurrenceAPIDestroyNextIncidentally");
      }
      // verify the required parameter '_date' is set
      if (_date === undefined || _date === null) {
        throw new Error("Missing the required parameter '_date' when calling tasqueCareTaskOccurrenceAPIDestroyNextIncidentally");
      }

      let pathParams = {
        'id': id,'date': _date
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = TasqueCareTaskOccurrence;

      return this.apiClient.callApi(
        '/v0/taken/care_task_occurrences/{id}/next_date/{date}/destroy_incidentally', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the tasqueCareTaskOccurrenceAPIFinish operation.
     * @callback moduleapi/TasqueCareTaskOccurrenceApi~tasqueCareTaskOccurrenceAPIFinishCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TasqueCareTaskOccurrence{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Set state of the given task occurrence to finish
     * @param {module:model/TasqueCareTaskOccurrence} body 
     * @param {String} id Identifier of CareTaskOccurrence to update.
     * @param {module:api/TasqueCareTaskOccurrenceApi~tasqueCareTaskOccurrenceAPIFinishCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    tasqueCareTaskOccurrenceAPIFinish(body, id, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling tasqueCareTaskOccurrenceAPIFinish");
      }
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling tasqueCareTaskOccurrenceAPIFinish");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = TasqueCareTaskOccurrence;

      return this.apiClient.callApi(
        '/v0/taken/care_task_occurrences/{id}/finish', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the tasqueCareTaskOccurrenceAPIGetClientIdsBySubType operation.
     * @callback moduleapi/TasqueCareTaskOccurrenceApi~tasqueCareTaskOccurrenceAPIGetClientIdsBySubTypeCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TasqueListClientIdBySubTypeList{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Query unique pairs [&lt;sub_type&gt;, &lt;client_id&gt;, &lt;sub_type_id&gt;] by sub type.
     * @param {String} subTypeQuery String to match tasks that have a &#x27;sub_type&#x27; starting with this string.
     * @param {module:api/TasqueCareTaskOccurrenceApi~tasqueCareTaskOccurrenceAPIGetClientIdsBySubTypeCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    tasqueCareTaskOccurrenceAPIGetClientIdsBySubType(subTypeQuery, callback) {
      
      let postBody = null;
      // verify the required parameter 'subTypeQuery' is set
      if (subTypeQuery === undefined || subTypeQuery === null) {
        throw new Error("Missing the required parameter 'subTypeQuery' when calling tasqueCareTaskOccurrenceAPIGetClientIdsBySubType");
      }

      let pathParams = {
        
      };
      let queryParams = {
        'sub_type_query': subTypeQuery
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = TasqueListClientIdBySubTypeList;

      return this.apiClient.callApi(
        '/v0/taken/care_task_occurrences/client_ids_by_sub_type', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the tasqueCareTaskOccurrenceAPINextById operation.
     * @callback moduleapi/TasqueCareTaskOccurrenceApi~tasqueCareTaskOccurrenceAPINextByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TasqueCareTaskOccurrence{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} id used for selecting CareTaskOccurrence
     * @param {Date} _date used for find the next occurrence
     * @param {module:api/TasqueCareTaskOccurrenceApi~tasqueCareTaskOccurrenceAPINextByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    tasqueCareTaskOccurrenceAPINextById(id, _date, callback) {
      
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling tasqueCareTaskOccurrenceAPINextById");
      }
      // verify the required parameter '_date' is set
      if (_date === undefined || _date === null) {
        throw new Error("Missing the required parameter '_date' when calling tasqueCareTaskOccurrenceAPINextById");
      }

      let pathParams = {
        'id': id,'date': _date
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = TasqueCareTaskOccurrence;

      return this.apiClient.callApi(
        '/v0/taken/care_task_occurrences/{id}/next_date/{date}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the tasqueCareTaskOccurrenceAPIUpdateFollowing operation.
     * @callback moduleapi/TasqueCareTaskOccurrenceApi~tasqueCareTaskOccurrenceAPIUpdateFollowingCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TasqueCareTaskOccurrence{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Updates the given CareTaskOccurrence item and all of the following occurrences of that item
     * @param {module:model/TasqueCareTaskOccurrence} body 
     * @param {String} id Identifier of CareTaskOccurrence to update.
     * @param {module:api/TasqueCareTaskOccurrenceApi~tasqueCareTaskOccurrenceAPIUpdateFollowingCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    tasqueCareTaskOccurrenceAPIUpdateFollowing(body, id, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling tasqueCareTaskOccurrenceAPIUpdateFollowing");
      }
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling tasqueCareTaskOccurrenceAPIUpdateFollowing");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = TasqueCareTaskOccurrence;

      return this.apiClient.callApi(
        '/v0/taken/care_task_occurrences/{id}/update_following', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the tasqueCareTaskOccurrenceAPIUpdateIncidentally operation.
     * @callback moduleapi/TasqueCareTaskOccurrenceApi~tasqueCareTaskOccurrenceAPIUpdateIncidentallyCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TasqueCareTaskOccurrence{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Updates only the given CareTaskOccurrence item
     * @param {module:model/TasqueCareTaskOccurrence} body 
     * @param {String} id Identifier of CareTaskOccurrence to update.
     * @param {module:api/TasqueCareTaskOccurrenceApi~tasqueCareTaskOccurrenceAPIUpdateIncidentallyCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    tasqueCareTaskOccurrenceAPIUpdateIncidentally(body, id, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling tasqueCareTaskOccurrenceAPIUpdateIncidentally");
      }
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling tasqueCareTaskOccurrenceAPIUpdateIncidentally");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = TasqueCareTaskOccurrence;

      return this.apiClient.callApi(
        '/v0/taken/care_task_occurrences/{id}/update_incidentally', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the tasqueCareTaskOccurrenceAPIUpdateNextFollowing operation.
     * @callback moduleapi/TasqueCareTaskOccurrenceApi~tasqueCareTaskOccurrenceAPIUpdateNextFollowingCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TasqueCareTaskOccurrence{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Find the next CareTaskOccurrence based on the id and a baseline search date and update only that found CareTaskOccurrence and all of the following occurrence of that item.
     * @param {module:model/TasqueCareTaskOccurrence} body 
     * @param {String} id Identifier of CareTaskOccurrence to update.
     * @param {Date} _date The date from which the search for the next occurrence should be done
     * @param {module:api/TasqueCareTaskOccurrenceApi~tasqueCareTaskOccurrenceAPIUpdateNextFollowingCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    tasqueCareTaskOccurrenceAPIUpdateNextFollowing(body, id, _date, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling tasqueCareTaskOccurrenceAPIUpdateNextFollowing");
      }
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling tasqueCareTaskOccurrenceAPIUpdateNextFollowing");
      }
      // verify the required parameter '_date' is set
      if (_date === undefined || _date === null) {
        throw new Error("Missing the required parameter '_date' when calling tasqueCareTaskOccurrenceAPIUpdateNextFollowing");
      }

      let pathParams = {
        'id': id,'date': _date
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = TasqueCareTaskOccurrence;

      return this.apiClient.callApi(
        '/v0/taken/care_task_occurrences/{id}/next_date/{date}/update_following', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the tasqueCareTaskOccurrenceAPIUpdateNextIncidentally operation.
     * @callback moduleapi/TasqueCareTaskOccurrenceApi~tasqueCareTaskOccurrenceAPIUpdateNextIncidentallyCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TasqueCareTaskOccurrence{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Find the next CareTaskOccurrence based on the id and a baseline search date and update only that found CareTaskOccurrence.
     * @param {module:model/TasqueCareTaskOccurrence} body 
     * @param {String} id Identifier of CareTaskOccurrence to update.
     * @param {Date} _date The date from which the search for the next occurrence should be done
     * @param {module:api/TasqueCareTaskOccurrenceApi~tasqueCareTaskOccurrenceAPIUpdateNextIncidentallyCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    tasqueCareTaskOccurrenceAPIUpdateNextIncidentally(body, id, _date, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling tasqueCareTaskOccurrenceAPIUpdateNextIncidentally");
      }
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling tasqueCareTaskOccurrenceAPIUpdateNextIncidentally");
      }
      // verify the required parameter '_date' is set
      if (_date === undefined || _date === null) {
        throw new Error("Missing the required parameter '_date' when calling tasqueCareTaskOccurrenceAPIUpdateNextIncidentally");
      }

      let pathParams = {
        'id': id,'date': _date
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = TasqueCareTaskOccurrence;

      return this.apiClient.callApi(
        '/v0/taken/care_task_occurrences/{id}/next_date/{date}/update_incidentally', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}