/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from "../ApiClient";
import ListTeamAssignmentList from '../model/ListTeamAssignmentList';
import TeamAssignment from '../model/TeamAssignment';

/**
* TeamAssignment service.
* @module api/TeamAssignmentApi
* @version 0.0.0
*/
export default class TeamAssignmentApi {

    /**
    * Constructs a new TeamAssignmentApi. 
    * @alias module:api/TeamAssignmentApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the teamAssignmentAPIByEmployeeId operation.
     * @callback moduleapi/TeamAssignmentApi~teamAssignmentAPIByEmployeeIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ListTeamAssignmentList{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Return the team assignments of a Employee corresponding to the given id.
     * @param {Number} employeeId id
     * @param {Object} opts Optional parameters
     * @param {Date} opts.validFrom 
     * @param {Date} opts.validTo 
     * @param {module:api/TeamAssignmentApi~teamAssignmentAPIByEmployeeIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    teamAssignmentAPIByEmployeeId(employeeId, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'employeeId' is set
      if (employeeId === undefined || employeeId === null) {
        throw new Error("Missing the required parameter 'employeeId' when calling teamAssignmentAPIByEmployeeId");
      }

      let pathParams = {
        'employee_id': employeeId
      };
      let queryParams = {
        'valid_from': opts['validFrom'],'valid_to': opts['validTo']
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ListTeamAssignmentList;

      return this.apiClient.callApi(
        '/v0/administration/employees/{employee_id}/teams', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the teamAssignmentAPIByEmployeeIdAndAssignmentId operation.
     * @callback moduleapi/TeamAssignmentApi~teamAssignmentAPIByEmployeeIdAndAssignmentIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TeamAssignment{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update the team assignment with the provided id assigned to the employee corresponding to the provided id.
     * @param {Number} employeeId id
     * @param {Number} teamAssignmentId 
     * @param {module:api/TeamAssignmentApi~teamAssignmentAPIByEmployeeIdAndAssignmentIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    teamAssignmentAPIByEmployeeIdAndAssignmentId(employeeId, teamAssignmentId, callback) {
      
      let postBody = null;
      // verify the required parameter 'employeeId' is set
      if (employeeId === undefined || employeeId === null) {
        throw new Error("Missing the required parameter 'employeeId' when calling teamAssignmentAPIByEmployeeIdAndAssignmentId");
      }
      // verify the required parameter 'teamAssignmentId' is set
      if (teamAssignmentId === undefined || teamAssignmentId === null) {
        throw new Error("Missing the required parameter 'teamAssignmentId' when calling teamAssignmentAPIByEmployeeIdAndAssignmentId");
      }

      let pathParams = {
        'employee_id': employeeId,'team_assignment_id': teamAssignmentId
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = TeamAssignment;

      return this.apiClient.callApi(
        '/v0/administration/employees/{employee_id}/teams/{team_assignment_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the teamAssignmentAPIById operation.
     * @callback moduleapi/TeamAssignmentApi~teamAssignmentAPIByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TeamAssignment{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Return the team assignment with the given id.
     * @param {Number} id id of the team assignment
     * @param {module:api/TeamAssignmentApi~teamAssignmentAPIByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    teamAssignmentAPIById(id, callback) {
      
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling teamAssignmentAPIById");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = TeamAssignment;

      return this.apiClient.callApi(
        '/v0/administration/team_assignments/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the teamAssignmentAPICreateForEmployeeId operation.
     * @callback moduleapi/TeamAssignmentApi~teamAssignmentAPICreateForEmployeeIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TeamAssignment{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create the provided team assignment and assign it to the employee corresponding to the provided id.
     * @param {module:model/TeamAssignment} body 
     * @param {Number} employeeId id
     * @param {module:api/TeamAssignmentApi~teamAssignmentAPICreateForEmployeeIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    teamAssignmentAPICreateForEmployeeId(body, employeeId, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling teamAssignmentAPICreateForEmployeeId");
      }
      // verify the required parameter 'employeeId' is set
      if (employeeId === undefined || employeeId === null) {
        throw new Error("Missing the required parameter 'employeeId' when calling teamAssignmentAPICreateForEmployeeId");
      }

      let pathParams = {
        'employee_id': employeeId
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = TeamAssignment;

      return this.apiClient.callApi(
        '/v0/administration/employees/{employee_id}/teams', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the teamAssignmentAPIRemoveForEmployeeId operation.
     * @callback moduleapi/TeamAssignmentApi~teamAssignmentAPIRemoveForEmployeeIdCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Remove the team assignment with the provided id assigned to the employee corresponding to the provided id.
     * @param {Number} employeeId id
     * @param {Number} teamAssignmentId 
     * @param {module:api/TeamAssignmentApi~teamAssignmentAPIRemoveForEmployeeIdCallback} callback The callback function, accepting three arguments: error, data, response
     */
    teamAssignmentAPIRemoveForEmployeeId(employeeId, teamAssignmentId, callback) {
      
      let postBody = null;
      // verify the required parameter 'employeeId' is set
      if (employeeId === undefined || employeeId === null) {
        throw new Error("Missing the required parameter 'employeeId' when calling teamAssignmentAPIRemoveForEmployeeId");
      }
      // verify the required parameter 'teamAssignmentId' is set
      if (teamAssignmentId === undefined || teamAssignmentId === null) {
        throw new Error("Missing the required parameter 'teamAssignmentId' when calling teamAssignmentAPIRemoveForEmployeeId");
      }

      let pathParams = {
        'employee_id': employeeId,'team_assignment_id': teamAssignmentId
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/v0/administration/employees/{employee_id}/teams/{team_assignment_id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the teamAssignmentAPIStreamAll operation.
     * @callback moduleapi/TeamAssignmentApi~teamAssignmentAPIStreamAllCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ListTeamAssignmentList{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Return all TeamAssignment models in a streaming manner
     * @param {module:api/TeamAssignmentApi~teamAssignmentAPIStreamAllCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    teamAssignmentAPIStreamAll(callback) {
      
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json', 'application/x-ndjson'];
      let returnType = ListTeamAssignmentList;

      return this.apiClient.callApi(
        '/v0/xstream/team_assignments/data', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the teamAssignmentAPIStreamDeletes operation.
     * @callback moduleapi/TeamAssignmentApi~teamAssignmentAPIStreamDeletesCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ListTeamAssignmentList{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Return all TeamAssignment models which where deleted since the date given in the request.
     * If no date is given it will return all deleted TeamAssignment models
     * @param {Date} since 
     * @param {module:api/TeamAssignmentApi~teamAssignmentAPIStreamDeletesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    teamAssignmentAPIStreamDeletes(since, callback) {
      
      let postBody = null;
      // verify the required parameter 'since' is set
      if (since === undefined || since === null) {
        throw new Error("Missing the required parameter 'since' when calling teamAssignmentAPIStreamDeletes");
      }

      let pathParams = {
        
      };
      let queryParams = {
        'since': since
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json', 'application/x-ndjson'];
      let returnType = ListTeamAssignmentList;

      return this.apiClient.callApi(
        '/v0/xstream/team_assignments/deletes', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the teamAssignmentAPIStreamUpdates operation.
     * @callback moduleapi/TeamAssignmentApi~teamAssignmentAPIStreamUpdatesCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ListTeamAssignmentList{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Return all TeamAssignment models which where updated since the date given in the request.
     * @param {Date} since 
     * @param {module:api/TeamAssignmentApi~teamAssignmentAPIStreamUpdatesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    teamAssignmentAPIStreamUpdates(since, callback) {
      
      let postBody = null;
      // verify the required parameter 'since' is set
      if (since === undefined || since === null) {
        throw new Error("Missing the required parameter 'since' when calling teamAssignmentAPIStreamUpdates");
      }

      let pathParams = {
        
      };
      let queryParams = {
        'since': since
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json', 'application/x-ndjson'];
      let returnType = ListTeamAssignmentList;

      return this.apiClient.callApi(
        '/v0/xstream/team_assignments/updates', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the teamAssignmentAPIUpdateForEmployeeId operation.
     * @callback moduleapi/TeamAssignmentApi~teamAssignmentAPIUpdateForEmployeeIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TeamAssignment{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update the team assignment with the provided id assigned to the employee corresponding to the provided id.
     * @param {module:model/TeamAssignment} body 
     * @param {Number} employeeId id
     * @param {Number} teamAssignmentId 
     * @param {module:api/TeamAssignmentApi~teamAssignmentAPIUpdateForEmployeeIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    teamAssignmentAPIUpdateForEmployeeId(body, employeeId, teamAssignmentId, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling teamAssignmentAPIUpdateForEmployeeId");
      }
      // verify the required parameter 'employeeId' is set
      if (employeeId === undefined || employeeId === null) {
        throw new Error("Missing the required parameter 'employeeId' when calling teamAssignmentAPIUpdateForEmployeeId");
      }
      // verify the required parameter 'teamAssignmentId' is set
      if (teamAssignmentId === undefined || teamAssignmentId === null) {
        throw new Error("Missing the required parameter 'teamAssignmentId' when calling teamAssignmentAPIUpdateForEmployeeId");
      }

      let pathParams = {
        'employee_id': employeeId,'team_assignment_id': teamAssignmentId
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = TeamAssignment;

      return this.apiClient.callApi(
        '/v0/administration/employees/{employee_id}/teams/{team_assignment_id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}