/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from "../ApiClient";
import ListLocationList from '../model/ListLocationList';
import ListUserList from '../model/ListUserList';
import PasswordChange from '../model/PasswordChange';
import User from '../model/User';
import UserStatus from '../model/UserStatus';

/**
* User service.
* @module api/UserApi
* @version 0.0.0
*/
export default class UserApi {

    /**
    * Constructs a new UserApi. 
    * @alias module:api/UserApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the userAPIByEmployeeId operation.
     * @callback moduleapi/UserApi~userAPIByEmployeeIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/User{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get user by employee ID
     * @param {Number} employeeId id
     * @param {module:api/UserApi~userAPIByEmployeeIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    userAPIByEmployeeId(employeeId, callback) {
      
      let postBody = null;
      // verify the required parameter 'employeeId' is set
      if (employeeId === undefined || employeeId === null) {
        throw new Error("Missing the required parameter 'employeeId' when calling userAPIByEmployeeId");
      }

      let pathParams = {
        'employee_id': employeeId
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = User;

      return this.apiClient.callApi(
        '/v0/administration/users/by_employee_id/{employee_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the userAPIById operation.
     * @callback moduleapi/UserApi~userAPIByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/User{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get user by ID
     * @param {Number} id used for selecting User
     * @param {module:api/UserApi~userAPIByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    userAPIById(id, callback) {
      
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling userAPIById");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = User;

      return this.apiClient.callApi(
        '/v0/administration/users/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the userAPIBySso operation.
     * @callback moduleapi/UserApi~userAPIBySsoCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ListUserList{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Return the User with the given SSO id
     * @param {String} ssoId 
     * @param {String} ssoProviderId 
     * @param {module:api/UserApi~userAPIBySsoCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    userAPIBySso(ssoId, ssoProviderId, callback) {
      
      let postBody = null;
      // verify the required parameter 'ssoId' is set
      if (ssoId === undefined || ssoId === null) {
        throw new Error("Missing the required parameter 'ssoId' when calling userAPIBySso");
      }
      // verify the required parameter 'ssoProviderId' is set
      if (ssoProviderId === undefined || ssoProviderId === null) {
        throw new Error("Missing the required parameter 'ssoProviderId' when calling userAPIBySso");
      }

      let pathParams = {
        
      };
      let queryParams = {
        'sso_id': ssoId,'sso_provider_id': ssoProviderId
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ListUserList;

      return this.apiClient.callApi(
        '/v0/administration/users/by_sso', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the userAPIByUserName operation.
     * @callback moduleapi/UserApi~userAPIByUserNameCallback
     * @param {String} error Error message, if any.
     * @param {module:model/User{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Find by user name.
     * @param {Object} opts Optional parameters
     * @param {String} opts.username The username of the user to find
     * @param {module:api/UserApi~userAPIByUserNameCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    userAPIByUserName(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        'username': opts['username']
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = User;

      return this.apiClient.callApi(
        '/v0/administration/users/by_username', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the userAPIByUserNameUnsafe operation.
     * @callback moduleapi/UserApi~userAPIByUserNameUnsafeCallback
     * @param {String} error Error message, if any.
     * @param {module:model/User{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Find by user name.
     * Use byUserNameSafe
     * @param {String} userName 
     * @param {module:api/UserApi~userAPIByUserNameUnsafeCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    userAPIByUserNameUnsafe(userName, callback) {
      
      let postBody = null;
      // verify the required parameter 'userName' is set
      if (userName === undefined || userName === null) {
        throw new Error("Missing the required parameter 'userName' when calling userAPIByUserNameUnsafe");
      }

      let pathParams = {
        'user_name': userName
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = User;

      return this.apiClient.callApi(
        '/v0/administration/users/by_username/{user_name}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the userAPIByUuid operation.
     * @callback moduleapi/UserApi~userAPIByUuidCallback
     * @param {String} error Error message, if any.
     * @param {module:model/User{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get user by UUID
     * @param {String} uuid 
     * @param {Object} opts Optional parameters
     * @param {Boolean} opts.bumpSessionExpireTime 
     * @param {module:api/UserApi~userAPIByUuidCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    userAPIByUuid(uuid, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'uuid' is set
      if (uuid === undefined || uuid === null) {
        throw new Error("Missing the required parameter 'uuid' when calling userAPIByUuid");
      }

      let pathParams = {
        'uuid': uuid
      };
      let queryParams = {
        'bump_session_expire_time': opts['bumpSessionExpireTime']
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = User;

      return this.apiClient.callApi(
        '/v0/administration/users/by_uuid/{uuid}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the userAPIChangePassword operation.
     * @callback moduleapi/UserApi~userAPIChangePasswordCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PasswordChange{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Changes the users password
     * @param {module:model/PasswordChange} body the new password, must consist of a combination of upper- and lowercase letters, numbers and special characters
     * @param {Number} userId 
     * @param {module:api/UserApi~userAPIChangePasswordCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    userAPIChangePassword(body, userId, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling userAPIChangePassword");
      }
      // verify the required parameter 'userId' is set
      if (userId === undefined || userId === null) {
        throw new Error("Missing the required parameter 'userId' when calling userAPIChangePassword");
      }

      let pathParams = {
        'user_id': userId
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = PasswordChange;

      return this.apiClient.callApi(
        '/v0/administration/users/{user_id}/password', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the userAPICreate operation.
     * @callback moduleapi/UserApi~userAPICreateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/User{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create User
     * @param {module:model/User} body User to create
     * @param {module:api/UserApi~userAPICreateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    userAPICreate(body, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling userAPICreate");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = User;

      return this.apiClient.callApi(
        '/v0/administration/users', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the userAPIDelete operation.
     * @callback moduleapi/UserApi~userAPIDeleteCallback
     * @param {String} error Error message, if any.
     * @param {module:model/User{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Deletes the User with given id
     * @param {Number} id used for selecting User
     * @param {module:api/UserApi~userAPIDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    userAPIDelete(id, callback) {
      
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling userAPIDelete");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = User;

      return this.apiClient.callApi(
        '/v0/administration/users/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the userAPIGetUserStatus operation.
     * @callback moduleapi/UserApi~userAPIGetUserStatusCallback
     * @param {String} error Error message, if any.
     * @param {module:model/UserStatus{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * returns the status of the user
     * containing a description about if the user is allowed to log into the application
     * @param {Number} userId user id
     * @param {module:api/UserApi~userAPIGetUserStatusCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    userAPIGetUserStatus(userId, callback) {
      
      let postBody = null;
      // verify the required parameter 'userId' is set
      if (userId === undefined || userId === null) {
        throw new Error("Missing the required parameter 'userId' when calling userAPIGetUserStatus");
      }

      let pathParams = {
        'user_id': userId
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = UserStatus;

      return this.apiClient.callApi(
        '/v0/administration/users/{user_id}/status', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the userAPILastVisitedLocations operation.
     * @callback moduleapi/UserApi~userAPILastVisitedLocationsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ListLocationList{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Return the last visited Locations of a User corresponding to the given id.
     * @param {Number} userId id
     * @param {module:api/UserApi~userAPILastVisitedLocationsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    userAPILastVisitedLocations(userId, callback) {
      
      let postBody = null;
      // verify the required parameter 'userId' is set
      if (userId === undefined || userId === null) {
        throw new Error("Missing the required parameter 'userId' when calling userAPILastVisitedLocations");
      }

      let pathParams = {
        'user_id': userId
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ListLocationList;

      return this.apiClient.callApi(
        '/v0/administration/users/{user_id}/last_visited_locations', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the userAPIStreamAll operation.
     * @callback moduleapi/UserApi~userAPIStreamAllCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ListUserList{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Return all User models in a streaming manner
     * @param {module:api/UserApi~userAPIStreamAllCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    userAPIStreamAll(callback) {
      
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json', 'application/x-ndjson'];
      let returnType = ListUserList;

      return this.apiClient.callApi(
        '/v0/xstream/responsibilities/data', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the userAPIStreamDeletes operation.
     * @callback moduleapi/UserApi~userAPIStreamDeletesCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ListUserList{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Return all User models which where deleted since the date given in the request.
     * If no date is given it will return all deleted Membership models
     * @param {Date} since 
     * @param {module:api/UserApi~userAPIStreamDeletesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    userAPIStreamDeletes(since, callback) {
      
      let postBody = null;
      // verify the required parameter 'since' is set
      if (since === undefined || since === null) {
        throw new Error("Missing the required parameter 'since' when calling userAPIStreamDeletes");
      }

      let pathParams = {
        
      };
      let queryParams = {
        'since': since
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json', 'application/x-ndjson'];
      let returnType = ListUserList;

      return this.apiClient.callApi(
        '/v0/xstream/responsibilities/deletes', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the userAPIStreamUpdates operation.
     * @callback moduleapi/UserApi~userAPIStreamUpdatesCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ListUserList{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Return all User models which where updated since the date given in the request.
     * @param {Date} since 
     * @param {module:api/UserApi~userAPIStreamUpdatesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    userAPIStreamUpdates(since, callback) {
      
      let postBody = null;
      // verify the required parameter 'since' is set
      if (since === undefined || since === null) {
        throw new Error("Missing the required parameter 'since' when calling userAPIStreamUpdates");
      }

      let pathParams = {
        
      };
      let queryParams = {
        'since': since
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json', 'application/x-ndjson'];
      let returnType = ListUserList;

      return this.apiClient.callApi(
        '/v0/xstream/responsibilities/updates', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the userAPIUpdate operation.
     * @callback moduleapi/UserApi~userAPIUpdateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/User{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Updates the given User
     * @param {module:model/User} body User to update
     * @param {Number} id used for selecting User
     * @param {module:api/UserApi~userAPIUpdateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    userAPIUpdate(body, id, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling userAPIUpdate");
      }
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling userAPIUpdate");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = User;

      return this.apiClient.callApi(
        '/v0/administration/users/{id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the userAPIViewableLocations operation.
     * @callback moduleapi/UserApi~userAPIViewableLocationsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ListLocationList{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Return the viewable Locations of a User corresponding to the given id.
     * use Shield. See https://github.com/nedap/shield/issues/3207#issuecomment-635947346
     * @param {Number} userId id
     * @param {Object} opts Optional parameters
     * @param {Boolean} opts.ignoreRecursiveLocationsEnabled Only return location user has explicitly access to, ignoring locations beneath those locations (default to <.>)
     * @param {module:api/UserApi~userAPIViewableLocationsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    userAPIViewableLocations(userId, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'userId' is set
      if (userId === undefined || userId === null) {
        throw new Error("Missing the required parameter 'userId' when calling userAPIViewableLocations");
      }

      let pathParams = {
        'user_id': userId
      };
      let queryParams = {
        'ignore_recursive_locations_enabled': opts['ignoreRecursiveLocationsEnabled']
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ListLocationList;

      return this.apiClient.callApi(
        '/v0/administration/users/{user_id}/viewable_locations', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}