/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from "../ApiClient";
import WmoWmoZorglegitimatie from '../model/WmoWmoZorglegitimatie';

/**
* WmoWmoZorglegitimatie service.
* @module api/WmoWmoZorglegitimatieApi
* @version 0.0.0
*/
export default class WmoWmoZorglegitimatieApi {

    /**
    * Constructs a new WmoWmoZorglegitimatieApi. 
    * @alias module:api/WmoWmoZorglegitimatieApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the wmoWmoZorglegitimatieAPIById operation.
     * @callback moduleapi/WmoWmoZorglegitimatieApi~wmoWmoZorglegitimatieAPIByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/WmoWmoZorglegitimatie{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Return the WmoZorgLegitimatie corresponding to the given id
     * @param {Number} id used to find the WmoZorglegitimatie
     * @param {module:api/WmoWmoZorglegitimatieApi~wmoWmoZorglegitimatieAPIByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    wmoWmoZorglegitimatieAPIById(id, callback) {
      
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling wmoWmoZorglegitimatieAPIById");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = WmoWmoZorglegitimatie;

      return this.apiClient.callApi(
        '/v0/administration/wmo/zorglegitimaties/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the wmoWmoZorglegitimatieAPICreate operation.
     * @callback moduleapi/WmoWmoZorglegitimatieApi~wmoWmoZorglegitimatieAPICreateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/WmoWmoZorglegitimatie{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create WmoZorglegitimatie
     * @param {module:model/WmoWmoZorglegitimatie} body WmoZorglegitimatie to create
     * @param {module:api/WmoWmoZorglegitimatieApi~wmoWmoZorglegitimatieAPICreateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    wmoWmoZorglegitimatieAPICreate(body, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling wmoWmoZorglegitimatieAPICreate");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = WmoWmoZorglegitimatie;

      return this.apiClient.callApi(
        '/v0/administration/wmo/zorglegitimaties', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the wmoWmoZorglegitimatieAPIDelete operation.
     * @callback moduleapi/WmoWmoZorglegitimatieApi~wmoWmoZorglegitimatieAPIDeleteCallback
     * @param {String} error Error message, if any.
     * @param {module:model/WmoWmoZorglegitimatie{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete a WmoZorglegitimatie
     * @param {Number} id used to find the WmoZorglegitimatie
     * @param {module:api/WmoWmoZorglegitimatieApi~wmoWmoZorglegitimatieAPIDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    wmoWmoZorglegitimatieAPIDelete(id, callback) {
      
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling wmoWmoZorglegitimatieAPIDelete");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = WmoWmoZorglegitimatie;

      return this.apiClient.callApi(
        '/v0/administration/wmo/zorglegitimaties/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}