/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from "../ApiClient";
import ZorgmailModuleDiagnosticProcedureSearchResult from '../model/ZorgmailModuleDiagnosticProcedureSearchResult';

/**
* ZorgmailModuleDiagnosticProcedure service.
* @module api/ZorgmailModuleDiagnosticProcedureApi
* @version 0.0.0
*/
export default class ZorgmailModuleDiagnosticProcedureApi {

    /**
    * Constructs a new ZorgmailModuleDiagnosticProcedureApi. 
    * @alias module:api/ZorgmailModuleDiagnosticProcedureApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the zorgmailModuleDiagnosticProcedureAPISearch operation.
     * @callback moduleapi/ZorgmailModuleDiagnosticProcedureApi~zorgmailModuleDiagnosticProcedureAPISearchCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ZorgmailModuleDiagnosticProcedureSearchResult{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Searches for diagnostic procedures.
     * Retrieve DiagnosticProcedureReports (lab results) for a particular client. This is the source for the lab results displayed in the Dossier application and medical overview
     * @param {Number} clientId 
     * @param {Object} opts Optional parameters
     * @param {Number} opts.offset 
     * @param {Number} opts.limit 
     * @param {Boolean} opts.includeReports 
     * @param {module:api/ZorgmailModuleDiagnosticProcedureApi~zorgmailModuleDiagnosticProcedureAPISearchCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    zorgmailModuleDiagnosticProcedureAPISearch(clientId, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'clientId' is set
      if (clientId === undefined || clientId === null) {
        throw new Error("Missing the required parameter 'clientId' when calling zorgmailModuleDiagnosticProcedureAPISearch");
      }

      let pathParams = {
        'client_id': clientId
      };
      let queryParams = {
        'offset': opts['offset'],'limit': opts['limit'],'include_reports': opts['includeReports']
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ZorgmailModuleDiagnosticProcedureSearchResult;

      return this.apiClient.callApi(
        '/v0/zorgmail_connector/clients/{client_id}/diagnostic_procedures', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}