/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NedapOnsApi);
  }
}(this, function(expect, NedapOnsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NedapOnsApi.CapacityCapacityProfileApi();
  });

  describe('(package)', function() {
    describe('CapacityCapacityProfileApi', function() {
      describe('capacityCapacityProfileAPIAll', function() {
        it('should call capacityCapacityProfileAPIAll successfully', function(done) {
          // TODO: uncomment capacityCapacityProfileAPIAll call and complete the assertions
          /*

          instance.capacityCapacityProfileAPIAll(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(NedapOnsApi.CapacityListCapacityProfileList);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('capacityCapacityProfileAPIAllActive', function() {
        it('should call capacityCapacityProfileAPIAllActive successfully', function(done) {
          // TODO: uncomment, update parameter values for capacityCapacityProfileAPIAllActive call and complete the assertions
          /*
          var opts = {};

          instance.capacityCapacityProfileAPIAllActive(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(NedapOnsApi.CapacityListCapacityProfileList);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('capacityCapacityProfileAPIById', function() {
        it('should call capacityCapacityProfileAPIById successfully', function(done) {
          // TODO: uncomment, update parameter values for capacityCapacityProfileAPIById call and complete the assertions
          /*

          instance.capacityCapacityProfileAPIById(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(NedapOnsApi.CapacityCapacityProfile);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
