/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NedapOnsApi);
  }
}(this, function(expect, NedapOnsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NedapOnsApi.ClientApi();
  });

  describe('(package)', function() {
    describe('ClientApi', function() {
      describe('clientAPIAddOrUpdateClientInFavorite', function() {
        it('should call clientAPIAddOrUpdateClientInFavorite successfully', function(done) {
          // TODO: uncomment, update parameter values for clientAPIAddOrUpdateClientInFavorite call
          /*

          instance.clientAPIAddOrUpdateClientInFavorite(userId, clientId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('clientAPIAllByArchetypeId', function() {
        it('should call clientAPIAllByArchetypeId successfully', function(done) {
          // TODO: uncomment, update parameter values for clientAPIAllByArchetypeId call and complete the assertions
          /*
          var opts = {};

          instance.clientAPIAllByArchetypeId(archetypeId, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(NedapOnsApi.ListClientList);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('clientAPIByBSN', function() {
        it('should call clientAPIByBSN successfully', function(done) {
          // TODO: uncomment, update parameter values for clientAPIByBSN call and complete the assertions
          /*
          var opts = {};

          instance.clientAPIByBSN(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(NedapOnsApi.Client);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('clientAPIByBSNUnsafe', function() {
        it('should call clientAPIByBSNUnsafe successfully', function(done) {
          // TODO: uncomment, update parameter values for clientAPIByBSNUnsafe call and complete the assertions
          /*
          var opts = {};

          instance.clientAPIByBSNUnsafe(bsn, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(NedapOnsApi.Client);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('clientAPIById', function() {
        it('should call clientAPIById successfully', function(done) {
          // TODO: uncomment, update parameter values for clientAPIById call and complete the assertions
          /*
          var opts = {};

          instance.clientAPIById(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(NedapOnsApi.Client);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('clientAPIByIdentificationNo', function() {
        it('should call clientAPIByIdentificationNo successfully', function(done) {
          // TODO: uncomment, update parameter values for clientAPIByIdentificationNo call and complete the assertions
          /*

          instance.clientAPIByIdentificationNo(identificationNo, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(NedapOnsApi.Client);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('clientAPIBySkn', function() {
        it('should call clientAPIBySkn successfully', function(done) {
          // TODO: uncomment, update parameter values for clientAPIBySkn call and complete the assertions
          /*
          var opts = {};

          instance.clientAPIBySkn(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(NedapOnsApi.Client);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('clientAPIByUUID', function() {
        it('should call clientAPIByUUID successfully', function(done) {
          // TODO: uncomment, update parameter values for clientAPIByUUID call and complete the assertions
          /*
          var opts = {};

          instance.clientAPIByUUID(uuid, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(NedapOnsApi.Client);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('clientAPICreate', function() {
        it('should call clientAPICreate successfully', function(done) {
          // TODO: uncomment, update parameter values for clientAPICreate call and complete the assertions
          /*
          var opts = {};

          instance.clientAPICreate(body, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(NedapOnsApi.Client);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('clientAPILastVisitedByUserId', function() {
        it('should call clientAPILastVisitedByUserId successfully', function(done) {
          // TODO: uncomment, update parameter values for clientAPILastVisitedByUserId call and complete the assertions
          /*

          instance.clientAPILastVisitedByUserId(userId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(NedapOnsApi.ListClientList);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('clientAPILastVisitedClients', function() {
        it('should call clientAPILastVisitedClients successfully', function(done) {
          // TODO: uncomment, update parameter values for clientAPILastVisitedClients call and complete the assertions
          /*
          var opts = {};

          instance.clientAPILastVisitedClients(employeeId, fromDate, toDate, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(NedapOnsApi.ListClientList);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('clientAPIMultiple', function() {
        it('should call clientAPIMultiple successfully', function(done) {
          // TODO: uncomment, update parameter values for clientAPIMultiple call and complete the assertions
          /*
          var opts = {};

          instance.clientAPIMultiple(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(NedapOnsApi.ListClientList);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('clientAPIOmnisearch', function() {
        it('should call clientAPIOmnisearch successfully', function(done) {
          // TODO: uncomment, update parameter values for clientAPIOmnisearch call and complete the assertions
          /*
          var opts = {};

          instance.clientAPIOmnisearch(query, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(NedapOnsApi.ListClientSearchResultList);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('clientAPISearch', function() {
        it('should call clientAPISearch successfully', function(done) {
          // TODO: uncomment, update parameter values for clientAPISearch call and complete the assertions
          /*
          var opts = {};

          instance.clientAPISearch(query, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(NedapOnsApi.ListClientSearchResultList);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('clientAPISearchByLocationId', function() {
        it('should call clientAPISearchByLocationId successfully', function(done) {
          // TODO: uncomment, update parameter values for clientAPISearchByLocationId call and complete the assertions
          /*
          var opts = {};

          instance.clientAPISearchByLocationId(locationId, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(NedapOnsApi.ListClientList);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('clientAPISearchClientIdsInCareInPeriod', function() {
        it('should call clientAPISearchClientIdsInCareInPeriod successfully', function(done) {
          // TODO: uncomment, update parameter values for clientAPISearchClientIdsInCareInPeriod call and complete the assertions
          /*
          var opts = {};

          instance.clientAPISearchClientIdsInCareInPeriod(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(NedapOnsApi.ListClientObjectIdList);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('clientAPISearchGrouped', function() {
        it('should call clientAPISearchGrouped successfully', function(done) {
          // TODO: uncomment, update parameter values for clientAPISearchGrouped call and complete the assertions
          /*
          var opts = {};

          instance.clientAPISearchGrouped(query, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(NedapOnsApi.ListClientSearchResultList);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('clientAPISearchInCareInPeriod', function() {
        it('should call clientAPISearchInCareInPeriod successfully', function(done) {
          // TODO: uncomment, update parameter values for clientAPISearchInCareInPeriod call and complete the assertions
          /*
          var opts = {};

          instance.clientAPISearchInCareInPeriod(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(NedapOnsApi.ListClientList);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('clientAPIStreamAll', function() {
        it('should call clientAPIStreamAll successfully', function(done) {
          // TODO: uncomment clientAPIStreamAll call and complete the assertions
          /*

          instance.clientAPIStreamAll(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(NedapOnsApi.ListClientList);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('clientAPIStreamDeletes', function() {
        it('should call clientAPIStreamDeletes successfully', function(done) {
          // TODO: uncomment, update parameter values for clientAPIStreamDeletes call and complete the assertions
          /*

          instance.clientAPIStreamDeletes(since, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(NedapOnsApi.ListClientList);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('clientAPIStreamUpdates', function() {
        it('should call clientAPIStreamUpdates successfully', function(done) {
          // TODO: uncomment, update parameter values for clientAPIStreamUpdates call and complete the assertions
          /*

          instance.clientAPIStreamUpdates(since, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(NedapOnsApi.ListClientList);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('clientAPIUpdate', function() {
        it('should call clientAPIUpdate successfully', function(done) {
          // TODO: uncomment, update parameter values for clientAPIUpdate call and complete the assertions
          /*
          var opts = {};

          instance.clientAPIUpdate(body, id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(NedapOnsApi.Client);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
