/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NedapOnsApi);
  }
}(this, function(expect, NedapOnsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NedapOnsApi.DossierEpisodesSubGoalApi();
  });

  describe('(package)', function() {
    describe('DossierEpisodesSubGoalApi', function() {
      describe('dossierEpisodesSubGoalAPIByEpisodeId', function() {
        it('should call dossierEpisodesSubGoalAPIByEpisodeId successfully', function(done) {
          // TODO: uncomment, update parameter values for dossierEpisodesSubGoalAPIByEpisodeId call and complete the assertions
          /*

          instance.dossierEpisodesSubGoalAPIByEpisodeId(episodeId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(NedapOnsApi.DossierEpisodesListSubGoalList);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('dossierEpisodesSubGoalAPICreate', function() {
        it('should call dossierEpisodesSubGoalAPICreate successfully', function(done) {
          // TODO: uncomment, update parameter values for dossierEpisodesSubGoalAPICreate call and complete the assertions
          /*

          instance.dossierEpisodesSubGoalAPICreate(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(NedapOnsApi.DossierEpisodesSubGoal);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('dossierEpisodesSubGoalAPIPatch', function() {
        it('should call dossierEpisodesSubGoalAPIPatch successfully', function(done) {
          // TODO: uncomment, update parameter values for dossierEpisodesSubGoalAPIPatch call and complete the assertions
          /*

          instance.dossierEpisodesSubGoalAPIPatch(body, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(NedapOnsApi.DossierEpisodesSubGoal);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('dossierEpisodesSubGoalAPIUpdate', function() {
        it('should call dossierEpisodesSubGoalAPIUpdate successfully', function(done) {
          // TODO: uncomment, update parameter values for dossierEpisodesSubGoalAPIUpdate call and complete the assertions
          /*

          instance.dossierEpisodesSubGoalAPIUpdate(body, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(NedapOnsApi.DossierEpisodesSubGoal);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
