/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NedapOnsApi);
  }
}(this, function(expect, NedapOnsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NedapOnsApi.ExpertiseProfileApi();
  });

  describe('(package)', function() {
    describe('ExpertiseProfileApi', function() {
      describe('expertiseProfileAPIAll', function() {
        it('should call expertiseProfileAPIAll successfully', function(done) {
          // TODO: uncomment expertiseProfileAPIAll call and complete the assertions
          /*

          instance.expertiseProfileAPIAll(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(NedapOnsApi.ListExpertiseProfileList);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('expertiseProfileAPIByEmployeeId', function() {
        it('should call expertiseProfileAPIByEmployeeId successfully', function(done) {
          // TODO: uncomment, update parameter values for expertiseProfileAPIByEmployeeId call and complete the assertions
          /*
          var opts = {};

          instance.expertiseProfileAPIByEmployeeId(employeeId, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(NedapOnsApi.ListExpertiseProfileList);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('expertiseProfileAPIById', function() {
        it('should call expertiseProfileAPIById successfully', function(done) {
          // TODO: uncomment, update parameter values for expertiseProfileAPIById call and complete the assertions
          /*

          instance.expertiseProfileAPIById(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(NedapOnsApi.ExpertiseProfile);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('expertiseProfileAPIMultiple', function() {
        it('should call expertiseProfileAPIMultiple successfully', function(done) {
          // TODO: uncomment, update parameter values for expertiseProfileAPIMultiple call and complete the assertions
          /*
          var opts = {};

          instance.expertiseProfileAPIMultiple(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(NedapOnsApi.ListExpertiseProfileList);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('expertiseProfileAPIStreamAll', function() {
        it('should call expertiseProfileAPIStreamAll successfully', function(done) {
          // TODO: uncomment expertiseProfileAPIStreamAll call and complete the assertions
          /*

          instance.expertiseProfileAPIStreamAll(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(NedapOnsApi.ListExpertiseProfileList);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('expertiseProfileAPIStreamUpdates', function() {
        it('should call expertiseProfileAPIStreamUpdates successfully', function(done) {
          // TODO: uncomment, update parameter values for expertiseProfileAPIStreamUpdates call and complete the assertions
          /*

          instance.expertiseProfileAPIStreamUpdates(since, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(NedapOnsApi.ListExpertiseProfileList);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
