/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NedapOnsApi);
  }
}(this, function(expect, NedapOnsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NedapOnsApi.ExpenseExpenseAddressModelApi();
  });

  describe('(package)', function() {
    describe('ExpenseExpenseAddressModelApi', function() {
      describe('expenseExpenseAddressModelAPICreateOrUpdateExpenseAddress', function() {
        it('should call expenseExpenseAddressModelAPICreateOrUpdateExpenseAddress successfully', function(done) {
          // TODO: uncomment, update parameter values for expenseExpenseAddressModelAPICreateOrUpdateExpenseAddress call and complete the assertions
          /*
          var opts = {};

          instance.expenseExpenseAddressModelAPICreateOrUpdateExpenseAddress(body, employeeId, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(NedapOnsApi.ExpenseExpenseAddressModel);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('expenseExpenseAddressModelAPIGetExpenseAddresses', function() {
        it('should call expenseExpenseAddressModelAPIGetExpenseAddresses successfully', function(done) {
          // TODO: uncomment, update parameter values for expenseExpenseAddressModelAPIGetExpenseAddresses call and complete the assertions
          /*
          var opts = {};

          instance.expenseExpenseAddressModelAPIGetExpenseAddresses(employeeId, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(NedapOnsApi.ExpenseListExpenseAddressModelList);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('expenseExpenseAddressModelAPIRemoveExpenseAddress', function() {
        it('should call expenseExpenseAddressModelAPIRemoveExpenseAddress successfully', function(done) {
          // TODO: uncomment, update parameter values for expenseExpenseAddressModelAPIRemoveExpenseAddress call
          /*
          var opts = {};

          instance.expenseExpenseAddressModelAPIRemoveExpenseAddress(employeeId, expenseAddressId, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
