/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NedapOnsApi);
  }
}(this, function(expect, NedapOnsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NedapOnsApi.FinanceDeclarationRuleApi();
  });

  describe('(package)', function() {
    describe('FinanceDeclarationRuleApi', function() {
      describe('financeDeclarationRuleAPIByClient', function() {
        it('should call financeDeclarationRuleAPIByClient successfully', function(done) {
          // TODO: uncomment, update parameter values for financeDeclarationRuleAPIByClient call and complete the assertions
          /*
          var opts = {};

          instance.financeDeclarationRuleAPIByClient(clientId, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(NedapOnsApi.FinanceListDeclarationRuleList);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('financeDeclarationRuleAPIById', function() {
        it('should call financeDeclarationRuleAPIById successfully', function(done) {
          // TODO: uncomment, update parameter values for financeDeclarationRuleAPIById call and complete the assertions
          /*

          instance.financeDeclarationRuleAPIById(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(NedapOnsApi.FinanceDeclarationRule);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('financeDeclarationRuleAPICreate', function() {
        it('should call financeDeclarationRuleAPICreate successfully', function(done) {
          // TODO: uncomment, update parameter values for financeDeclarationRuleAPICreate call and complete the assertions
          /*

          instance.financeDeclarationRuleAPICreate(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(NedapOnsApi.FinanceDeclarationRule);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('financeDeclarationRuleAPIDelete', function() {
        it('should call financeDeclarationRuleAPIDelete successfully', function(done) {
          // TODO: uncomment, update parameter values for financeDeclarationRuleAPIDelete call and complete the assertions
          /*

          instance.financeDeclarationRuleAPIDelete(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(NedapOnsApi.FinanceDeclarationRule);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('financeDeclarationRuleAPIIsVerifiedInPeriod', function() {
        it('should call financeDeclarationRuleAPIIsVerifiedInPeriod successfully', function(done) {
          // TODO: uncomment, update parameter values for financeDeclarationRuleAPIIsVerifiedInPeriod call and complete the assertions
          /*

          instance.financeDeclarationRuleAPIIsVerifiedInPeriod(clientId, from, to, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(NedapOnsApi.BooleanWithReason);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('financeDeclarationRuleAPIUpdate', function() {
        it('should call financeDeclarationRuleAPIUpdate successfully', function(done) {
          // TODO: uncomment, update parameter values for financeDeclarationRuleAPIUpdate call and complete the assertions
          /*

          instance.financeDeclarationRuleAPIUpdate(body, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(NedapOnsApi.FinanceDeclarationRule);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('financeDeclarationRuleAPIVerifiedUntil', function() {
        it('should call financeDeclarationRuleAPIVerifiedUntil successfully', function(done) {
          // TODO: uncomment, update parameter values for financeDeclarationRuleAPIVerifiedUntil call and complete the assertions
          /*

          instance.financeDeclarationRuleAPIVerifiedUntil(clientId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(NedapOnsApi.DateWrapper);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
