/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NedapOnsApi);
  }
}(this, function(expect, NedapOnsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NedapOnsApi.FreeFieldAssignmentApi();
  });

  describe('(package)', function() {
    describe('FreeFieldAssignmentApi', function() {
      describe('freeFieldAssignmentAPIStreamAll', function() {
        it('should call freeFieldAssignmentAPIStreamAll successfully', function(done) {
          // TODO: uncomment freeFieldAssignmentAPIStreamAll call and complete the assertions
          /*

          instance.freeFieldAssignmentAPIStreamAll(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(NedapOnsApi.ListFreeFieldAssignmentList);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('freeFieldAssignmentAPIStreamUpdates', function() {
        it('should call freeFieldAssignmentAPIStreamUpdates successfully', function(done) {
          // TODO: uncomment, update parameter values for freeFieldAssignmentAPIStreamUpdates call and complete the assertions
          /*

          instance.freeFieldAssignmentAPIStreamUpdates(since, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(NedapOnsApi.ListFreeFieldAssignmentList);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
