/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NedapOnsApi);
  }
}(this, function(expect, NedapOnsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NedapOnsApi.MovesPlanCardOccurrenceApi();
  });

  describe('(package)', function() {
    describe('MovesPlanCardOccurrenceApi', function() {
      describe('movesPlanCardOccurrenceAPIIncidentalChange', function() {
        it('should call movesPlanCardOccurrenceAPIIncidentalChange successfully', function(done) {
          // TODO: uncomment, update parameter values for movesPlanCardOccurrenceAPIIncidentalChange call and complete the assertions
          /*

          instance.movesPlanCardOccurrenceAPIIncidentalChange(body, checksum, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(NedapOnsApi.MovesPlanCardOccurrenceResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('movesPlanCardOccurrenceAPIPlan', function() {
        it('should call movesPlanCardOccurrenceAPIPlan successfully', function(done) {
          // TODO: uncomment, update parameter values for movesPlanCardOccurrenceAPIPlan call and complete the assertions
          /*

          instance.movesPlanCardOccurrenceAPIPlan(body, checksum, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(NedapOnsApi.MovesPlanCardOccurrenceResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('movesPlanCardOccurrenceAPISearch', function() {
        it('should call movesPlanCardOccurrenceAPISearch successfully', function(done) {
          // TODO: uncomment, update parameter values for movesPlanCardOccurrenceAPISearch call and complete the assertions
          /*

          instance.movesPlanCardOccurrenceAPISearch(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(NedapOnsApi.MovesPlanCardOccurrenceList);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
