/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NedapOnsApi);
  }
}(this, function(expect, NedapOnsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NedapOnsApi.ReferralApi();
  });

  describe('(package)', function() {
    describe('ReferralApi', function() {
      describe('referralAPIByClient', function() {
        it('should call referralAPIByClient successfully', function(done) {
          // TODO: uncomment, update parameter values for referralAPIByClient call and complete the assertions
          /*

          instance.referralAPIByClient(clientId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(NedapOnsApi.ListReferralList);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('referralAPIById', function() {
        it('should call referralAPIById successfully', function(done) {
          // TODO: uncomment, update parameter values for referralAPIById call and complete the assertions
          /*

          instance.referralAPIById(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(NedapOnsApi.Referral);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('referralAPICreate', function() {
        it('should call referralAPICreate successfully', function(done) {
          // TODO: uncomment, update parameter values for referralAPICreate call and complete the assertions
          /*

          instance.referralAPICreate(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(NedapOnsApi.Referral);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('referralAPIGetAllReferrerCategories', function() {
        it('should call referralAPIGetAllReferrerCategories successfully', function(done) {
          // TODO: uncomment referralAPIGetAllReferrerCategories call and complete the assertions
          /*

          instance.referralAPIGetAllReferrerCategories(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(NedapOnsApi.ListReferrerCategoryList);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
