/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The Ability model module.
 * @module model/Ability
 * @version 0.0.0
 */
export default class Ability {
  /**
   * Constructs a new <code>Ability</code>.
   * Ability model (no description)
   * @alias module:model/Ability
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Ability</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Ability} obj Optional instance to populate.
   * @return {module:model/Ability} The populated <code>Ability</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Ability();
      if (data.hasOwnProperty('enabled'))
        obj.enabled = ApiClient.convertToType(data['enabled'], 'Boolean');
      if (data.hasOwnProperty('possible'))
        obj.possible = ApiClient.convertToType(data['possible'], 'Boolean');
      if (data.hasOwnProperty('message'))
        obj.message = ApiClient.convertToType(data['message'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Boolean} enabled
 */
Ability.prototype.enabled = undefined;

/**
 * @member {Boolean} possible
 */
Ability.prototype.possible = undefined;

/**
 * @member {String} message
 */
Ability.prototype.message = undefined;

