/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The AdminBackgroundImage model module.
 * @module model/AdminBackgroundImage
 * @version 0.0.0
 */
export default class AdminBackgroundImage {
  /**
   * Constructs a new <code>AdminBackgroundImage</code>.
   * BackgroundImage model (no description)
   * @alias module:model/AdminBackgroundImage
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>AdminBackgroundImage</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AdminBackgroundImage} obj Optional instance to populate.
   * @return {module:model/AdminBackgroundImage} The populated <code>AdminBackgroundImage</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AdminBackgroundImage();
      if (data.hasOwnProperty('isGradient'))
        obj.isGradient = ApiClient.convertToType(data['isGradient'], 'Boolean');
      if (data.hasOwnProperty('backgroundPath'))
        obj.backgroundPath = ApiClient.convertToType(data['backgroundPath'], 'String');
      if (data.hasOwnProperty('color'))
        obj.color = ApiClient.convertToType(data['color'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Boolean} isGradient
 * @default false
 */
AdminBackgroundImage.prototype.isGradient = false;

/**
 * @member {String} backgroundPath
 */
AdminBackgroundImage.prototype.backgroundPath = undefined;

/**
 * @member {String} color
 */
AdminBackgroundImage.prototype.color = undefined;

