/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import ArrangementStakeholder from './ArrangementStakeholder';

/**
 * The ArrangementListStakeholderList model module.
 * @module model/ArrangementListStakeholderList
 * @version 0.0.0
 */
export default class ArrangementListStakeholderList {
  /**
   * Constructs a new <code>ArrangementListStakeholderList</code>.
   * StakeholderList model (no description)
   * @alias module:model/ArrangementListStakeholderList
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ArrangementListStakeholderList</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ArrangementListStakeholderList} obj Optional instance to populate.
   * @return {module:model/ArrangementListStakeholderList} The populated <code>ArrangementListStakeholderList</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ArrangementListStakeholderList();
      if (data.hasOwnProperty('stakeholders'))
        obj.stakeholders = ApiClient.convertToType(data['stakeholders'], [ArrangementStakeholder]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/ArrangementStakeholder>} stakeholders
 */
ArrangementListStakeholderList.prototype.stakeholders = undefined;

