/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import CapacityCapacityCategory from './CapacityCapacityCategory';
import FinanceFinanceType from './FinanceFinanceType';

/**
 * The CapacityCapacityProfile model module.
 * @module model/CapacityCapacityProfile
 * @version 0.0.0
 */
export default class CapacityCapacityProfile {
  /**
   * Constructs a new <code>CapacityCapacityProfile</code>.
   * CapacityProfile is a profile used for capacity management. Every profile can contain multiple {@link CapacityCategory} instances. Every {@link CapacityCategory} can contain multiple {@link CapacityExpertiseProfileAssignment} instances that link a {@link CapacityCategory} to an {@link com.nedap.healthcare.domain.ExpertiseProfile} for a given number of minutes. Besides that, every {@link CapacityCategory} can contain multiple @link CapacityExpertiseGroupAssignment} instances that link a {@link CapacityCategory} to an {@link com.nedap.healthcare.domain.ExpertiseGroup} for a given number of minutes. All those assignments together give an indication of the estimated capacity needed for this profile.
   * @alias module:model/CapacityCapacityProfile
   * @class
   * @param name {String} 
   * @param beginDate {Date} 
   */
  constructor(name, beginDate) {
    this.name = name;
    this.beginDate = beginDate;
  }

  /**
   * Constructs a <code>CapacityCapacityProfile</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CapacityCapacityProfile} obj Optional instance to populate.
   * @return {module:model/CapacityCapacityProfile} The populated <code>CapacityCapacityProfile</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CapacityCapacityProfile();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('comment'))
        obj.comment = ApiClient.convertToType(data['comment'], 'String');
      if (data.hasOwnProperty('financeType'))
        obj.financeType = FinanceFinanceType.constructFromObject(data['financeType']);
      if (data.hasOwnProperty('beginDate'))
        obj.beginDate = ApiClient.convertToType(data['beginDate'], 'Date');
      if (data.hasOwnProperty('endDate'))
        obj.endDate = ApiClient.convertToType(data['endDate'], 'Date');
      if (data.hasOwnProperty('capacityCategories'))
        obj.capacityCategories = ApiClient.convertToType(data['capacityCategories'], [CapacityCapacityCategory]);
      if (data.hasOwnProperty('createdAt'))
        obj.createdAt = ApiClient.convertToType(data['createdAt'], 'Date');
      if (data.hasOwnProperty('updatedAt'))
        obj.updatedAt = ApiClient.convertToType(data['updatedAt'], 'Date');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
CapacityCapacityProfile.prototype.id = undefined;

/**
 * @member {String} name
 */
CapacityCapacityProfile.prototype.name = undefined;

/**
 * Additional optional comments for this profile.
 * @member {String} comment
 */
CapacityCapacityProfile.prototype.comment = undefined;

/**
 * @member {module:model/FinanceFinanceType} financeType
 */
CapacityCapacityProfile.prototype.financeType = undefined;

/**
 * @member {Date} beginDate
 */
CapacityCapacityProfile.prototype.beginDate = undefined;

/**
 * End date of this profile. Can be null for never ending profile.
 * @member {Date} endDate
 */
CapacityCapacityProfile.prototype.endDate = undefined;

/**
 * Set of all {@link CapacityCategory} instances that this profile contains.
 * @member {Array.<module:model/CapacityCapacityCategory>} capacityCategories
 */
CapacityCapacityProfile.prototype.capacityCategories = undefined;

/**
 * @member {Date} createdAt
 */
CapacityCapacityProfile.prototype.createdAt = undefined;

/**
 * @member {Date} updatedAt
 */
CapacityCapacityProfile.prototype.updatedAt = undefined;

