/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The CareProvider model module.
 * @module model/CareProvider
 * @version 0.0.0
 */
export default class CareProvider {
  /**
   * Constructs a new <code>CareProvider</code>.
   * The source of this MedicationChart. A pharmacy. identificationNumber and companyName should be filled. The identificationNumber should be the AGB-code of the pharmacy. All other fields are optional.
   * @alias module:model/CareProvider
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CareProvider</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CareProvider} obj Optional instance to populate.
   * @return {module:model/CareProvider} The populated <code>CareProvider</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CareProvider();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('identificationNumber'))
        obj.identificationNumber = ApiClient.convertToType(data['identificationNumber'], 'String');
      if (data.hasOwnProperty('beholdenId'))
        obj.beholdenId = ApiClient.convertToType(data['beholdenId'], 'String');
      if (data.hasOwnProperty('companyName'))
        obj.companyName = ApiClient.convertToType(data['companyName'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('firstName'))
        obj.firstName = ApiClient.convertToType(data['firstName'], 'String');
      if (data.hasOwnProperty('initials'))
        obj.initials = ApiClient.convertToType(data['initials'], 'String');
      if (data.hasOwnProperty('prefix'))
        obj.prefix = ApiClient.convertToType(data['prefix'], 'String');
      if (data.hasOwnProperty('gender'))
        obj.gender = ApiClient.convertToType(data['gender'], 'String');
      if (data.hasOwnProperty('preferredContactTime'))
        obj.preferredContactTime = ApiClient.convertToType(data['preferredContactTime'], 'String');
      if (data.hasOwnProperty('comments'))
        obj.comments = ApiClient.convertToType(data['comments'], 'String');
      if (data.hasOwnProperty('categoryObjectId'))
        obj.categoryObjectId = ApiClient.convertToType(data['categoryObjectId'], 'Number');
      if (data.hasOwnProperty('organisationCategoryId'))
        obj.organisationCategoryId = ApiClient.convertToType(data['organisationCategoryId'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
CareProvider.prototype.id = undefined;

/**
 * @member {String} identificationNumber
 */
CareProvider.prototype.identificationNumber = undefined;

/**
 * @member {String} beholdenId
 */
CareProvider.prototype.beholdenId = undefined;

/**
 * @member {String} companyName
 */
CareProvider.prototype.companyName = undefined;

/**
 * @member {String} name
 */
CareProvider.prototype.name = undefined;

/**
 * @member {String} firstName
 */
CareProvider.prototype.firstName = undefined;

/**
 * @member {String} initials
 */
CareProvider.prototype.initials = undefined;

/**
 * @member {String} prefix
 */
CareProvider.prototype.prefix = undefined;

/**
 * <pre> Possible values: M - Male F - Female U - Unknown </pre>
 * @member {String} gender
 */
CareProvider.prototype.gender = undefined;

/**
 * @member {String} preferredContactTime
 */
CareProvider.prototype.preferredContactTime = undefined;

/**
 * @member {String} comments
 */
CareProvider.prototype.comments = undefined;

/**
 * @member {Number} categoryObjectId
 */
CareProvider.prototype.categoryObjectId = undefined;

/**
 * @member {Number} organisationCategoryId
 */
CareProvider.prototype.organisationCategoryId = undefined;

