/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import ClientStoryAccessLevel from './ClientStoryAccessLevel';
import ClientStoryCategory from './ClientStoryCategory';

/**
 * The ClientStoryStory model module.
 * @module model/ClientStoryStory
 * @version 0.0.0
 */
export default class ClientStoryStory {
  /**
   * Constructs a new <code>ClientStoryStory</code>.
   * Story model (no description)
   * @alias module:model/ClientStoryStory
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ClientStoryStory</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ClientStoryStory} obj Optional instance to populate.
   * @return {module:model/ClientStoryStory} The populated <code>ClientStoryStory</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ClientStoryStory();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('categories'))
        obj.categories = ApiClient.convertToType(data['categories'], [ClientStoryCategory]);
      if (data.hasOwnProperty('accessLevel'))
        obj.accessLevel = ClientStoryAccessLevel.constructFromObject(data['accessLevel']);
      if (data.hasOwnProperty('updatedAt'))
        obj.updatedAt = ApiClient.convertToType(data['updatedAt'], 'Date');
      if (data.hasOwnProperty('updatedSource'))
        obj.updatedSource = ApiClient.convertToType(data['updatedSource'], 'String');
      if (data.hasOwnProperty('updatedBy'))
        obj.updatedBy = ApiClient.convertToType(data['updatedBy'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
ClientStoryStory.prototype.id = undefined;

/**
 * A list of categories in this client story
 * @member {Array.<module:model/ClientStoryCategory>} categories
 */
ClientStoryStory.prototype.categories = undefined;

/**
 * @member {module:model/ClientStoryAccessLevel} accessLevel
 */
ClientStoryStory.prototype.accessLevel = undefined;

/**
 * When this story was last updated
 * @member {Date} updatedAt
 */
ClientStoryStory.prototype.updatedAt = undefined;

/**
 * The deployment that last updated this story
 * @member {String} updatedSource
 */
ClientStoryStory.prototype.updatedSource = undefined;

/**
 * Who the story was last updated by
 * @member {Number} updatedBy
 */
ClientStoryStory.prototype.updatedBy = undefined;

