/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The Coding model module.
 * @module model/Coding
 * @version 0.0.0
 */
export default class Coding {
  /**
   * Constructs a new <code>Coding</code>.
   * Based on http://hl7.org/fhir/STU3/datatypes.html#Coding
   * @alias module:model/Coding
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Coding</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Coding} obj Optional instance to populate.
   * @return {module:model/Coding} The populated <code>Coding</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Coding();
      if (data.hasOwnProperty('system'))
        obj.system = ApiClient.convertToType(data['system'], 'String');
      if (data.hasOwnProperty('code'))
        obj.code = ApiClient.convertToType(data['code'], 'String');
      if (data.hasOwnProperty('display'))
        obj.display = ApiClient.convertToType(data['display'], 'String');
    }
    return obj;
  }
}

/**
 * Identity of the terminology system (URI)
 * @member {String} system
 */
Coding.prototype.system = undefined;

/**
 * Symbol in syntax defined by the system
 * @member {String} code
 */
Coding.prototype.code = undefined;

/**
 * Representation defined by the system
 * @member {String} display
 */
Coding.prototype.display = undefined;

