/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import AuditedBase from './AuditedBase';

/**
 * The DossierEpisodesAction model module.
 * @module model/DossierEpisodesAction
 * @version 0.0.0
 */
export default class DossierEpisodesAction extends AuditedBase {
  /**
   * Constructs a new <code>DossierEpisodesAction</code>.
   * Action model (no description)
   * @alias module:model/DossierEpisodesAction
   * @class
   * @extends module:model/AuditedBase
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>DossierEpisodesAction</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DossierEpisodesAction} obj Optional instance to populate.
   * @return {module:model/DossierEpisodesAction} The populated <code>DossierEpisodesAction</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DossierEpisodesAction();
      AuditedBase.constructFromObject(data, obj);
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('title'))
        obj.title = ApiClient.convertToType(data['title'], 'String');
      if (data.hasOwnProperty('subGoalId'))
        obj.subGoalId = ApiClient.convertToType(data['subGoalId'], 'Number');
      if (data.hasOwnProperty('showInCarePlan'))
        obj.showInCarePlan = ApiClient.convertToType(data['showInCarePlan'], 'Boolean');
      if (data.hasOwnProperty('archived'))
        obj.archived = ApiClient.convertToType(data['archived'], 'Boolean');
    }
    return obj;
  }
}

/**
 * Object id of this episode action
 * @member {Number} id
 */
DossierEpisodesAction.prototype.id = undefined;

/**
 * Title of this episode action
 * @member {String} title
 */
DossierEpisodesAction.prototype.title = undefined;

/**
 * Object id of the parent episode sub goal
 * @member {Number} subGoalId
 */
DossierEpisodesAction.prototype.subGoalId = undefined;

/**
 * Show this action in the care plan
 * @member {Boolean} showInCarePlan
 */
DossierEpisodesAction.prototype.showInCarePlan = undefined;

/**
 * Archive status of this action
 * @member {Boolean} archived
 */
DossierEpisodesAction.prototype.archived = undefined;

