/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import DossierReportAuthorization from './DossierReportAuthorization';

/**
 * The DossierReportAction model module.
 * @module model/DossierReportAction
 * @version 0.0.0
 */
export default class DossierReportAction extends DossierReportAuthorization {
  /**
   * Constructs a new <code>DossierReportAction</code>.
   * ReportAction model (no description)
   * @alias module:model/DossierReportAction
   * @class
   * @extends module:model/DossierReportAuthorization
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>DossierReportAction</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DossierReportAction} obj Optional instance to populate.
   * @return {module:model/DossierReportAction} The populated <code>DossierReportAction</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DossierReportAction();
      DossierReportAuthorization.constructFromObject(data, obj);
      if (data.hasOwnProperty('employeeId'))
        obj.employeeId = ApiClient.convertToType(data['employeeId'], 'Number');
      if (data.hasOwnProperty('dateFinished'))
        obj.dateFinished = ApiClient.convertToType(data['dateFinished'], 'Date');
    }
    return obj;
  }
}

/**
 * @member {Number} employeeId
 */
DossierReportAction.prototype.employeeId = undefined;

/**
 * @member {Date} dateFinished
 */
DossierReportAction.prototype.dateFinished = undefined;

