/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import AuditedBase from './AuditedBase';

/**
 * The DossierDomain model module.
 * @module model/DossierDomain
 * @version 0.0.0
 */
export default class DossierDomain extends AuditedBase {
  /**
   * Constructs a new <code>DossierDomain</code>.
   * Zorgplan \&quot;domein\&quot;
   * @alias module:model/DossierDomain
   * @class
   * @extends module:model/AuditedBase
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>DossierDomain</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DossierDomain} obj Optional instance to populate.
   * @return {module:model/DossierDomain} The populated <code>DossierDomain</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DossierDomain();
      AuditedBase.constructFromObject(data, obj);
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('hidden'))
        obj.hidden = ApiClient.convertToType(data['hidden'], 'Boolean');
      if (data.hasOwnProperty('classificationId'))
        obj.classificationId = ApiClient.convertToType(data['classificationId'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
DossierDomain.prototype.id = undefined;

/**
 * (nl) Naam van dit domein
 * @member {String} name
 */
DossierDomain.prototype.name = undefined;

/**
 * @member {Boolean} hidden
 * @default false
 */
DossierDomain.prototype.hidden = false;

/**
 * @member {String} classificationId
 */
DossierDomain.prototype.classificationId = undefined;

