/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import DossierMedicalRelationshipBuilder from './DossierMedicalRelationshipBuilder';

/**
 * The DossierMedicalDiagnosisBuilder model module.
 * @module model/DossierMedicalDiagnosisBuilder
 * @version 0.0.0
 */
export default class DossierMedicalDiagnosisBuilder extends DossierMedicalRelationshipBuilder {
  /**
   * Constructs a new <code>DossierMedicalDiagnosisBuilder</code>.
   * DiagnosisBuilder model (no description)
   * @alias module:model/DossierMedicalDiagnosisBuilder
   * @class
   * @extends module:model/DossierMedicalRelationshipBuilder
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>DossierMedicalDiagnosisBuilder</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DossierMedicalDiagnosisBuilder} obj Optional instance to populate.
   * @return {module:model/DossierMedicalDiagnosisBuilder} The populated <code>DossierMedicalDiagnosisBuilder</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DossierMedicalDiagnosisBuilder();
      DossierMedicalRelationshipBuilder.constructFromObject(data, obj);
    }
    return obj;
  }
}
