/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import DossierMedicalDsmClassification from './DossierMedicalDsmClassification';

/**
 * The DossierMedicalDsmListClassificationList model module.
 * @module model/DossierMedicalDsmListClassificationList
 * @version 0.0.0
 */
export default class DossierMedicalDsmListClassificationList {
  /**
   * Constructs a new <code>DossierMedicalDsmListClassificationList</code>.
   * ClassificationList model (no description)
   * @alias module:model/DossierMedicalDsmListClassificationList
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>DossierMedicalDsmListClassificationList</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DossierMedicalDsmListClassificationList} obj Optional instance to populate.
   * @return {module:model/DossierMedicalDsmListClassificationList} The populated <code>DossierMedicalDsmListClassificationList</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DossierMedicalDsmListClassificationList();
      if (data.hasOwnProperty('classifications'))
        obj.classifications = ApiClient.convertToType(data['classifications'], [DossierMedicalDsmClassification]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/DossierMedicalDsmClassification>} classifications
 */
DossierMedicalDsmListClassificationList.prototype.classifications = undefined;

