/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The DossierReportsWithActionsSummary model module.
 * @module model/DossierReportsWithActionsSummary
 * @version 0.0.0
 */
export default class DossierReportsWithActionsSummary {
  /**
   * Constructs a new <code>DossierReportsWithActionsSummary</code>.
   * ReportsWithActionsSummary model (no description)
   * @alias module:model/DossierReportsWithActionsSummary
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>DossierReportsWithActionsSummary</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DossierReportsWithActionsSummary} obj Optional instance to populate.
   * @return {module:model/DossierReportsWithActionsSummary} The populated <code>DossierReportsWithActionsSummary</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DossierReportsWithActionsSummary();
      if (data.hasOwnProperty('actionsForUser'))
        obj.actionsForUser = ApiClient.convertToType(data['actionsForUser'], 'Number');
      if (data.hasOwnProperty('actionsByUser'))
        obj.actionsByUser = ApiClient.convertToType(data['actionsByUser'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} actionsForUser
 */
DossierReportsWithActionsSummary.prototype.actionsForUser = undefined;

/**
 * @member {Number} actionsByUser
 */
DossierReportsWithActionsSummary.prototype.actionsByUser = undefined;

