/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * Enum class DossierFeederAuditTransferType.
 * @enum {String}
 * @readonly
 */
const DossierFeederAuditTransferType = {
  /**
   * value: "eoverdracht_nursing"
   * @const
   */
  eoverdrachtNursing: "eoverdracht_nursing",

  /**
   * value: "anw"
   * @const
   */
  anw: "anw",

  /**
   * value: "other"
   * @const
   */
  other: "other",

  /**
   * Returns a <code>DossierFeederAuditTransferType</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/DossierFeederAuditTransferType} The enum <code>DossierFeederAuditTransferType</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export default {DossierFeederAuditTransferType};