/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import DossierOmahaDomain from './DossierOmahaDomain';
import DossierOmahaSignOrSymptom from './DossierOmahaSignOrSymptom';

/**
 * The DossierOmahaProblem model module.
 * @module model/DossierOmahaProblem
 * @version 0.0.0
 */
export default class DossierOmahaProblem {
  /**
   * Constructs a new <code>DossierOmahaProblem</code>.
   * Omaha definitie van &#x27;gebied&#x27; 
   * @alias module:model/DossierOmahaProblem
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>DossierOmahaProblem</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DossierOmahaProblem} obj Optional instance to populate.
   * @return {module:model/DossierOmahaProblem} The populated <code>DossierOmahaProblem</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DossierOmahaProblem();
      if (data.hasOwnProperty('classificationId'))
        obj.classificationId = ApiClient.convertToType(data['classificationId'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('omahaDomain'))
        obj.omahaDomain = DossierOmahaDomain.constructFromObject(data['omahaDomain']);
      if (data.hasOwnProperty('omahaSignsAndSymptoms'))
        obj.omahaSignsAndSymptoms = ApiClient.convertToType(data['omahaSignsAndSymptoms'], [DossierOmahaSignOrSymptom]);
    }
    return obj;
  }
}

/**
 * @member {String} classificationId
 */
DossierOmahaProblem.prototype.classificationId = undefined;

/**
 * (nl) Naam van dit gebied
 * @member {String} name
 */
DossierOmahaProblem.prototype.name = undefined;

/**
 * @member {module:model/DossierOmahaDomain} omahaDomain
 */
DossierOmahaProblem.prototype.omahaDomain = undefined;

/**
 * (nl) Gerelateerde signalen en symptomen
 * @member {Array.<module:model/DossierOmahaSignOrSymptom>} omahaSignsAndSymptoms
 */
DossierOmahaProblem.prototype.omahaSignsAndSymptoms = undefined;

