/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import DossierMedicalMedicalSummary from './DossierMedicalMedicalSummary';

/**
 * The DossierMedicalListMedicalSummaryList model module.
 * @module model/DossierMedicalListMedicalSummaryList
 * @version 0.0.0
 */
export default class DossierMedicalListMedicalSummaryList {
  /**
   * Constructs a new <code>DossierMedicalListMedicalSummaryList</code>.
   * MedicalSummaryList model (no description)
   * @alias module:model/DossierMedicalListMedicalSummaryList
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>DossierMedicalListMedicalSummaryList</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DossierMedicalListMedicalSummaryList} obj Optional instance to populate.
   * @return {module:model/DossierMedicalListMedicalSummaryList} The populated <code>DossierMedicalListMedicalSummaryList</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DossierMedicalListMedicalSummaryList();
      if (data.hasOwnProperty('medicalSummaries'))
        obj.medicalSummaries = ApiClient.convertToType(data['medicalSummaries'], [DossierMedicalMedicalSummary]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/DossierMedicalMedicalSummary>} medicalSummaries
 */
DossierMedicalListMedicalSummaryList.prototype.medicalSummaries = undefined;

