/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The DossierCarePlanMetadata model module.
 * @module model/DossierCarePlanMetadata
 * @version 0.0.0
 */
export default class DossierCarePlanMetadata {
  /**
   * Constructs a new <code>DossierCarePlanMetadata</code>.
   * CarePlanMetadata model (no description)
   * @alias module:model/DossierCarePlanMetadata
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>DossierCarePlanMetadata</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DossierCarePlanMetadata} obj Optional instance to populate.
   * @return {module:model/DossierCarePlanMetadata} The populated <code>DossierCarePlanMetadata</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DossierCarePlanMetadata();
      if (data.hasOwnProperty('clientId'))
        obj.clientId = ApiClient.convertToType(data['clientId'], 'Number');
      if (data.hasOwnProperty('beginDate'))
        obj.beginDate = ApiClient.convertToType(data['beginDate'], 'Date');
      if (data.hasOwnProperty('endDate'))
        obj.endDate = ApiClient.convertToType(data['endDate'], 'Date');
    }
    return obj;
  }
}

/**
 * @member {Number} clientId
 */
DossierCarePlanMetadata.prototype.clientId = undefined;

/**
 * Begin date of this care plan
 * @member {Date} beginDate
 */
DossierCarePlanMetadata.prototype.beginDate = undefined;

/**
 * End date of this care plan
 * @member {Date} endDate
 */
DossierCarePlanMetadata.prototype.endDate = undefined;

