/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The DossierMedicalAdvanceDirectivesDecision model module.
 * @module model/DossierMedicalAdvanceDirectivesDecision
 * @version 0.0.0
 */
export default class DossierMedicalAdvanceDirectivesDecision {
  /**
   * Constructs a new <code>DossierMedicalAdvanceDirectivesDecision</code>.
   * Decision model (no description)
   * @alias module:model/DossierMedicalAdvanceDirectivesDecision
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>DossierMedicalAdvanceDirectivesDecision</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DossierMedicalAdvanceDirectivesDecision} obj Optional instance to populate.
   * @return {module:model/DossierMedicalAdvanceDirectivesDecision} The populated <code>DossierMedicalAdvanceDirectivesDecision</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DossierMedicalAdvanceDirectivesDecision();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('outcome'))
        obj.outcome = ApiClient.convertToType(data['outcome'], 'String');
      if (data.hasOwnProperty('snomedExpressionValue'))
        obj.snomedExpressionValue = ApiClient.convertToType(data['snomedExpressionValue'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
DossierMedicalAdvanceDirectivesDecision.prototype.name = undefined;

/**
 * @member {String} outcome
 */
DossierMedicalAdvanceDirectivesDecision.prototype.outcome = undefined;

/**
 * snomedexpression of the whole decision. Example: \"363589002 | associated procedure |: 246456000 | has interpretation | =439569004 | resuscitation |, 408729009 | finding context | =373066001 | yes |\"
 * @member {String} snomedExpressionValue
 */
DossierMedicalAdvanceDirectivesDecision.prototype.snomedExpressionValue = undefined;

