/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import FinanceNamedItemModel from './FinanceNamedItemModel';

/**
 * The FinanceGroupActivityModel model module.
 * @module model/FinanceGroupActivityModel
 * @version 0.0.0
 */
export default class FinanceGroupActivityModel {
  /**
   * Constructs a new <code>FinanceGroupActivityModel</code>.
   * A group-level finance activity used by the finance API. Use this model as the request body when creating or updating a group activity and as the response payload when reading group activities. Field guidance: - id: database identifier, optional for create and required for update/delete. - name: human-readable label for the group activity (required). - financeTypeCount: number of distinct finance types associated with this group activity; clients may omit this and the server can compute it from the &#x60;financeTypes&#x60; list. - financeTypes: optional list of finance types (id + name) attached to this group activity; provide these to explicitly set associations on create/update.
   * @alias module:model/FinanceGroupActivityModel
   * @class
   * @param name {String} Name of the group activity. Required for create and update operations.
   */
  constructor(name) {
    this.name = name;
  }

  /**
   * Constructs a <code>FinanceGroupActivityModel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FinanceGroupActivityModel} obj Optional instance to populate.
   * @return {module:model/FinanceGroupActivityModel} The populated <code>FinanceGroupActivityModel</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new FinanceGroupActivityModel();
      if (data.hasOwnProperty('distinctFinanceTypeCount'))
        obj.distinctFinanceTypeCount = ApiClient.convertToType(data['distinctFinanceTypeCount'], 'Number');
      if (data.hasOwnProperty('financeTypes'))
        obj.financeTypes = ApiClient.convertToType(data['financeTypes'], [FinanceNamedItemModel]);
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} distinctFinanceTypeCount
 */
FinanceGroupActivityModel.prototype.distinctFinanceTypeCount = undefined;

/**
 * @member {Array.<module:model/FinanceNamedItemModel>} financeTypes
 */
FinanceGroupActivityModel.prototype.financeTypes = undefined;

/**
 * Required for UPDATE or DELETE operations, not required for CREATE
 * @member {Number} id
 */
FinanceGroupActivityModel.prototype.id = undefined;

/**
 * Name of the group activity. Required for create and update operations.
 * @member {String} name
 */
FinanceGroupActivityModel.prototype.name = undefined;

