/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import FinanceDebtorGroup from './FinanceDebtorGroup';

/**
 * The FinanceListDebtorGroupList model module.
 * @module model/FinanceListDebtorGroupList
 * @version 0.0.0
 */
export default class FinanceListDebtorGroupList {
  /**
   * Constructs a new <code>FinanceListDebtorGroupList</code>.
   * DebtorGroupList model (no description)
   * @alias module:model/FinanceListDebtorGroupList
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>FinanceListDebtorGroupList</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FinanceListDebtorGroupList} obj Optional instance to populate.
   * @return {module:model/FinanceListDebtorGroupList} The populated <code>FinanceListDebtorGroupList</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new FinanceListDebtorGroupList();
      if (data.hasOwnProperty('debtorGroups'))
        obj.debtorGroups = ApiClient.convertToType(data['debtorGroups'], [FinanceDebtorGroup]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/FinanceDebtorGroup>} debtorGroups
 */
FinanceListDebtorGroupList.prototype.debtorGroups = undefined;

