/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import Address from './Address';

/**
 * The ListAddressList model module.
 * @module model/ListAddressList
 * @version 0.0.0
 */
export default class ListAddressList {
  /**
   * Constructs a new <code>ListAddressList</code>.
   * AddressList model (no description)
   * @alias module:model/ListAddressList
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ListAddressList</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ListAddressList} obj Optional instance to populate.
   * @return {module:model/ListAddressList} The populated <code>ListAddressList</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ListAddressList();
      if (data.hasOwnProperty('addresses'))
        obj.addresses = ApiClient.convertToType(data['addresses'], [Address]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/Address>} addresses
 */
ListAddressList.prototype.addresses = undefined;

