/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The MovesShiftAssignment model module.
 * @module model/MovesShiftAssignment
 * @version 0.0.0
 */
export default class MovesShiftAssignment {
  /**
   * Constructs a new <code>MovesShiftAssignment</code>.
   * Updated by Jurriën Gosselink on 04-03-19
   * @alias module:model/MovesShiftAssignment
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>MovesShiftAssignment</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MovesShiftAssignment} obj Optional instance to populate.
   * @return {module:model/MovesShiftAssignment} The populated <code>MovesShiftAssignment</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MovesShiftAssignment();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('date'))
        obj._date = ApiClient.convertToType(data['date'], 'Date');
      if (data.hasOwnProperty('beginTime'))
        obj.beginTime = ApiClient.convertToType(data['beginTime'], 'Date');
      if (data.hasOwnProperty('endTime'))
        obj.endTime = ApiClient.convertToType(data['endTime'], 'Date');
      if (data.hasOwnProperty('shiftId'))
        obj.shiftId = ApiClient.convertToType(data['shiftId'], 'String');
      if (data.hasOwnProperty('shiftName'))
        obj.shiftName = ApiClient.convertToType(data['shiftName'], 'String');
      if (data.hasOwnProperty('employeeId'))
        obj.employeeId = ApiClient.convertToType(data['employeeId'], 'Number');
      if (data.hasOwnProperty('employeeLeadingName'))
        obj.employeeLeadingName = ApiClient.convertToType(data['employeeLeadingName'], 'String');
      if (data.hasOwnProperty('employeeName'))
        obj.employeeName = ApiClient.convertToType(data['employeeName'], 'String');
      if (data.hasOwnProperty('externalExpertiseProfileId'))
        obj.externalExpertiseProfileId = ApiClient.convertToType(data['externalExpertiseProfileId'], 'Number');
      if (data.hasOwnProperty('expertiseProfileName'))
        obj.expertiseProfileName = ApiClient.convertToType(data['expertiseProfileName'], 'String');
      if (data.hasOwnProperty('onCall'))
        obj.onCall = ApiClient.convertToType(data['onCall'], 'Boolean');
      if (data.hasOwnProperty('timelineShiftId'))
        obj.timelineShiftId = ApiClient.convertToType(data['timelineShiftId'], 'Number');
      if (data.hasOwnProperty('unitId'))
        obj.unitId = ApiClient.convertToType(data['unitId'], 'Number');
      if (data.hasOwnProperty('breakDuration'))
        obj.breakDuration = ApiClient.convertToType(data['breakDuration'], 'Number');
      if (data.hasOwnProperty('incidental'))
        obj.incidental = ApiClient.convertToType(data['incidental'], 'Boolean');
      if (data.hasOwnProperty('order'))
        obj.order = ApiClient.convertToType(data['order'], 'Number');
      if (data.hasOwnProperty('startBreakTime'))
        obj.startBreakTime = ApiClient.convertToType(data['startBreakTime'], 'Date');
      if (data.hasOwnProperty('stopBreakTime'))
        obj.stopBreakTime = ApiClient.convertToType(data['stopBreakTime'], 'Date');
      if (data.hasOwnProperty('discardedAt'))
        obj.discardedAt = ApiClient.convertToType(data['discardedAt'], 'Date');
      if (data.hasOwnProperty('exportable'))
        obj.exportable = ApiClient.convertToType(data['exportable'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
MovesShiftAssignment.prototype.id = undefined;

/**
 * @member {Date} _date
 */
MovesShiftAssignment.prototype._date = undefined;

/**
 * Effective begin time (based on the shift or incidental)
 * @member {Date} beginTime
 */
MovesShiftAssignment.prototype.beginTime = undefined;

/**
 * Effective end time (based on the shift or incidental)
 * @member {Date} endTime
 */
MovesShiftAssignment.prototype.endTime = undefined;

/**
 * Composed from the timeline_id and date: \"413@2019-05-01\"
 * @member {String} shiftId
 */
MovesShiftAssignment.prototype.shiftId = undefined;

/**
 * Name of the shift
 * @member {String} shiftName
 */
MovesShiftAssignment.prototype.shiftName = undefined;

/**
 * @member {Number} employeeId
 */
MovesShiftAssignment.prototype.employeeId = undefined;

/**
 * @member {String} employeeLeadingName
 */
MovesShiftAssignment.prototype.employeeLeadingName = undefined;

/**
 * @member {String} employeeName
 */
MovesShiftAssignment.prototype.employeeName = undefined;

/**
 * Effective expertise profile (based on the shift or incidentally changed)
 * @member {Number} externalExpertiseProfileId
 */
MovesShiftAssignment.prototype.externalExpertiseProfileId = undefined;

/**
 * Name of the effective expertise profile
 * @member {String} expertiseProfileName
 */
MovesShiftAssignment.prototype.expertiseProfileName = undefined;

/**
 * Is it an on-call (bereikbaarheidsdienst) shift
 * @member {Boolean} onCall
 */
MovesShiftAssignment.prototype.onCall = undefined;

/**
 * To what shift does it belong
 * @member {Number} timelineShiftId
 */
MovesShiftAssignment.prototype.timelineShiftId = undefined;

/**
 * To what unit/team does it belong
 * @member {Number} unitId
 */
MovesShiftAssignment.prototype.unitId = undefined;

/**
 * How long is the break (in minutes)
 * @member {Number} breakDuration
 */
MovesShiftAssignment.prototype.breakDuration = undefined;

/**
 * Has one of the following fields been changed in comparison to the original shift (begin/end time, start/stop break time and/or expertise profile).
 * @member {Boolean} incidental
 */
MovesShiftAssignment.prototype.incidental = undefined;

/**
 * Order of ShiftAssignments if there are multiple on the same date and shift.
 * @member {Number} order
 */
MovesShiftAssignment.prototype.order = undefined;

/**
 * Effective start break time (based on the shift or incidental)
 * @member {Date} startBreakTime
 */
MovesShiftAssignment.prototype.startBreakTime = undefined;

/**
 * Effective stop break time (based on the shift or incidental)
 * @member {Date} stopBreakTime
 */
MovesShiftAssignment.prototype.stopBreakTime = undefined;

/**
 * Shift Assignments are not hard-deleted, but marked as discarded. When the Shift Assignment is discarded, discardedAt shows when this was discarded.
 * @member {Date} discardedAt
 */
MovesShiftAssignment.prototype.discardedAt = undefined;

/**
 * Indicates if this ShiftAssignnment will be exported. Only available through specific APIs.
 * @member {Boolean} exportable
 */
MovesShiftAssignment.prototype.exportable = undefined;

