/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import MovesAvailabilityOccurrence from './MovesAvailabilityOccurrence';
import MovesLeaveRequestOccurrence from './MovesLeaveRequestOccurrence';
import MovesPlannedVisit from './MovesPlannedVisit';
import MovesRosterSlot from './MovesRosterSlot';
import MovesUnavailabilityOccurrence from './MovesUnavailabilityOccurrence';

/**
 * The MovesEmployeeScheduleItem model module.
 * @module model/MovesEmployeeScheduleItem
 * @version 0.0.0
 */
export default class MovesEmployeeScheduleItem {
  /**
   * Constructs a new <code>MovesEmployeeScheduleItem</code>.
   * An item rostered, planned, or otherwise scheduled for an Employee in Ons Planning.
   * @alias module:model/MovesEmployeeScheduleItem
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>MovesEmployeeScheduleItem</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MovesEmployeeScheduleItem} obj Optional instance to populate.
   * @return {module:model/MovesEmployeeScheduleItem} The populated <code>MovesEmployeeScheduleItem</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MovesEmployeeScheduleItem();
      if (data.hasOwnProperty('rosterSlot'))
        obj.rosterSlot = MovesRosterSlot.constructFromObject(data['rosterSlot']);
      if (data.hasOwnProperty('unavailabilityOccurrence'))
        obj.unavailabilityOccurrence = MovesUnavailabilityOccurrence.constructFromObject(data['unavailabilityOccurrence']);
      if (data.hasOwnProperty('directlyPlannedVisits'))
        obj.directlyPlannedVisits = ApiClient.convertToType(data['directlyPlannedVisits'], [MovesPlannedVisit]);
      if (data.hasOwnProperty('availabilityOccurrence'))
        obj.availabilityOccurrence = MovesAvailabilityOccurrence.constructFromObject(data['availabilityOccurrence']);
      if (data.hasOwnProperty('leaveRequestOccurrence'))
        obj.leaveRequestOccurrence = MovesLeaveRequestOccurrence.constructFromObject(data['leaveRequestOccurrence']);
      if (data.hasOwnProperty('displayCategory'))
        obj.displayCategory = ApiClient.convertToType(data['displayCategory'], 'String');
      if (data.hasOwnProperty('onsdraaiboekUrl'))
        obj.onsdraaiboekUrl = ApiClient.convertToType(data['onsdraaiboekUrl'], 'String');
    }
    return obj;
  }
}

/**
 * @member {module:model/MovesRosterSlot} rosterSlot
 */
MovesEmployeeScheduleItem.prototype.rosterSlot = undefined;

/**
 * @member {module:model/MovesUnavailabilityOccurrence} unavailabilityOccurrence
 */
MovesEmployeeScheduleItem.prototype.unavailabilityOccurrence = undefined;

/**
 * PlannedVisits that have been directly planned to the Employee.  When directlyPlannedVisits is set, rosterSlot, unavailabilityOccurrence, availabilityOccurrence and leaveRequestOccurrence are all null.
 * @member {Array.<module:model/MovesPlannedVisit>} directlyPlannedVisits
 */
MovesEmployeeScheduleItem.prototype.directlyPlannedVisits = undefined;

/**
 * @member {module:model/MovesAvailabilityOccurrence} availabilityOccurrence
 */
MovesEmployeeScheduleItem.prototype.availabilityOccurrence = undefined;

/**
 * @member {module:model/MovesLeaveRequestOccurrence} leaveRequestOccurrence
 */
MovesEmployeeScheduleItem.prototype.leaveRequestOccurrence = undefined;

/**
 * Indicates how this item should be presented to the user. <pre> working not-working not-working-tentative available flex-signed-up </pre>
 * @member {String} displayCategory
 */
MovesEmployeeScheduleItem.prototype.displayCategory = undefined;

/**
 * URL to OnsDraaiboek where this item can be found.
 * @member {String} onsdraaiboekUrl
 */
MovesEmployeeScheduleItem.prototype.onsdraaiboekUrl = undefined;

