/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The MovesPlannedAddress model module.
 * @module model/MovesPlannedAddress
 * @version 0.0.0
 */
export default class MovesPlannedAddress {
  /**
   * Constructs a new <code>MovesPlannedAddress</code>.
   * Address where {@link PlannedVisit}s are planned.  Moves has it&#x27;s own Address model, and plancards can be planned tp addresses not known in other systems.
   * @alias module:model/MovesPlannedAddress
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>MovesPlannedAddress</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MovesPlannedAddress} obj Optional instance to populate.
   * @return {module:model/MovesPlannedAddress} The populated <code>MovesPlannedAddress</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MovesPlannedAddress();
      if (data.hasOwnProperty('latitude'))
        obj.latitude = ApiClient.convertToType(data['latitude'], 'Number');
      if (data.hasOwnProperty('longitude'))
        obj.longitude = ApiClient.convertToType(data['longitude'], 'Number');
      if (data.hasOwnProperty('city'))
        obj.city = ApiClient.convertToType(data['city'], 'String');
      if (data.hasOwnProperty('street'))
        obj.street = ApiClient.convertToType(data['street'], 'String');
      if (data.hasOwnProperty('zipcode'))
        obj.zipcode = ApiClient.convertToType(data['zipcode'], 'String');
      if (data.hasOwnProperty('number'))
        obj._number = ApiClient.convertToType(data['number'], 'String');
      if (data.hasOwnProperty('numberPostfix'))
        obj.numberPostfix = ApiClient.convertToType(data['numberPostfix'], 'String');
      if (data.hasOwnProperty('residenceAccessInfo'))
        obj.residenceAccessInfo = ApiClient.convertToType(data['residenceAccessInfo'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} latitude
 */
MovesPlannedAddress.prototype.latitude = undefined;

/**
 * @member {Number} longitude
 */
MovesPlannedAddress.prototype.longitude = undefined;

/**
 * @member {String} city
 */
MovesPlannedAddress.prototype.city = undefined;

/**
 * @member {String} street
 */
MovesPlannedAddress.prototype.street = undefined;

/**
 * @member {String} zipcode
 */
MovesPlannedAddress.prototype.zipcode = undefined;

/**
 * @member {String} _number
 */
MovesPlannedAddress.prototype._number = undefined;

/**
 * @member {String} numberPostfix
 */
MovesPlannedAddress.prototype.numberPostfix = undefined;

/**
 * @member {String} residenceAccessInfo
 */
MovesPlannedAddress.prototype.residenceAccessInfo = undefined;

