/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import MovesEmployeeScheduleDay from './MovesEmployeeScheduleDay';

/**
 * The MovesEmployeeSchedule model module.
 * @module model/MovesEmployeeSchedule
 * @version 0.0.0
 */
export default class MovesEmployeeSchedule {
  /**
   * Constructs a new <code>MovesEmployeeSchedule</code>.
   * EmployeeSchedule model (no description)
   * @alias module:model/MovesEmployeeSchedule
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>MovesEmployeeSchedule</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MovesEmployeeSchedule} obj Optional instance to populate.
   * @return {module:model/MovesEmployeeSchedule} The populated <code>MovesEmployeeSchedule</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MovesEmployeeSchedule();
      if (data.hasOwnProperty('employeeId'))
        obj.employeeId = ApiClient.convertToType(data['employeeId'], 'Number');
      if (data.hasOwnProperty('from'))
        obj.from = ApiClient.convertToType(data['from'], 'Date');
      if (data.hasOwnProperty('to'))
        obj.to = ApiClient.convertToType(data['to'], 'Date');
      if (data.hasOwnProperty('employeeScheduleDays'))
        obj.employeeScheduleDays = ApiClient.convertToType(data['employeeScheduleDays'], [MovesEmployeeScheduleDay]);
    }
    return obj;
  }
}

/**
 * @member {Number} employeeId
 */
MovesEmployeeSchedule.prototype.employeeId = undefined;

/**
 * Describes, together with the \"to\" attribute, for which period the EmployeeSchedule was retrieved.
 * @member {Date} from
 */
MovesEmployeeSchedule.prototype.from = undefined;

/**
 * Describes, together with the \"from\" attribute, for which period the EmployeeSchedule was retrieved.
 * @member {Date} to
 */
MovesEmployeeSchedule.prototype.to = undefined;

/**
 * List of EmployeeScheduleDays that make up this EmployeeSchedule.
 * @member {Array.<module:model/MovesEmployeeScheduleDay>} employeeScheduleDays
 */
MovesEmployeeSchedule.prototype.employeeScheduleDays = undefined;

