/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The MovesMovesRatelimitError model module.
 * @module model/MovesMovesRatelimitError
 * @version 0.0.0
 */
export default class MovesMovesRatelimitError {
  /**
   * Constructs a new <code>MovesMovesRatelimitError</code>.
   * An error describing a specific rate limit has been reached and that the client should wait to retry the response
   * @alias module:model/MovesMovesRatelimitError
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>MovesMovesRatelimitError</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MovesMovesRatelimitError} obj Optional instance to populate.
   * @return {module:model/MovesMovesRatelimitError} The populated <code>MovesMovesRatelimitError</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MovesMovesRatelimitError();
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('title'))
        obj.title = ApiClient.convertToType(data['title'], 'String');
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'Number');
    }
    return obj;
  }
}

/**
 * The type of error raised
 * @member {String} type
 */
MovesMovesRatelimitError.prototype.type = undefined;

/**
 * The human readable title of the rate limit error
 * @member {String} title
 */
MovesMovesRatelimitError.prototype.title = undefined;

/**
 * The HTTP status code being given
 * @member {Number} status
 */
MovesMovesRatelimitError.prototype.status = undefined;

