/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The MovesAvailability model module.
 * @module model/MovesAvailability
 * @version 0.0.0
 */
export default class MovesAvailability {
  /**
   * Constructs a new <code>MovesAvailability</code>.
   * An availability is a period of time in which an employee or client has &#x27;something&#x27;.  Some examples of availabilities: - Employee A is sick in a period - Employee B has training every friday in a period - Employee C is on holiday for a period
   * @alias module:model/MovesAvailability
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>MovesAvailability</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MovesAvailability} obj Optional instance to populate.
   * @return {module:model/MovesAvailability} The populated <code>MovesAvailability</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MovesAvailability();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('containerId'))
        obj.containerId = ApiClient.convertToType(data['containerId'], 'Number');
      if (data.hasOwnProperty('start'))
        obj.start = ApiClient.convertToType(data['start'], 'String');
      if (data.hasOwnProperty('stop'))
        obj.stop = ApiClient.convertToType(data['stop'], 'String');
      if (data.hasOwnProperty('duration'))
        obj.duration = ApiClient.convertToType(data['duration'], 'Number');
      if (data.hasOwnProperty('validFrom'))
        obj.validFrom = ApiClient.convertToType(data['validFrom'], 'Date');
      if (data.hasOwnProperty('validTo'))
        obj.validTo = ApiClient.convertToType(data['validTo'], 'Date');
      if (data.hasOwnProperty('recurrenceType'))
        obj.recurrenceType = ApiClient.convertToType(data['recurrenceType'], 'String');
      if (data.hasOwnProperty('cycleBase'))
        obj.cycleBase = ApiClient.convertToType(data['cycleBase'], 'Date');
      if (data.hasOwnProperty('cycleInterval'))
        obj.cycleInterval = ApiClient.convertToType(data['cycleInterval'], 'Number');
      if (data.hasOwnProperty('cycleOffset'))
        obj.cycleOffset = ApiClient.convertToType(data['cycleOffset'], 'Number');
      if (data.hasOwnProperty('unitId'))
        obj.unitId = ApiClient.convertToType(data['unitId'], 'Number');
      if (data.hasOwnProperty('availabilityTypeId'))
        obj.availabilityTypeId = ApiClient.convertToType(data['availabilityTypeId'], 'Number');
      if (data.hasOwnProperty('dayPart'))
        obj.dayPart = ApiClient.convertToType(data['dayPart'], 'Number');
      if (data.hasOwnProperty('comment'))
        obj.comment = ApiClient.convertToType(data['comment'], 'String');
      if (data.hasOwnProperty('peopleType'))
        obj.peopleType = ApiClient.convertToType(data['peopleType'], 'String');
      if (data.hasOwnProperty('peopleExternalId'))
        obj.peopleExternalId = ApiClient.convertToType(data['peopleExternalId'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
MovesAvailability.prototype.id = undefined;

/**
 * @member {Number} containerId
 */
MovesAvailability.prototype.containerId = undefined;

/**
 * @member {String} start
 */
MovesAvailability.prototype.start = undefined;

/**
 * @member {String} stop
 */
MovesAvailability.prototype.stop = undefined;

/**
 * @member {Number} duration
 */
MovesAvailability.prototype.duration = undefined;

/**
 * @member {Date} validFrom
 */
MovesAvailability.prototype.validFrom = undefined;

/**
 * @member {Date} validTo
 */
MovesAvailability.prototype.validTo = undefined;

/**
 * <pre> recurrenceType: Possible values incidental whole_period recurring </pre>
 * @member {String} recurrenceType
 */
MovesAvailability.prototype.recurrenceType = undefined;

/**
 * @member {Date} cycleBase
 */
MovesAvailability.prototype.cycleBase = undefined;

/**
 * <pre> cycleInterval: Every 1 = day 7 = week 14 = 2 weeks ... </pre>
 * @member {Number} cycleInterval
 */
MovesAvailability.prototype.cycleInterval = undefined;

/**
 * <pre> cycleOffset: Which day 0 = Sunday 1 = Monday 2 = Tuesday ... </pre>
 * @member {Number} cycleOffset
 */
MovesAvailability.prototype.cycleOffset = undefined;

/**
 * @member {Number} unitId
 */
MovesAvailability.prototype.unitId = undefined;

/**
 * @member {Number} availabilityTypeId
 */
MovesAvailability.prototype.availabilityTypeId = undefined;

/**
 * <pre> Daypart 0 = Night 1 = Morning 2 = Evening ... </pre>
 * @member {Number} dayPart
 */
MovesAvailability.prototype.dayPart = undefined;

/**
 * @member {String} comment
 */
MovesAvailability.prototype.comment = undefined;

/**
 * <pre> Possible values: Employee Client </pre>
 * @member {String} peopleType
 */
MovesAvailability.prototype.peopleType = undefined;

/**
 * @member {Number} peopleExternalId
 */
MovesAvailability.prototype.peopleExternalId = undefined;

