/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The MovesAvailabilityType model module.
 * @module model/MovesAvailabilityType
 * @version 0.0.0
 */
export default class MovesAvailabilityType {
  /**
   * Constructs a new <code>MovesAvailabilityType</code>.
   * An availability types are for example: Sick, Holiday, Meeting, Training AvailabilityTypes are linked to an employee of client via an Availability
   * @alias module:model/MovesAvailabilityType
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>MovesAvailabilityType</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MovesAvailabilityType} obj Optional instance to populate.
   * @return {module:model/MovesAvailabilityType} The populated <code>MovesAvailabilityType</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MovesAvailabilityType();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('abbreviation'))
        obj.abbreviation = ApiClient.convertToType(data['abbreviation'], 'String');
      if (data.hasOwnProperty('key'))
        obj.key = ApiClient.convertToType(data['key'], 'String');
      if (data.hasOwnProperty('available'))
        obj.available = ApiClient.convertToType(data['available'], 'Boolean');
      if (data.hasOwnProperty('forEmployees'))
        obj.forEmployees = ApiClient.convertToType(data['forEmployees'], 'Boolean');
      if (data.hasOwnProperty('forClients'))
        obj.forClients = ApiClient.convertToType(data['forClients'], 'Boolean');
      if (data.hasOwnProperty('hourTypeId'))
        obj.hourTypeId = ApiClient.convertToType(data['hourTypeId'], 'Number');
      if (data.hasOwnProperty('externalHourTypeId'))
        obj.externalHourTypeId = ApiClient.convertToType(data['externalHourTypeId'], 'Number');
      if (data.hasOwnProperty('movesHourTypeId'))
        obj.movesHourTypeId = ApiClient.convertToType(data['movesHourTypeId'], 'Number');
      if (data.hasOwnProperty('defaultPayrollingType'))
        obj.defaultPayrollingType = ApiClient.convertToType(data['defaultPayrollingType'], 'String');
      if (data.hasOwnProperty('isPublic'))
        obj.isPublic = ApiClient.convertToType(data['isPublic'], 'Boolean');
      if (data.hasOwnProperty('isSynthetic'))
        obj.isSynthetic = ApiClient.convertToType(data['isSynthetic'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
MovesAvailabilityType.prototype.id = undefined;

/**
 * @member {String} name
 */
MovesAvailabilityType.prototype.name = undefined;

/**
 * @member {String} abbreviation
 */
MovesAvailabilityType.prototype.abbreviation = undefined;

/**
 * @member {String} key
 */
MovesAvailabilityType.prototype.key = undefined;

/**
 * <pre> Is person available false: unavailable (unavailability) true:  available (availability) </pre>
 * @member {Boolean} available
 */
MovesAvailabilityType.prototype.available = undefined;

/**
 * @member {Boolean} forEmployees
 */
MovesAvailabilityType.prototype.forEmployees = undefined;

/**
 * @member {Boolean} forClients
 */
MovesAvailabilityType.prototype.forClients = undefined;

/**
 * Use moves_hour_type_id instead.
 * @member {Number} hourTypeId
 */
MovesAvailabilityType.prototype.hourTypeId = undefined;

/**
 * @member {Number} externalHourTypeId
 */
MovesAvailabilityType.prototype.externalHourTypeId = undefined;

/**
 * @member {Number} movesHourTypeId
 */
MovesAvailabilityType.prototype.movesHourTypeId = undefined;

/**
 * @member {String} defaultPayrollingType
 */
MovesAvailabilityType.prototype.defaultPayrollingType = undefined;

/**
 * @member {Boolean} isPublic
 */
MovesAvailabilityType.prototype.isPublic = undefined;

/**
 * @member {Boolean} isSynthetic
 */
MovesAvailabilityType.prototype.isSynthetic = undefined;

