/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import MovesContainerAssignment from './MovesContainerAssignment';

/**
 * The MovesPlanCardOccurrenceResponseMetadataImpact model module.
 * @module model/MovesPlanCardOccurrenceResponseMetadataImpact
 * @version 0.0.0
 */
export default class MovesPlanCardOccurrenceResponseMetadataImpact {
  /**
   * Constructs a new <code>MovesPlanCardOccurrenceResponseMetadataImpact</code>.
   * Metadata about the impact of the plan card occurrence planning
   * @alias module:model/MovesPlanCardOccurrenceResponseMetadataImpact
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>MovesPlanCardOccurrenceResponseMetadataImpact</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MovesPlanCardOccurrenceResponseMetadataImpact} obj Optional instance to populate.
   * @return {module:model/MovesPlanCardOccurrenceResponseMetadataImpact} The populated <code>MovesPlanCardOccurrenceResponseMetadataImpact</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MovesPlanCardOccurrenceResponseMetadataImpact();
      if (data.hasOwnProperty('containers'))
        obj.containers = ApiClient.convertToType(data['containers'], [MovesContainerAssignment]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/MovesContainerAssignment>} containers
 */
MovesPlanCardOccurrenceResponseMetadataImpact.prototype.containers = undefined;

