/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import MovesContainerSearchRequest from './MovesContainerSearchRequest';
import MovesPlanCardOccurrence from './MovesPlanCardOccurrence';

/**
 * The MovesPlanCardOccurrenceList model module.
 * @module model/MovesPlanCardOccurrenceList
 * @version 0.0.0
 */
export default class MovesPlanCardOccurrenceList {
  /**
   * Constructs a new <code>MovesPlanCardOccurrenceList</code>.
   * A response body that contains a list of plan tasks found for this search
   * @alias module:model/MovesPlanCardOccurrenceList
   * @class
   * @param metadata {module:model/MovesContainerSearchRequest} 
   * @param planCardOccurrences {Array.<module:model/MovesPlanCardOccurrence>} 
   */
  constructor(metadata, planCardOccurrences) {
    this.metadata = metadata;
    this.planCardOccurrences = planCardOccurrences;
  }

  /**
   * Constructs a <code>MovesPlanCardOccurrenceList</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MovesPlanCardOccurrenceList} obj Optional instance to populate.
   * @return {module:model/MovesPlanCardOccurrenceList} The populated <code>MovesPlanCardOccurrenceList</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MovesPlanCardOccurrenceList();
      if (data.hasOwnProperty('metadata'))
        obj.metadata = MovesContainerSearchRequest.constructFromObject(data['metadata']);
      if (data.hasOwnProperty('planCardOccurrences'))
        obj.planCardOccurrences = ApiClient.convertToType(data['planCardOccurrences'], [MovesPlanCardOccurrence]);
    }
    return obj;
  }
}

/**
 * @member {module:model/MovesContainerSearchRequest} metadata
 */
MovesPlanCardOccurrenceList.prototype.metadata = undefined;

/**
 * @member {Array.<module:model/MovesPlanCardOccurrence>} planCardOccurrences
 */
MovesPlanCardOccurrenceList.prototype.planCardOccurrences = undefined;

