/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import MovesContainerTimeBlockType from './MovesContainerTimeBlockType';

/**
 * The MovesContainerTimeBlock model module.
 * @module model/MovesContainerTimeBlock
 * @version 0.0.0
 */
export default class MovesContainerTimeBlock {
  /**
   * Constructs a new <code>MovesContainerTimeBlock</code>.
   * A block of time in which plan cards are (not) allowed to be planned in.
   * @alias module:model/MovesContainerTimeBlock
   * @class
   * @param startDateTime {Date} The starting time of the (un)availability for this container.
   * @param endDateTime {Date} The ending time of the (un)availability for this container.
   * @param type {module:model/MovesContainerTimeBlockType} 
   * @param plannable {Boolean} Describes if we can plan inside of this time block
   */
  constructor(startDateTime, endDateTime, type, plannable) {
    this.startDateTime = startDateTime;
    this.endDateTime = endDateTime;
    this.type = type;
    this.plannable = plannable;
  }

  /**
   * Constructs a <code>MovesContainerTimeBlock</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MovesContainerTimeBlock} obj Optional instance to populate.
   * @return {module:model/MovesContainerTimeBlock} The populated <code>MovesContainerTimeBlock</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MovesContainerTimeBlock();
      if (data.hasOwnProperty('startDateTime'))
        obj.startDateTime = ApiClient.convertToType(data['startDateTime'], 'Date');
      if (data.hasOwnProperty('endDateTime'))
        obj.endDateTime = ApiClient.convertToType(data['endDateTime'], 'Date');
      if (data.hasOwnProperty('type'))
        obj.type = MovesContainerTimeBlockType.constructFromObject(data['type']);
      if (data.hasOwnProperty('plannable'))
        obj.plannable = ApiClient.convertToType(data['plannable'], 'Boolean');
    }
    return obj;
  }
}

/**
 * The starting time of the (un)availability for this container.
 * @member {Date} startDateTime
 */
MovesContainerTimeBlock.prototype.startDateTime = undefined;

/**
 * The ending time of the (un)availability for this container.
 * @member {Date} endDateTime
 */
MovesContainerTimeBlock.prototype.endDateTime = undefined;

/**
 * @member {module:model/MovesContainerTimeBlockType} type
 */
MovesContainerTimeBlock.prototype.type = undefined;

/**
 * Describes if we can plan inside of this time block
 * @member {Boolean} plannable
 */
MovesContainerTimeBlock.prototype.plannable = undefined;

