/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The OnsEhrGgzPlanStatistic model module.
 * @module model/OnsEhrGgzPlanStatistic
 * @version 0.0.0
 */
export default class OnsEhrGgzPlanStatistic {
  /**
   * Constructs a new <code>OnsEhrGgzPlanStatistic</code>.
   * GgzPlanStatistic model
   * @alias module:model/OnsEhrGgzPlanStatistic
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>OnsEhrGgzPlanStatistic</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OnsEhrGgzPlanStatistic} obj Optional instance to populate.
   * @return {module:model/OnsEhrGgzPlanStatistic} The populated <code>OnsEhrGgzPlanStatistic</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new OnsEhrGgzPlanStatistic();
      if (data.hasOwnProperty('planId'))
        obj.planId = ApiClient.convertToType(data['planId'], 'Number');
      if (data.hasOwnProperty('clientId'))
        obj.clientId = ApiClient.convertToType(data['clientId'], 'String');
      if (data.hasOwnProperty('createdAt'))
        obj.createdAt = ApiClient.convertToType(data['createdAt'], 'Date');
      if (data.hasOwnProperty('employeeId'))
        obj.employeeId = ApiClient.convertToType(data['employeeId'], 'String');
    }
    return obj;
  }
}

/**
 * The plan composition id
 * @member {Number} planId
 */
OnsEhrGgzPlanStatistic.prototype.planId = undefined;

/**
 * The client id
 * @member {String} clientId
 */
OnsEhrGgzPlanStatistic.prototype.clientId = undefined;

/**
 * When the plan was created
 * @member {Date} createdAt
 */
OnsEhrGgzPlanStatistic.prototype.createdAt = undefined;

/**
 * The employee id
 * @member {String} employeeId
 */
OnsEhrGgzPlanStatistic.prototype.employeeId = undefined;

