/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The OnsimportUploadResponse model module.
 * @module model/OnsimportUploadResponse
 * @version 0.0.0
 */
export default class OnsimportUploadResponse {
  /**
   * Constructs a new <code>OnsimportUploadResponse</code>.
   * Contains a unique id by which information about an upload can be retrieved.
   * @alias module:model/OnsimportUploadResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>OnsimportUploadResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OnsimportUploadResponse} obj Optional instance to populate.
   * @return {module:model/OnsimportUploadResponse} The populated <code>OnsimportUploadResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new OnsimportUploadResponse();
      if (data.hasOwnProperty('uploadId'))
        obj.uploadId = ApiClient.convertToType(data['uploadId'], 'String');
    }
    return obj;
  }
}

/**
 * Unique id for requesting status info about the upload.
 * @member {String} uploadId
 */
OnsimportUploadResponse.prototype.uploadId = undefined;

