/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The OpenehrItemTag model module.
 * @module model/OpenehrItemTag
 * @version 0.0.0
 */
export default class OpenehrItemTag {
  /**
   * Constructs a new <code>OpenehrItemTag</code>.
   * OpenEHR ItemTag, which is a tag with a key and optional value that is associated with a target ReferenceModelObjectWrapper.
   * @alias module:model/OpenehrItemTag
   * @class
   * @param key {String} The tag key. May not be empty or contain leading or trailing whitespace.
   */
  constructor(key) {
    this.key = key;
  }

  /**
   * Constructs a <code>OpenehrItemTag</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OpenehrItemTag} obj Optional instance to populate.
   * @return {module:model/OpenehrItemTag} The populated <code>OpenehrItemTag</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new OpenehrItemTag();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('key'))
        obj.key = ApiClient.convertToType(data['key'], 'String');
      if (data.hasOwnProperty('value'))
        obj.value = ApiClient.convertToType(data['value'], 'String');
      if (data.hasOwnProperty('targetPath'))
        obj.targetPath = ApiClient.convertToType(data['targetPath'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
OpenehrItemTag.prototype.id = undefined;

/**
 * The tag key. May not be empty or contain leading or trailing whitespace.
 * @member {String} key
 */
OpenehrItemTag.prototype.key = undefined;

/**
 * The value. If set, may not be empty.
 * @member {String} value
 */
OpenehrItemTag.prototype.value = undefined;

/**
 * Optional archetype or RM path within target, used to tag a fine-grained element.
 * @member {String} targetPath
 */
OpenehrItemTag.prototype.targetPath = undefined;

