/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import PayrollContractType from './PayrollContractType';

/**
 * The PayrollListContractTypeList model module.
 * @module model/PayrollListContractTypeList
 * @version 0.0.0
 */
export default class PayrollListContractTypeList {
  /**
   * Constructs a new <code>PayrollListContractTypeList</code>.
   * ContractTypeList model (no description)
   * @alias module:model/PayrollListContractTypeList
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>PayrollListContractTypeList</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PayrollListContractTypeList} obj Optional instance to populate.
   * @return {module:model/PayrollListContractTypeList} The populated <code>PayrollListContractTypeList</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PayrollListContractTypeList();
      if (data.hasOwnProperty('contractTypes'))
        obj.contractTypes = ApiClient.convertToType(data['contractTypes'], [PayrollContractType]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/PayrollContractType>} contractTypes
 */
PayrollListContractTypeList.prototype.contractTypes = undefined;

