/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The PortalEmployeePortalProfile model module.
 * @module model/PortalEmployeePortalProfile
 * @version 0.0.0
 */
export default class PortalEmployeePortalProfile {
  /**
   * Constructs a new <code>PortalEmployeePortalProfile</code>.
   * EmployeePortalProfile model (no description)
   * @alias module:model/PortalEmployeePortalProfile
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>PortalEmployeePortalProfile</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PortalEmployeePortalProfile} obj Optional instance to populate.
   * @return {module:model/PortalEmployeePortalProfile} The populated <code>PortalEmployeePortalProfile</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PortalEmployeePortalProfile();
      if (data.hasOwnProperty('employeeId'))
        obj.employeeId = ApiClient.convertToType(data['employeeId'], 'Number');
      if (data.hasOwnProperty('facebookEnabled'))
        obj.facebookEnabled = ApiClient.convertToType(data['facebookEnabled'], 'Boolean');
      if (data.hasOwnProperty('rosterEnabled'))
        obj.rosterEnabled = ApiClient.convertToType(data['rosterEnabled'], 'Boolean');
      if (data.hasOwnProperty('selfRosteringEnabled'))
        obj.selfRosteringEnabled = ApiClient.convertToType(data['selfRosteringEnabled'], 'Boolean');
      if (data.hasOwnProperty('selfAvailabilityEnabled'))
        obj.selfAvailabilityEnabled = ApiClient.convertToType(data['selfAvailabilityEnabled'], 'Boolean');
      if (data.hasOwnProperty('vacationHoursEnabled'))
        obj.vacationHoursEnabled = ApiClient.convertToType(data['vacationHoursEnabled'], 'Boolean');
      if (data.hasOwnProperty('employeePortalUrl'))
        obj.employeePortalUrl = ApiClient.convertToType(data['employeePortalUrl'], 'String');
      if (data.hasOwnProperty('externalWebsiteName'))
        obj.externalWebsiteName = ApiClient.convertToType(data['externalWebsiteName'], 'String');
      if (data.hasOwnProperty('sendEmailForKaminoMessage'))
        obj.sendEmailForKaminoMessage = ApiClient.convertToType(data['sendEmailForKaminoMessage'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {Number} employeeId
 */
PortalEmployeePortalProfile.prototype.employeeId = undefined;

/**
 * @member {Boolean} facebookEnabled
 */
PortalEmployeePortalProfile.prototype.facebookEnabled = undefined;

/**
 * @member {Boolean} rosterEnabled
 */
PortalEmployeePortalProfile.prototype.rosterEnabled = undefined;

/**
 * @member {Boolean} selfRosteringEnabled
 */
PortalEmployeePortalProfile.prototype.selfRosteringEnabled = undefined;

/**
 * @member {Boolean} selfAvailabilityEnabled
 */
PortalEmployeePortalProfile.prototype.selfAvailabilityEnabled = undefined;

/**
 * @member {Boolean} vacationHoursEnabled
 */
PortalEmployeePortalProfile.prototype.vacationHoursEnabled = undefined;

/**
 * @member {String} employeePortalUrl
 */
PortalEmployeePortalProfile.prototype.employeePortalUrl = undefined;

/**
 * @member {String} externalWebsiteName
 */
PortalEmployeePortalProfile.prototype.externalWebsiteName = undefined;

/**
 * @member {Boolean} sendEmailForKaminoMessage
 */
PortalEmployeePortalProfile.prototype.sendEmailForKaminoMessage = undefined;

