/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import Address from './Address';

/**
 * The TeamAddress model module.
 * @module model/TeamAddress
 * @version 0.0.0
 */
export default class TeamAddress extends Address {
  /**
   * Constructs a new <code>TeamAddress</code>.
   * The address of a team
   * @alias module:model/TeamAddress
   * @class
   * @extends module:model/Address
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>TeamAddress</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TeamAddress} obj Optional instance to populate.
   * @return {module:model/TeamAddress} The populated <code>TeamAddress</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TeamAddress();
      Address.constructFromObject(data, obj);
      if (data.hasOwnProperty('teamId'))
        obj.teamId = ApiClient.convertToType(data['teamId'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} teamId
 */
TeamAddress.prototype.teamId = undefined;

