/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import ToezichtAuditIdentity from './ToezichtAuditIdentity';
import ToezichtAuditReferences from './ToezichtAuditReferences';

/**
 * The ToezichtAudit model module.
 * @module model/ToezichtAudit
 * @version 0.0.0
 */
export default class ToezichtAudit {
  /**
   * Constructs a new <code>ToezichtAudit</code>.
   * A single exported audit
   * @alias module:model/ToezichtAudit
   * @class
   * @param createdAt {String} 
   */
  constructor(createdAt) {
    this.createdAt = createdAt;
  }

  /**
   * Constructs a <code>ToezichtAudit</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ToezichtAudit} obj Optional instance to populate.
   * @return {module:model/ToezichtAudit} The populated <code>ToezichtAudit</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ToezichtAudit();
      if (data.hasOwnProperty('activeIdentity'))
        obj.activeIdentity = ToezichtAuditIdentity.constructFromObject(data['activeIdentity']);
      if (data.hasOwnProperty('createdAt'))
        obj.createdAt = ApiClient.convertToType(data['createdAt'], 'String');
      if (data.hasOwnProperty('deploymentType'))
        obj.deploymentType = ApiClient.convertToType(data['deploymentType'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('failed'))
        obj.failed = ApiClient.convertToType(data['failed'], 'Boolean');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('references'))
        obj.references = ToezichtAuditReferences.constructFromObject(data['references']);
      if (data.hasOwnProperty('title'))
        obj.title = ApiClient.convertToType(data['title'], 'String');
    }
    return obj;
  }
}

/**
 * @member {module:model/ToezichtAuditIdentity} activeIdentity
 */
ToezichtAudit.prototype.activeIdentity = undefined;

/**
 * @member {String} createdAt
 */
ToezichtAudit.prototype.createdAt = undefined;

/**
 * @member {String} deploymentType
 */
ToezichtAudit.prototype.deploymentType = undefined;

/**
 * @member {String} description
 */
ToezichtAudit.prototype.description = undefined;

/**
 * @member {Boolean} failed
 */
ToezichtAudit.prototype.failed = undefined;

/**
 * @member {String} name
 */
ToezichtAudit.prototype.name = undefined;

/**
 * @member {module:model/ToezichtAuditReferences} references
 */
ToezichtAudit.prototype.references = undefined;

/**
 * @member {String} title
 */
ToezichtAudit.prototype.title = undefined;

