/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import LzBericht from './LzBericht';

/**
 * The WlzWlzZorglegitimatie model module.
 * @module model/WlzWlzZorglegitimatie
 * @version 0.0.0
 */
export default class WlzWlzZorglegitimatie {
  /**
   * Constructs a new <code>WlzWlzZorglegitimatie</code>.
   * WlzZorglegitimatie model (no description)
   * @alias module:model/WlzWlzZorglegitimatie
   * @class
   * @param id {Number} The id for the import
   * @param client {Number} The client
   * @param berichten {Array.<module:model/LzBericht>} A list with messages
   */
  constructor(id, client, berichten) {
    this.id = id;
    this.client = client;
    this.berichten = berichten;
  }

  /**
   * Constructs a <code>WlzWlzZorglegitimatie</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/WlzWlzZorglegitimatie} obj Optional instance to populate.
   * @return {module:model/WlzWlzZorglegitimatie} The populated <code>WlzWlzZorglegitimatie</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new WlzWlzZorglegitimatie();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('client'))
        obj.client = ApiClient.convertToType(data['client'], 'Number');
      if (data.hasOwnProperty('berichten'))
        obj.berichten = ApiClient.convertToType(data['berichten'], [LzBericht]);
    }
    return obj;
  }
}

/**
 * The id for the import
 * @member {Number} id
 */
WlzWlzZorglegitimatie.prototype.id = undefined;

/**
 * The client
 * @member {Number} client
 */
WlzWlzZorglegitimatie.prototype.client = undefined;

/**
 * A list with messages
 * @member {Array.<module:model/LzBericht>} berichten
 */
WlzWlzZorglegitimatie.prototype.berichten = undefined;

