/*
 * Nedap Ons API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import AuditedBase from './AuditedBase';

/**
 * The ZpmZpmSetting model module.
 * @module model/ZpmZpmSetting
 * @version 0.0.0
 */
export default class ZpmZpmSetting extends AuditedBase {
  /**
   * Constructs a new <code>ZpmZpmSetting</code>.
   * Setting (context, environment) in which care is being delivered.
   * @alias module:model/ZpmZpmSetting
   * @class
   * @extends module:model/AuditedBase
   * @param code {} Setting code.
   * @param legalBegin {} Legal begin date.
   * @param activeBegin {} Date that this setting becomes active for the tenant.
   * @param name {} Setting name.
   */
  constructor(code, legalBegin, activeBegin, name) {
    super();
    this.code = code;
    this.legalBegin = legalBegin;
    this.activeBegin = activeBegin;
    this.name = name;
  }

  /**
   * Constructs a <code>ZpmZpmSetting</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ZpmZpmSetting} obj Optional instance to populate.
   * @return {module:model/ZpmZpmSetting} The populated <code>ZpmZpmSetting</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ZpmZpmSetting();
      AuditedBase.constructFromObject(data, obj);
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('code'))
        obj.code = ApiClient.convertToType(data['code'], 'String');
      if (data.hasOwnProperty('legalBegin'))
        obj.legalBegin = ApiClient.convertToType(data['legalBegin'], 'Date');
      if (data.hasOwnProperty('legalEnd'))
        obj.legalEnd = ApiClient.convertToType(data['legalEnd'], 'Date');
      if (data.hasOwnProperty('activeBegin'))
        obj.activeBegin = ApiClient.convertToType(data['activeBegin'], 'Date');
      if (data.hasOwnProperty('activeEnd'))
        obj.activeEnd = ApiClient.convertToType(data['activeEnd'], 'Date');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
    }
    return obj;
  }
}

/**
 * Object identifier.
 * @member {Number} id
 */
ZpmZpmSetting.prototype.id = undefined;

/**
 * Setting code.
 * @member {String} code
 */
ZpmZpmSetting.prototype.code = undefined;

/**
 * Legal begin date.
 * @member {Date} legalBegin
 */
ZpmZpmSetting.prototype.legalBegin = undefined;

/**
 * Legal end date.
 * @member {Date} legalEnd
 */
ZpmZpmSetting.prototype.legalEnd = undefined;

/**
 * Date that this setting becomes active for the tenant.
 * @member {Date} activeBegin
 */
ZpmZpmSetting.prototype.activeBegin = undefined;

/**
 * Date that this setting stops being active for this tenant.
 * @member {Date} activeEnd
 */
ZpmZpmSetting.prototype.activeEnd = undefined;

/**
 * Setting name.
 * @member {String} name
 */
ZpmZpmSetting.prototype.name = undefined;

